### ISSUE TITLE
a crash error

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#1]
### Describe your bug here.

so... whenever i play a song while the char/bg option is a\unchecked on optimization, it keeps crashing.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/a7456d8b-3da2-4358-b52e-320de365d13a)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no?

**Comment by JordanSantiagoYT** [comment]
did you try turning off double note ghosts?

**Comment by JordanSantiagoYT** [comment]
fixed with any commit/action build later than https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/8055ba24bb8f7062f51ea4805d04a52660834eab

**Comment by SyncGit12** [comment]
this is the first issue of js engine

btw why are you here
