### ISSUE TITLE
the "gf sing" note didnt actually make the whatever character on gf not playing an animation

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#10]
### Describe your bug here.

i just noticed this problem where when the gf sing note hits the gf side doesnt really play an animation if you know how to fix this issue, thanks alot (example: this video is an example where i put random "gf sing" note and the gf is the yellow sans and if you look at it the yellow sans didnt play an animation but the regular sans did)

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/07cc2a73-9b57-4b00-acb9-c3eeeeae59f2

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
just to double check, do you have "Optimized Chart Loading" turned on? ive seen it causes some issues with gf notes
