### ISSUE TITLE
notes (i dont know how to delete last issue)

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#102]
### What feature do you want to get added on the **base** engine?

Visible notes in chart editor, if show notes disable, or this make game slowed?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by NAEL2XD** [comment]
I'm guessing the "Show Notes" option is disabled for you and you didn't notice

**Comment by JordanSantiagoYT** [comment]
i can’t do that
