### ISSUE TITLE
Chart Editor Bug???

### ISSUE THREAD

**Issue by Xenith-MROHIO6337** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#103]
### Describe your bug here.

Uh, I was zoomed out in the chart editor, i think a 16/1? and i was just seeing if there was any sort of like, notes on the opponents side that I was going to delete? and all of a sudden.. BAM! Crashed

### Command Prompt/Terminal logs (if existing)

```bash
editors/ChartingState.hx (Line 2783)
editors/ChartingState.hx (Line 2728)
editors/ChartingState.hx (Line 3070)
editors/ChartingState.hx (Line 2528)
flixel/FlxState.hx (Line 203)
flixel/FlxGame.hx (Line 752)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I do not know what I edited, :sob:

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by MemeHovy** [comment]
hmm, this doesn't add up properly, which version are you using?

**Comment by JordanSantiagoYT** [comment]
is one of the sections you're trying to load less than 4 beats long? psych engine doesn't handle half grids properly so it crashes if that's the case

**Comment by Stefan2008Git** [comment]
> is one of the sections you're trying to load less than 4 beats long? psych engine doesn't handle half grids properly so it crashes if that's the case

Update the grid gradient graphic sprite tho

**Comment by Xenith-MROHIO6337** [comment]
> hmm, this doesn't add up properly, which version are you using?

VERY SORRY FOR THE LATE RESPONSE I had my notifications off and shi. But uh, I was busy working on my FNF Mod. And I went to go zoom out to 1/16 I think, and so I thought it could go further than that, so I had clicked "Z" again (me thinking there is a 1/32), It crashed. 

OR, something is wrong and I zoomed into 1/16 then back to 1/8. I don't really know, I can't really remember that well.

**Comment by StinkTheStinker** [comment]
ohhh, i know why you are having that problem (somehow)

**Comment by StinkTheStinker** [comment]
it's because there is no 1/32. the game would break if it reaches to that point, which prob made it panic on what you want it to do, and crash. there is only one grid line on 1/16 by the way!

**Comment by moxie-coder** [comment]
hmm, looks like a waveform issue, since the 2 lines point to redrawing the waveform, I'll see what I can do
