### ISSUE TITLE
Haxe logo issue | part 2 of the issue

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#104]
### Describe your bug here.

You know how the issue is caused by the mod characters right? It's actully the double note ghost.

W/ note ghost
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/f936ecd1-864d-4cd6-a1b0-64ddea7b28ae)

Without note ghost
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/7f7b94f7-620a-4cb9-8db2-031a675f5b3d)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/3017318e-45b5-4f7f-a7df-d0d6d10fa159)
just in case if you are confused on what im talkin about

**Comment by JordanSantiagoYT** [comment]
check newest commit and see if the issue still occurs

**Comment by StinkTheStinker** [comment]
theres two thats from 17 hours ago

**Comment by JordanSantiagoYT** [comment]
the *newest* one

**Comment by JordanSantiagoYT** [comment]
aka the one that's higher

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/aad1d90b-1851-4338-ba56-78fd6d5f4bca)
bruh

**Comment by Stefan2008Git** [comment]
First of all, this is not an type of any issues, second of all, you are missing the sprite name or sprite image path for that. How the f#ck can be Double Ghost option problem?

**Comment by StinkTheStinker** [comment]
idk, i disabled it, and it was not there after

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/b058fb5f-26d1-4b0e-abd2-b7f899a7786d)

**Comment by StinkTheStinker** [comment]
also, i think you got confused on the screenshot with the option

**Comment by StinkTheStinker** [comment]
let me get a new one

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/9eeb8d48-2878-4461-a1ae-ea88e7fd2b85)

**Comment by JordanSantiagoYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/20b7d5a0-0ab5-4bb9-b42f-e84a4160b4a8

Double Note Ghosts have been confirmed to not be the problem, as I have it turned on this time and there's no haxe logo

**Comment by StinkTheStinker** [comment]
What the fuck

**Comment by StinkTheStinker** [comment]
what the shit, i don't see it now

**Comment by StinkTheStinker** [comment]
i just now noticed it

**Comment by moxie-coder** [comment]
don't see it on my end, even had the option enabled

¯\_(ツ)_/¯
