### ISSUE TITLE
VIsuals and Ui

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#107]
### What feature do you want to get added on the **base** engine?

Style fps/ram counter (psych engine, js engine 1.12.0-1.14.0, 1.15.0-1.xx.x)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> Style fps/ram counter (psych engine, js engine 1.12.0-1.14.0, 1.15.0-1.xx.x)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor and 6K+ support.

not planned, nobody would even use it

**Comment by Stefan2008Git** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > Style fps/ram counter (psych engine, js engine 1.12.0-1.14.0, 1.15.0-1.xx.x)
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > Stage Editor and 6K+ support.
> 
> not planned, nobody would even use it

He means the font style, like what i did that on my engine by my real coding on 2.9.0, so check out the
[release tag here](https://github.com/Stefan2008Git/FNF-SB-Engine/releases/tag/2.9.0) for more
