### ISSUE TITLE
Flixel Intro Addition

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#108]
### What feature do you want to get added on the **base** engine?

thats it, you can tell by the name.

i think it does sprites and sound from the assets too

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
erm.. no because it's just additional loading time

**Comment by StinkTheStinker** [comment]
what if there was a skip and an option to turn it off or on? will that still effect anything?

**Comment by Stefan2008Git** [comment]
> what if there was a skip and an option to turn it off or on? will that still effect anything

> ### What feature do you want to get added on the **base** engine?
> thats it, you can tell by the name.
> 
> i think it does sprites and sound from the assets too
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

Proper credit that was forgotten? The fuck do you mean the credit was forgotten? HaxeFlixel made an HaxeFlixel logo intro to game bruh

**Comment by StinkTheStinker** [comment]
i dont even use that option
