### ISSUE TITLE
Dialogue Editor issue

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#109]
### Describe your bug here.

When I press space to replay a part of a dialogue in the editor, it goes back to the debug menu.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

can this not be required :skull:

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
how is that possible

**Comment by StinkTheStinker** [comment]
also, i cant even change the loop offset

**Comment by StinkTheStinker** [comment]
never mind

**Comment by StinkTheStinker** [comment]
the idle offset is the ASWD
the loop offset is the Arrows

**Comment by JordanSantiagoYT** [comment]
fixed in latest commit
