### ISSUE TITLE
crashes on modchart

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#11]
### Describe your bug here.

idk why but it keeps crashing when seraphic hits the multicorn section with the modchart in its file, is there something toggle-able to stop this from happening in the settings?
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/a0d0ff01-efbe-4923-9d36-e10293e82211)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by JordanSantiagoYT** [comment]
me when Note.resizeByRatio crashes the game because of "Change Scroll Speed" events

**Comment by JordanSantiagoYT** [comment]
fixed in 1.9.0
