### ISSUE TITLE
im confused

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#110]
### Describe your problem here.

```
flixel/tweens/misc/VarTween.hx (Line 103)
flixel/tweens/misc/VarTween.hx (Line 55)
flixel/tweens/FlxTween.hx (Line 1263)
flixel/FlxGame.hx (Line 750)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: The property "y" is not numeric.
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng

```

showed that error
and im confused as fuck
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/8c761009-99d5-47f4-946f-4dd7f6e1b770)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
did you have a script that changed some y value

**Comment by StinkTheStinker** [comment]
nah

**Comment by StinkTheStinker** [comment]
i changed the capilization on the y in the dialogue.json and it stopped the error

**Comment by JordanSantiagoYT** [comment]
GUIH

**Comment by StinkTheStinker** [comment]
idek (i dont even know) why

**Comment by StinkTheStinker** [comment]
also, i changed the credit icon, and it does not work. its the same width and hight

**Comment by JordanSantiagoYT** [comment]
let me see?

**Comment by StinkTheStinker** [comment]
ill screen shot 3 of it

**Comment by JordanSantiagoYT** [comment]
nvm, trying it again showed me the bug

**Comment by StinkTheStinker** [comment]
bruh

**Comment by StinkTheStinker** [comment]
i just transfered the shit to the new commit build

**Comment by JordanSantiagoYT** [comment]
nvm, it was in the wrong folder

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/ff2df289-cb7e-4c96-b71b-e9a35b4c35ba

**Comment by StinkTheStinker** [comment]
wdym wrong folder

**Comment by JordanSantiagoYT** [comment]
like, i had two weeks that were both in different mods folders, i got confused on which one it was so i tried both.

**Comment by JordanSantiagoYT** [comment]
also, did you put your song creator icon in either assets/shared/images/songCreators or mods/(your mod name here)/images/songCreators, and make sure that the name matches exactly with what you put in the song credits icon in the chart editor?

**Comment by StinkTheStinker** [comment]
the assets way

**Comment by StinkTheStinker** [comment]
did it in the mod folder way, and it works

**Comment by StinkTheStinker** [comment]
aside from that, im gonna send you the mod thing and i need you to fast foward to cheating in story mode (week 3). i just gotta make the drive folder

**Comment by StinkTheStinker** [comment]
And I gotta take a shower

**Comment by StinkTheStinker** [comment]
Worst time possible

**Comment by StinkTheStinker** [comment]
https://drive.google.com/drive/folders/15JVFGWRUltS_-tUOah4Bo1wCaVD8Ll7E?usp=sharing
there you go

**Comment by StinkTheStinker** [comment]
you can test it out tomorrow

**Comment by JordanSantiagoYT** [comment]
just tried this

there's no haxe logo?? even with double ghosts on

**Comment by StinkTheStinker** [comment]
what the fuck

**Comment by Stefan2008Git** [comment]
> did you have a script that changed some y value

It can be the script that had an wrong FlxTween functions, i mean the ``doTweenY`` and ``doTweenX`` had something wrong

**Comment by Stefan2008Git** [comment]
> also, did you put your song creator icon in either assets/shared/images/songCreators or mods/(your mod name here)/images/songCreators, and make sure that the name matches exactly with what you put in the song credits icon in the chart editor?

Can you make it for mod support instead for shared folder shit? It's so annoying to put song image file to shared instead on mods/images/credits/song for example

**Comment by JordanSantiagoYT** [comment]
i did add mods folder support? it’s just i don’t think it supports if you directly put it in mods/, especially if your mod is mostly done using assets

**Comment by JordanSantiagoYT** [comment]
heck, look in my BFBL videos. JJ1982’s icon is in mods/funnysongs/images/songCreators/

**Comment by Stefan2008Git** [comment]
> heck, look in my BFBL videos. JJ1982’s icon is in mods/funnysongs/images/songCreators/

Please change it to `mods/images/credits/funnySongs/songCreators`. Thank you

**Comment by JordanSantiagoYT** [comment]
NO, that will just make the current mods folder support even worse.

**Comment by Stefan2008Git** [comment]
> NO, that will just make the current mods folder support even worse.

You sure? I think for some people is not

**Comment by StinkTheStinker** [comment]
tf is goin on :skull:

**Comment by JordanSantiagoYT** [comment]
> > NO, that will just make the current mods folder support even worse.
> 
> You sure? I think for some people is not

having it in (mod)/images/songCreators makes more sense because you can put mod specific credits and you won’t have to bundle the entire engine with that mod

**Comment by moxie-coder** [comment]
gonna assume this is fixed since it's old as shit now
