### ISSUE TITLE
New rating option | i will give you a break after this request, i swear

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#111]
### What feature do you want to get added on the **base** engine?

rating option is called "no more cussing guys"

idk if this is allowed tbh

the ratings
![bad](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/8eda3ead-6de9-416d-96c7-37b7678f0c36)
![good](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/2d88f5d9-7078-4cb3-b1e7-cc986cc7e1ac)
![sick](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a0a9eaa0-d062-4cee-8d93-bff0fecf83e9)
![shit](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/4316c451-be37-4707-b0c4-f092fd47bcf6)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by StinkTheStinker** [comment]
bruh = bad
spongbobsad = shit
nice=good
wow!=good

**Comment by StinkTheStinker** [comment]
i mean, hey, if a family friendly channel (for example "PGHLfilms"). they can use this option.

**Comment by StinkTheStinker** [comment]
ima go to sleep btw, so expect very late (or after school) responses. since i have github on my phone now

**Comment by StinkTheStinker** [comment]
bambi reference!11!!11!1

**Comment by JordanSantiagoYT** [comment]
you're missing a marvelous rating

**Comment by StinkTheStinker** [comment]
> you're missing a marvelous rating

I'll do that when I get home

**Comment by StinkTheStinker** [comment]
is marv.png the one?

**Comment by JordanSantiagoYT** [comment]
yeah

**Comment by StinkTheStinker** [comment]
k

**Comment by StinkTheStinker** [comment]
idk if combo is optional, so ill add both of them

images:
![combo](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/630da1d4-fd6b-4d7b-aa43-3e8bbf59196a)
![marv](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/7ce15848-246d-4f6a-a8b6-ca91a27e062b)

**Comment by StinkTheStinker** [comment]
idk if it works as well

**Comment by JordanSantiagoYT** [comment]
what about the pixelated ratings? (the pixel versions of ratings that only occur when playing a week 6 song)

**Comment by StinkTheStinker** [comment]
i didnt make them, you want me to make them rq?

**Comment by JordanSantiagoYT** [comment]
i mean sure

**Comment by StinkTheStinker** [comment]
aight, ill do em

**Comment by StinkTheStinker** [comment]
nvm i cant

**Comment by StinkTheStinker** [comment]
just add a note to the description that says: "theres no pixeled ones though"

**Comment by JordanSantiagoYT** [comment]
ok

**Comment by StinkTheStinker** [comment]
you will credit me for it, right?

**Comment by JordanSantiagoYT** [comment]
yeah, but how????????

**Comment by StinkTheStinker** [comment]
oh shit

**Comment by StinkTheStinker** [comment]
now you just said that

**Comment by StinkTheStinker** [comment]
i got confused with the credits themed description

**Comment by JordanSantiagoYT** [comment]
i just tested it out, it has an insane amount of lag because the number sprites are missing

**Comment by StinkTheStinker** [comment]
bruh

**Comment by StinkTheStinker** [comment]
hold on

**Comment by StinkTheStinker** [comment]
there should be countdown options

**Comment by StinkTheStinker** [comment]
like that animated go from gapple

**Comment by StinkTheStinker** [comment]
anyway, im done
![num5](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/085fbac5-f6a6-4b73-809b-cd5c359ade85)
![num6](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/6c58d2af-ccf2-4361-be87-c04b2af1271f)
![num7](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/cca78478-6921-444a-ae4c-bad81d7e241c)
![num8](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/f310834a-ad43-41c1-bcf6-748f0db3d4de)
![num9](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/5ae85c16-dbb7-49b2-ac7e-e03b1a023d28)
![num0](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a5f47772-e72d-4950-8466-a810aadac7d6)
![num1](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/68227939-42ec-4288-bc1d-66bee4e4a4e9)
![num2](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/2de6be5a-469f-4fa7-b05b-b56b71fd7a24)
![num3](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/46e2f99e-e888-4c36-a7e3-42516da084b7)
![num4](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a93af24c-5b37-46fe-8f8b-947c6e3a9166)

**Comment by StinkTheStinker** [comment]
how do i get the gold ratings off
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/6d715f5e-7756-4bb4-9a75-11afc0c4b701)

**Comment by JordanSantiagoYT** [comment]
turn

> how do i get the gold ratings off ![image](https://private-user-images.githubusercontent.com/145304742/290688369-6d715f5e-7756-4bb4-9a75-11afc0c4b701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTkyMzEsIm5iZiI6MTcwMjU5ODkzMSwicGF0aCI6Ii8xNDUzMDQ3NDIvMjkwNjg4MzY5LTZkNzE1ZjVlLTc3NTYtNGJiNC05YTc1LTExYWZjMGM0YjcwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwMDA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTA4MDhkZDM1YTY4ODk3Mzg4ZDhkNmU1NjQ1N2VmN2ZkYWQzMGZjZTljODhmOWJmNzEzYTAwODM5NWY1NjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ax1DyKZJuzlJCN-mt5wfuBxXVK-E_FjC6BWqn4OxI1Q)

turn off the rating popups entirely, unless you're trying to get the funny nmcw ratings

**Comment by StinkTheStinker** [comment]
i just want the gold ones gone

**Comment by JordanSantiagoYT** [comment]
go to options -> visuals & ui -> marvelous rating color

**Comment by StinkTheStinker** [comment]
ima go ahead and close this
