### ISSUE TITLE
buuggg

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#112]
### Describe your bug here.

I understood why I can’t log into the chart editor, because I don’t get into chart mode. It is advisable to fix this, it is inconvenient to simply re-enter the chart editor, test by launching it (events are not supported in the test editor), test, and repeat these circles.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using source code

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
I did not understand this. i can enter and exit the chart editor just fine.

**Comment by StinkTheStinker** [comment]
the test for the chart editor is only for making sure if the notes are on time of a new voice note, if you want to play it fully in charting mode, press enter in the chart editor

**Comment by StinkTheStinker** [comment]
if you want to get out of the testing, press escape again

**Comment by StinkTheStinker** [comment]
look at the ctrl's on the bottom right of the chart editor, and you will understand stuff more

**Comment by bimbifan** [comment]
> Я этого не понял. я могу нормально входить и выходить из редактора диаграмм.
uh no, I just don't get into chart mode and can't go into the editor.

**Comment by StinkTheStinker** [comment]
go to `settings>gameplay>disable chart editor` and make sure if thats off. if the issue is still happening, test the chart editor with no mods in it (seperate JS Engine from the one with the mods)
