### ISSUE TITLE
Broken events

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#113]
### Describe your bug here.

I feel like the has to do with the recent updates but some events I used to use just stopped working, the biggest one being a flash event. dk what else to add cause im tired [other than adding the events](https://drive.google.com/drive/folders/1XT1L33PlQppP6JhmvKgLIzj3Mxcpq8YK?usp=sharing). also have you changed how the add cam zoom event works? it seems like its effects have doubled since i last used it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I can't remember at this point. All my charts are in copied versions of themselves (like copying the folder and reusing it)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
at least show a video of whats going on

**Comment by JordanSantiagoYT** [comment]
yeah.. show a video. i didn't touch any of the lua stuff. you're probably just tired and not adding the events correctly

**Comment by JordanSantiagoYT** [comment]
Also, i didn't touch the Add Camera Zoom event.

**Comment by StinkTheStinker** [comment]
yea, i dont remember him adding a cam zoom

**Comment by JordanSantiagoYT** [comment]
no, the engine has an Add Camera Zoom event built in, but i didn't touch that

**Comment by StinkTheStinker** [comment]
then i prob got myself confused on the custom events i have

**Comment by SMWpalkia** [comment]
sorry i completely forgot about this. i figured it out myself so sorry for wasting yalls time
