### ISSUE TITLE
(is MediaFire allowed in forms?)

### ISSUE THREAD

**Issue by REALCraylenGD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#114]
### What is your question?

So, I want to be able to suggest a song one day. For the link of the song, can I use MediaFire? (The only reason I'm asking here is because I don't have a Google account and I don't have a YouTube account)

**Comment by JordanSantiagoYT** [comment]
ehh,, it's weird that you asked here but.. mediafire is kinda allowed.

**Comment by StinkTheStinker** [comment]
if its not a virus, its fine

**Comment by StinkTheStinker** [comment]
also, we can use winrar to make sure if theres no virus
