### ISSUE TITLE
option missed

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#115]
### Describe your bug here.

in the note color style option when you set "quant-based" it gives a null object reference.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using source code

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
did you enable "Enable Note Colors"? that needs to be enabled

**Comment by bimbifan** [comment]
> did you enable "Enable Note Colors"? that needs to be enabled

strange, other variations can work without it

**Comment by bimbifan** [comment]
> did you enable "Enable Note Colors"? that needs to be enabled



> did you enable "Enable Note Colors"? that needs to be enabled
now enable, all works

**Comment by bimbifan** [comment]
now on, all works

**Comment by bimbifan** [comment]
nvm, my carelessness, by the way, how do notes in the char-based option acquire the color of the character? does this need to be done somewhere separately or is the game oriented according to the character’s avatar?

**Comment by JordanSantiagoYT** [comment]
> nvm, my carelessness, by the way, how do notes in the char-based option acquire the color of the character? does this need to be done somewhere separately or is the game oriented according to the character’s avatar?

The colors are grabbed based off the character's health bar color, this is done by each note grabbing the character's PlayState.instance.(character).healthColorArray values according to which type of note it is.

If the note must be pressed, then it grabs bf's health color array. 
If not, it grabs dad's health color array.
If the note is a GF note, it grabs GF's health color array.
Once a change character event is applied, all notes on screen and after grab the new character's healthColorArray values accordingly.
