### ISSUE TITLE
question about a forked source code (using this)

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#116]
### What is your question?

does it compile it self or do i have to compile it?

**Comment by StinkTheStinker** [comment]
also, you should add the stuff thats from the funkin github and the psych github to the `quick SETUP.bat`

**Comment by StinkTheStinker** [comment]
so the the thing is more easier to compile

**Comment by JordanSantiagoYT** [comment]
you have to compile it, and no i won't add that stuff
