### ISSUE TITLE
I fixed the stretched corners on the long version of the Dave and Bambi Health Bar

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#117]
### What feature do you want to get added on the **base** engine?

This:
![longDnBHealthBar](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89111294/41a5301a-28c0-41d8-8ae4-c297689593c6)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
added
