### ISSUE TITLE
Js Engine Android Build 

### ISSUE THREAD

**Issue by HolyBamber** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#118]
### What needs to be documented?

I was about to download Js Engine Android Build again but I should keep it instead of uninstalling it again until I noticed that the Android, Linux, Mac, and Windows downloads had expired, I creating my Dave and Bambi chart and I need the Android Build so I can test it again if I can tell if it's good. The Lastest Psych Engine is a Android Build 0.7.1 and it lags with botplay so I need no botplay lag from your engine.

**Comment by JordanSantiagoYT** [comment]
Wait 4 days.
