### ISSUE TITLE
Chart editor

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#120]
### What feature do you want to get added on the **base** engine?

chart scrolling speed, for example: bpm: 522, and zoom 64, and you can set the scrolling speed and type everything much more conveniently!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by StinkTheStinker** [comment]
this makes no sense

**Comment by JordanSantiagoYT** [comment]
1. You passed the test
2. this makes no sense

**Comment by StinkTheStinker** [comment]
i pass the test?

**Comment by JordanSantiagoYT** [comment]
> i pass the test?

i was replying to the person that made the issue

**Comment by StinkTheStinker** [comment]
oh

**Comment by bimbifan** [comment]
> 1. Вы прошли тест

Well, actually it does, because the diagram editor just scrolls unrealistically fast

**Comment by bimbifan** [comment]
> 1. Вы прошли тест
> 2. это не имеет никакого смысла

well actually that makes a little sense because the chart editor scrolls very quickly

**Comment by bimbifan** [comment]
no, this function helps to chart, not view the chart

**Comment by JordanSantiagoYT** [comment]
> > 1. Вы прошли тест
> > 2. это не имеет никакого смысла
> 
> well actually that makes a little sense because the chart editor scrolls very quickly

you can literally use the zoom?? this suggestion is kinda useless

**Comment by bimbifan** [comment]
Well yes, I use zoom and the c key, but is there another way? Sometimes I can use shift with c

**Comment by NAEL2XD** [comment]
Wait did you mean EZ spam?

**Comment by bimbifan** [comment]
> Wait did you mean EZ spam?
No, about adding graph scrolling speed, it’s just that when using Shift the graphs are distorted

**Comment by bimbifan** [comment]
> Wait did you mean EZ spam?

No, about adding graph scrolling speed, it’s just that when using Shift the graphs are distorted

**Comment by JordanSantiagoYT** [comment]
..that’s intentional? the chart editor literally has a tip text that tells you that your chart moves 4x faster while holding SHIFT

**Comment by StinkTheStinker** [comment]
yea, you can do that

**Comment by StinkTheStinker** [comment]
pay attention to the controls on the chart editor more

**Comment by bimbifan** [comment]
Okay, I'll use shift for now, but how do I make such smooth graphs? Or am I just not able to do it carefully?
