### ISSUE TITLE
cant think of a title

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#121]
### What feature do you want to get added on the **base** engine?

in the data tab, there should be health drain when the opponent sings, adjustable health drain to. just not to the point that will kill you

to turn it on, there needs to be a number over "0"
to keep it off, make it "0"

yes, i know theres an option for the health drain in settings, it's like a force `health drain` thing

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by JordanSantiagoYT** [comment]
No.

the reason is because that's an OS Engine feature, and the Gameplay Modifiers has a setting for that

**Comment by StinkTheStinker** [comment]
oh

**Comment by StinkTheStinker** [comment]
ill close this then
