### ISSUE TITLE
An early/late counter

### ISSUE THREAD

**Issue by MrSropical** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#123]
### What feature do you want to get added on the **base** engine?

you know those early/late counter that are mic'd up or forever engine, well it's the thing

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
we don't need to add more judgements to the list.

**Comment by MrSropical** [comment]
> we don't need to add more judgements to the list.

i know we don't need in the judgements counter like ddto+ just like in the rating
