### ISSUE TITLE
Problem with Discord Presence (the playing game section)

### ISSUE THREAD

**Issue by Ollieq1977336** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#124]
### Describe your bug here.

Hello. Theres a problem with the discord presence not showing. it was happening since 1.16 but I didn't realise.
Ive attached a screenshot to the issue. FNF JS engine is open.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/112081585/1b6bfd9d-b906-4422-8002-6d0c07fc9248)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just added a few mods.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
this doesn't add up. i didn't touch the discord rpc code.

**Comment by JordanSantiagoYT** [comment]
also, since i don't have discord I can't really offer much help with fixing this.
