### ISSUE TITLE
Pixel NoteSplashes

### ISSUE THREAD

**Issue by Sussusen** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#125]
### What feature do you want to get added on the **base** engine?

A pixel notesplashes
![655fb4d8ece54](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/154748133/9d5b8920-5981-4cac-ba35-b96638037ba5)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
not planned and won't add, i tried but the best result was either red note splashes, black or white splashes
