### ISSUE TITLE
spotlight event | you can say no if the coding will be complicated or some shit, idfk

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#126]
### What feature do you want to get added on the **base** engine?

you should already know by the name. theres two options of the types
1: separate events of the Dave and Bambi Style and the OG one (what im saying is that, if you want to add the Dave and Bambi Spotlight, you can go ahead and do this option)

2: Only the og (basically just fix the event script)

it's quicker if you fix the event script first

Txt files:
--------------if it's option 2--------------
Use the txt file that came with it

--------------if it's option 1--------------
For the Dave and Bambi One:
```
Value 1: On or Off

Value 2: type of ease (quartOut is default and reccomended)

Note about Value 2: if it's blank, it will be quartOut for default
```
For the OG one:
the one that came with it

sorry if it's confusing!

_that felt like a fuckin essay_

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
this can already be done in Lua, so no
