### ISSUE TITLE
Editor constantly crashing when modifying events

### ISSUE THREAD

**Issue by TheTrueAccount** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#127]
### Describe your bug here.

There was a common bug in last versions that dropped your fps to 1-5 when using the editor for like 10 minutes or using too much zoom
With the latest version it made this really frequent to the point that i cant even modify an event without making the game crash and this issue is new because it was not happening in previous versions, making the editor really inestable on 1.17
i know for fact that the issue is not related with my pc 
This is how it looks like on a video, i can speedrun and make the game crash in less than 2 minutes

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/144788620/bbb7d479-be1a-47dd-b972-549d00fe7d54

### Command Prompt/Terminal logs (if existing)

Its a preformance bug

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by TheTrueAccount** [comment]
here is the video since it looks like it didnt uploaded on the post
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/144788620/bbb7d479-be1a-47dd-b972-549d00fe7d54

**Comment by JordanSantiagoYT** [comment]
i know a few things that could be the cause:
me when Constant grid updating in sections with enormous amounts of notes:

**Comment by JordanSantiagoYT** [comment]
new commit, should fix this
