### ISSUE TITLE
what

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#128]
### Describe your bug here.

what

### Command Prompt/Terminal logs (if existing)

```bash
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/cpp/_std/sys/io/File.hx (Line 30)
editors/ChartingState.hx (Line 3212)
editors/ChartingState.hx (Line 3176)
editors/ChartingState.hx (Line 3171)
editors/ChartingState.hx (Line 3149)
editors/ChartingState.hx (Line 2069)
flixel/FlxState.hx (Line 203)
flixel/FlxGame.hx (Line 752)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 550)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: [file_contents,assets/characters/bf.json]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah, i don't think so. can this not be required though?

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
i forgot the screenshot, but it's lost in the files

**Comment by StinkTheStinker** [comment]
lightshot moment

**Comment by StinkTheStinker** [comment]
but that happened while i was playing the song in charting mode

**Comment by StinkTheStinker** [comment]
im also using 1.16 still, since i dont want to update for now

**Comment by StinkTheStinker** [comment]
`

> C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/cpp/_std/sys/io/File.hx (Line 30)

`

what the fuck is this

**Comment by JordanSantiagoYT** [comment]
Missing character file

**Comment by StinkTheStinker** [comment]
it was in charting tho?

**Comment by JordanSantiagoYT** [comment]
Reproduced issue
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/70f57afd-b449-4820-ad5a-d4300e357fdf

**Comment by StinkTheStinker** [comment]
wha
