### ISSUE TITLE
game freeze bug

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#129]
### Describe your bug here.

it was letting me do the game stuff, like playing the audio, but it was frozen. but then it completely froze. ill try to get an another recording of it when it happens again

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nuh uh

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by moxie-coder** [comment]
make sure you have your audio files in the game for the current song as "Inst.ogg" and or "Voices.ogg", and make sure you didn't just rename the extension, otherwise they will not work
