### ISSUE TITLE
json spritesheet not working

### ISSUE THREAD

**Issue by RedcappedmelonYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#131]
### Describe your bug here.

i tested mouse from w.i with json spritesheet but it ain't working

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't know

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

**Comment by JordanSantiagoYT** [comment]
Can you actually send me a picture/screenshot of this happening?

**Comment by StinkTheStinker** [comment]
fr

**Comment by RedcappedmelonYT** [comment]
> Can you actually send me a picture/screenshot of this happening?

ok

**Comment by RedcappedmelonYT** [comment]
> Can you actually send me a picture/screenshot of this happening?

![Screenshot_20231229_113919](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/155062363/664c0abe-a870-41fc-854b-44e5e752a81c)

**Comment by JordanSantiagoYT** [comment]
does your image actually exist in mods/images/characters or assets/shared/images/characters

**Comment by RedcappedmelonYT** [comment]
> does your image actually exist in mods/images/characters or assets/shared/images/characters

yes, but I don't use a xml for character, instead, i use json for all poses

**Comment by JordanSantiagoYT** [comment]
> > does your image actually exist in mods/images/characters or assets/shared/images/characters
> 
> yes, but I don't use a xml for character, instead, i use json for all poses

Your XML is supposed to exist along with the image, or it doesn't work

**Comment by RedcappedmelonYT** [comment]
> > > does your image actually exist in mods/images/characters or assets/shared/images/characters
> > 
> > 
> > yes, but I don't use a xml for character, instead, i use json for all poses
> 
> Your XML is supposed to exist along with the image, or it doesn't work

![Screenshot_20231229_114312_ZArchiver](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/155062363/3c9889a4-11ce-471a-813a-0efdbc86db9e)
some how i use json since there is no xml and i was gonna test it jordan, also add json support for characters

**Comment by JordanSantiagoYT** [comment]
ok why are you trying to port the characters directly from the mod, that isn't going to work because character support in this game is different

**Comment by RedcappedmelonYT** [comment]
> ok why are you trying to port the characters directly from the mod, that isn't going to work because character support in this engine is different from the wi engine

idk I'll make it as xml this time

**Comment by RedcappedmelonYT** [comment]
> ok why are you trying to port the characters directly from the mod, that isn't going to work because character support in this engine is different from the wi engine

also ok
