### ISSUE TITLE
add crossfade options

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#132]
### What feature do you want to get added on the **base** engine?

add crossfade options like denpa engine instead of just imposter v4 ghost

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
i would but there isnt much i can do since that would give me no choice but to use denpa code, which can get this engine in serious trouble

**Comment by moxie-ahegaokami** [comment]
> i would but there isnt much i can do since that would give me no choice but to use denpa code, which can get this engine in serious trouble

I was a former developer, I say you can, just give credit for the code you use

**Comment by JordanSantiagoYT** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

are you sure that i actually can

**Comment by moxie-coder** [comment]
> hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
> 
> are you sure that i actually can

yeah, I’ve talked with AT about it before

**Comment by JordanSantiagoYT** [comment]
> > hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
> > are you sure that i actually can
> 
> yeah, I’ve talked with AT about it before

ahhhhhhhhhh ok
