### ISSUE TITLE
game randomly crashes when i load up a song

### ISSUE THREAD

**Issue by BuatedsFNF** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#133]
### Describe your problem here.

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/113240120/f41b2ebe-0ebb-4366-b4c2-07bc9c599a9c

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BuatedsFNF** [comment]
[JSEngine_2023-12-28_19'25'20.log](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/files/13788017/JSEngine_2023-12-28_19.25.20.log)
heres the crash

**Comment by JordanSantiagoYT** [comment]
health icon issue, possibly happening because you have no icon (which uses the placeholder one)

**Comment by BuatedsFNF** [comment]
OHHHHHHhhhhhhh ok thanks
