### ISSUE TITLE
is there a way to limit ram?

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#134]
### What is your question?

im not sure if the problem is memory but usually when im in the middle into a song thats like 6-20 minutes long  , my game starts subtly lagging , then it starts getting laggier , then the game stops responding

**Comment by StinkTheStinker** [comment]
I don't think there is. You can check the optimization category in settings and try to see.

**Comment by StinkTheStinker** [comment]
What specs do you have anyway?

**Comment by JordanSantiagoYT** [comment]
because of haxeflixel limitations, there's no way to limit how much ram the engine can use.

well, MAYBE this can be done but nobody's quite figured it out yet
