### ISSUE TITLE
Press 7 VIdeo Event

### ISSUE THREAD

**Issue by BobEnjoyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#136]
### What is your question?

I used the option to play a video instead of going to chart editor when pressing 7. When I did it, the video played, but then after the game just stayed at a standstill, showing the icons and healthbar of the characters in the song but nothing else. Is this intentional to do this after playing the video?

**Comment by StinkTheStinker** [comment]
It's not ment to happen, idk why he added the play video in the first place

**Comment by JordanSantiagoYT** [comment]
i have changed the event with a recent commit, to close the game after the video completes
