### ISSUE TITLE
Character render in freeplay

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#137]
### What feature do you want to get added on the **base** engine?

i know the coding will be difficult, but, explanation in the pics below:
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/41d180bc-e9f2-4f36-bbe5-a112dfc69c77)
for the week editor looks on freeplay:
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/095e6a9b-fd3a-4886-9c46-179394c8d489)
i forgot to add the "json anim" one, but it's fine.

if you are wondering about an extra opponent one, do this layout, this is optional by the way:
```
Selected Json: dave (opponent 1), bambi (opponent 2)
Selected Json anim: hey, idle
```
idk if you know this type of coding btw

also, if the selected json anim is blank, it will be set to idle as default

if the json uses the "playable character" option, flip the x-axis

i also don't know what proper credit to do

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by StinkTheStinker** [comment]
you should prob add "Make static"
if checked=only the last frame of the anim
if not checked=loop the anim
dont think you will though

**Comment by StinkTheStinker** [comment]
ill look at this tomorrow

**Comment by JordanSantiagoYT** [comment]
...Why would this be needed?

**Comment by StinkTheStinker** [comment]
if someone does not know what the character(s) will be. there's that

**Comment by Stefan2008Git** [comment]
> ...Why would this be needed?

Oh, i know why, because the character and them spritesheet will use an your fucking RAM memory peak 😐
