### ISSUE TITLE
music died

### ISSUE THREAD

**Issue by ARandomLocal** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#138]
### Describe your bug here.

basically all the music has just stopped working

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, don't think so

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

**Comment by NAEL2XD** [comment]
Either:
- you pressed 0 (and it mutes) but didn't even press + to turn on the music
- you deleted all the ogg music

**Comment by ARandomLocal** [comment]
just realised i pressed 0, im an idiot, thanks for letting me know
