### ISSUE TITLE
Control Z working too well

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#139]
### Describe your bug here.

I'm not sure if this has been mentioned before but randomly when I use ctrl Z in the chart editor, it just undoes all the progress I've made up until the last save. I don't have a video cause it's hard to know when this will happen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Mostly events but nothing major

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
if your song has more than 50k notes, then i suggest not using CTRL+Z as trying to save an undo with more than 50K notes.. won't save the last change you did. this is to prevent extreme memory usage and because it also does extreme lag
