### ISSUE TITLE
Error compiling the game

### ISSUE THREAD

**Issue by Diego0160** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#140]
### Describe your problem here.

I have tried to compile the game, solving several errors that have occurred, but I am stuck with this one and I have no idea how to fix it.

Here are the terminal logs

`D:\Downloads\FNF\Engines\FNF-PsychEngine-NoBotplayLag-1.17.0> lime test linux`
`D:/Downloads/FNF/Engines/FNF-PsychEngine-NoBotplayLag-1.17.0/.haxelib/discord_rpc/git/discord_rpc/DiscordRpc.hx:4: characters 8-20 : You cannot access the cpp package while targeting neko (for cpp.Function)`
`source/Discord.hx:7: characters 8-30 : ... referenced here`
`source/Main.hx:16: characters 8-15 : ... referenced here`
`export/release/neko/haxe/ApplicationMain.hx:321: characters 48-52 : ... referenced here`

PD: I am compiling from Windows, since compiling from Linux sends more errors (unless I fix it)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, everything fresh from the source code

**Comment by JordanSantiagoYT** [comment]
i don't think it's going to work if you try compiling a linux build from windows 😭
windows builds need to be compiled on windows, mac builds need to be compiled on macOS, and linux builds need to be compiled on linux.

**Comment by StinkTheStinker** [comment]
since people usually play fnf on windows, just do windows

**Comment by Diego0160** [comment]
> since people usually play fnf on windows, just do windows

yep, although it is not my main operating system

**Comment by Diego0160** [comment]
I think I already saw the error, the discord_rpc repository was not imported correctly
Now the only error it shows is this:
`/media/diego/60CC-1C0C/Downloads/FNF/Engines/FNF-PsychEngine-NoBotplayLag-1.17.0/.haxelib/flixel/5,2,2/flixel/group/FlxSpriteGroup.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)`

**Comment by JordanSantiagoYT** [comment]
Remove SScript

**Comment by StinkTheStinker** [comment]
> Remove SScript

quick question, where is that?

**Comment by JordanSantiagoYT** [comment]
> > Remove SScript
> 
> quick question, where is that?

uhh.. haxelib remove SScript

**Comment by Diego0160** [comment]
Sscript library is not installed, the error still remains

**Comment by JordanSantiagoYT** [comment]
New commit, should fix this issue

**Comment by Diego0160** [comment]
The new commit works, but a new error arose in the same file in a different line of code

`/media/diego/60CC-1C0C/Downloads/FNF/Engines/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,2,2/flixel/FlxG.hx:3: characters 8-17 : You cannot access the flash package while in a macro (for flash.Lib)`

**Comment by JordanSantiagoYT** [comment]
Idk about any more of the macro stuff

**Comment by moxie-coder** [comment]
> The new commit works, but a new error arose in the same file in a different line of code
> 
> `/media/diego/60CC-1C0C/Downloads/FNF/Engines/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,2,2/flixel/FlxG.hx:3: characters 8-17 : You cannot access the flash package while in a macro (for flash.Lib)`

you didn't update

**Comment by JordanSantiagoYT** [comment]
> > The new commit works, but a new error arose in the same file in a different line of code
> > `/media/diego/60CC-1C0C/Downloads/FNF/Engines/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,2,2/flixel/FlxG.hx:3: characters 8-17 : You cannot access the flash package while in a macro (for flash.Lib)`
> 
> you didn't update

no apparently the project.xml needs a few additional settings to allow the engine to use the flash package

**Comment by Stefan2008Git** [comment]
> > > The new commit works, but a new error arose in the same file in a different line of code
> > > `/media/diego/60CC-1C0C/Downloads/FNF/Engines/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,2,2/flixel/FlxG.hx:3: characters 8-17 : You cannot access the flash package while in a macro (for flash.Lib)`
> > 
> > 
> > you didn't update
> 
> no apparently the project.xml needs a few additional settings to allow the engine to use the flash package

This guy had an fucking latest Haxe version. He needs to use the 4.2.5 for fix

**Comment by Diego0160** [comment]
Yes you're right
Automatically updated via APT
It was complicated to reinstall it because the repository is obsolete and can only be done manually from the haxe source code but I already have it installed.
Now the only error that shows me is from hxCódec, in the libvlccore.so.9 library
The error is the following: 
```
/usr/bin/ld:/home/diego/Games/FNF/FNF-PsychEngine-NoBotplayLag-1.18.0/.haxelib/hxCodec/2,5,1/lib/vlc/lib/Linux/libvlccore.so.9: file format not recognized; treating as linker script
/usr/bin/ld:/home/diego/Games/FNF/FNF-PsychEngine-NoBotplayLag-1.18.0/.haxelib/hxCodec/2,5,1/lib/vlc/lib/Linux/libvlccore.so.9:0: syntax error
```

**Comment by Stefan2008Git** [comment]
> Yes you're right Automatically updated via APT It was complicated to reinstall it because the repository is obsolete and can only be done manually from the haxe source code but I already have it installed. Now the only error that shows me is from hxCódec, in the libvlccore.so.9 library The error is the following:
> 
> ```
> /usr/bin/ld:/home/diego/Games/FNF/FNF-PsychEngine-NoBotplayLag-1.18.0/.haxelib/hxCodec/2,5,1/lib/vlc/lib/Linux/libvlccore.so.9: file format not recognized; treating as linker script
> /usr/bin/ld:/home/diego/Games/FNF/FNF-PsychEngine-NoBotplayLag-1.18.0/.haxelib/hxCodec/2,5,1/lib/vlc/lib/Linux/libvlccore.so.9:0: syntax error
> ```

You have the weirdest libvlcvcore version installed

**Comment by Diego0160** [comment]
I know, it was something unexpected after installing the libraries

**Comment by moxie-coder** [comment]
I would suggest reinstalling hxCodec 2.5.1, or updating since latest versions should work

**Comment by Diego0160** [comment]
Yep, Updating it solves the problem thx

**Comment by moxie-coder** [comment]
> Yep, Updating it solves the problem thx

np
