### ISSUE TITLE
character

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#143]
### What is your question?

When a character has only 1 animation (idle), he moves with its task (for example, a note to the left, he moves to the left) and the animation is replayed. Is it possible to solve this?

**Comment by JordanSantiagoYT** [comment]
Make the sing animations, but make them all with the same animation and offsets as the idle animations

**Comment by bimbifan** [comment]
At first I did so, but then the animation began to repeat itself

**Comment by JordanSantiagoYT** [comment]
...that's normal..? because the animation is binded to all 4 arrows, hitting one will loop the anim from the start

**Comment by JordanSantiagoYT** [comment]
if you don't want it to loop, then you have to make all the notes "No Animation"

**Comment by bimbifan** [comment]
thanks!!!
