### ISSUE TITLE
Personal best

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#144]
### Describe your bug here.

For some reason my personal best is not saved :(

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using source code

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/e5e8ae87-0a59-43b0-829f-fdd5c0127f7d)

can you check the following:

If the amount of safe frames you have is less than 10 (Values higher than that will stop saving)
If the combo multiplier limit is less than 10 (Values higher than that will stop saving)
If you accessed the Gameplay Changers substate and changed either Botplay or Practice mode (changing either will stop saving even if you change them back)

**Comment by JordanSantiagoYT** [comment]
Safe frames are located at Options -> Gameplay
Combo Multiplier limit is located at Options -> Gameplay

**Comment by bimbifan** [comment]
weird, but when I redownloaded the game everything was stable for me

**Comment by Stefan2008Git** [comment]
> ![image](https://private-user-images.githubusercontent.com/61796448/294021983-e5e8ae87-0a59-43b0-829f-fdd5c0127f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjU5NjEsIm5iZiI6MTcwNDc2NTY2MSwicGF0aCI6Ii82MTc5NjQ0OC8yOTQwMjE5ODMtZTVlOGFlODctMGE1OS00M2IwLTgyOWYtZmRkNWMwMTI3ZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAyMDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YWRjMjU4MDIyNzU1MDA4OGU0OTkwYmQ1YjczYWNkZmE5MTM3OGI4ZmMyZGYxZWFmZGI5YWYyOGM5MDM0YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJTiXm7mlNMLsQXVuOfPMlICR1LtLOL9-MVGmKzAYfM)
> 
> can you check the following:
> 
> If the amount of safe frames you have is less than 10 (Values higher than that will stop saving) If the combo multiplier limit is less than 10 (Values higher than that will stop saving) If you accessed the Gameplay Changers substate and changed either Botplay or Practice mode (changing either will stop saving even if you change them back)

The fuck? Did you even tested without botplay or practice to see if you had that bug?

**Comment by moxie-coder** [comment]
should be fixed in latest ver
