### ISSUE TITLE
Event counter just like note counter

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#145]
### What feature do you want to get added on the **base** engine?

Basically the same as how much note(s) it has, but what about how much event(s) it does have?

(apply to the chart editor)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ Support.

**Comment by NAEL2XD** [comment]
edited because i misclick "optimization" instead of "stage editor and 6k+ support"

**Comment by JordanSantiagoYT** [comment]
No

**Comment by NAEL2XD** [comment]
:( ok
