### ISSUE TITLE
Chart editor memory leak?

### ISSUE THREAD

**Issue by fel0429** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#146]
### Describe your bug here.

it doesnt crash for me but, when im charting sometimes it just lags so bad my fps drops to 5 or 4 and i can barely do anything so i have to open the game again

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
here's a few tips:

disable the charting grid, it reduces memory leaks for some reason
if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon

**Comment by JordanSantiagoYT** [comment]
> > here's a few tips:
> > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> 
> Here is an my tip:
> 
> Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization

If you're gonna be rude then YOU optimize the code. I don't understand optimization that well

**Comment by Stefan2008Git** [comment]
> > > here's a few tips:
> > > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> > 
> > 
> > Here is an my tip:
> > Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization
> 
> If you're gonna be rude then YOU optimize the code. I don't understand optimization that well

I am just fine. My life is just making me really fucking sick because everyone in the real life highschool abusing me and i can't handle that shit

**Comment by JordanSantiagoYT** [comment]
> > > > here's a few tips:
> > > > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> > > 
> > > 
> > > Here is an my tip:
> > > Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization
> > 
> > 
> > If you're gonna be rude then YOU optimize the code. I don't understand optimization that well
> 
> I am just fine. My life is just making me really fucking sick because everyone in the real life highschool abusing me and i can't handle that shit

Oh.

well i think you should take a break from social media for a bit, that usually helps a bit with mental health issues

**Comment by Stefan2008Git** [comment]
> > > > > here's a few tips:
> > > > > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> > > > 
> > > > 
> > > > Here is an my tip:
> > > > Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization
> > > 
> > > 
> > > If you're gonna be rude then YOU optimize the code. I don't understand optimization that well
> > 
> > 
> > I am just fine. My life is just making me really fucking sick because everyone in the real life highschool abusing me and i can't handle that shit
> 
> Oh.
> 
> well i think you should take a break from social media for a bit, that usually helps a bit with mental health issues

And i am discounting my engine too, because I can't fucking use my laptop anymore. I will throw my laptop to trash

**Comment by moxie-coder** [comment]
> > > > > > here's a few tips:
> > > > > > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> > > > > 
> > > > > 
> > > > > Here is an my tip:
> > > > > Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization
> > > > 
> > > > 
> > > > If you're gonna be rude then YOU optimize the code. I don't understand optimization that well
> > > 
> > > 
> > > I am just fine. My life is just making me really fucking sick because everyone in the real life highschool abusing me and i can't handle that shit
> > 
> > 
> > Oh.
> > well i think you should take a break from social media for a bit, that usually helps a bit with mental health issues
> 
> And i am discounting my engine too, because I can't fucking use my laptop anymore. I will throw my laptop to trash

jeez, why can't I take over the project then?

**Comment by Stefan2008Git** [comment]
> > > > > here's a few tips:
> > > > > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> > > > 
> > > > 
> > > > Here is an my tip:
> > > > Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization
> > > 
> > > 
> > > If you're gonna be rude then YOU optimize the code. I don't understand optimization that well
> > 
> > 
> > I am just fine. My life is just making me really fucking sick because everyone in the real life highschool abusing me and i can't handle that shit
> 
> Oh.
> 
> well i think you should take a break from social media for a bit, that usually helps a bit with mental health issues

And i am discounting my engine too, because I can't fucking use my laptop anymore. I will throw my laptop to trash

> > > > > > > here's a few tips:
> > > > > > > disable the charting grid, it reduces memory leaks for some reason if you're charting, undos will be saved after every change up to the last 100. i might add an option to disable undos soon
> > > > > > 
> > > > > > 
> > > > > > Here is an my tip:
> > > > > > Optimize the entire fucking source code like PE 0.7+. It helps to my shitty laptop. Your modified Psych fork crashed my game because engine is not an that "optimized". I don't understand what is that optimization
> > > > > 
> > > > > 
> > > > > If you're gonna be rude then YOU optimize the code. I don't understand optimization that well
> > > > 
> > > > 
> > > > I am just fine. My life is just making me really fucking sick because everyone in the real life highschool abusing me and i can't handle that shit
> > > 
> > > 
> > > Oh.
> > > well i think you should take a break from social media for a bit, that usually helps a bit with mental health issues
> > 
> > 
> > And i am discounting my engine too, because I can't fucking use my laptop anymore. I will throw my laptop to trash
> 
> jeez, why can't I take over the project then?

No, no, no. You can't, because i am not allowing that. Thank you for supporting my engine after 10 months, but this is an day that Stefsn is officially discounted him's engine because he can't use anymore an laptop, so have an great day

**Comment by StinkTheStinker** [comment]
is your laptop corrupted or somethin?

**Comment by Stefan2008Git** [comment]
> is your laptop corrupted or somethin?

I fixed that shit already
https://cdn.discordapp.com/attachments/1089705065658454026/1194477548340523189/rn_image_picker_lib_temp_93df691c-a44d-45b8-8acd-723b1157fa87.jpg?ex=65b07ee7&is=659e09e7&hm=3860cec6b937613332a84510a935ec12c3a37303087c800577ef1005181cc1b2&

**Comment by Stefan2008Git** [comment]
> > is your laptop corrupted or somethin?
> 
> I fixed that shit already https://cdn.discordapp.com/attachments/1089705065658454026/1194477548340523189/rn_image_picker_lib_temp_93df691c-a44d-45b8-8acd-723b1157fa87.jpg?ex=65b07ee7&is=659e09e7&hm=3860cec6b937613332a84510a935ec12c3a37303087c800577ef1005181cc1b2&

![slika](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/126715034/f787184f-513c-4537-86da-4954da1aa01d)
@JordanSantiagoYT Nevermind, everything is fine now

**Comment by moxie-coder** [comment]
honestly, idk why the memory leaks happen, they happen in regular psych, but idk why
