### ISSUE TITLE
recording idea or something like that

### ISSUE THREAD

**Issue by BuatedsFNF** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#147]
### What feature do you want to get added on the **base** engine?

idk if  this is stupid or would be impossible or not, but what if **you could record a replay as mp4 with no lag?**
you could use ffmpeg for this and make it render in another window like zenith or something (if that's possible)

this would probably be cool, since you wouldn't have to wait for a song to finish at 0.1x speed like watching paint dry
tell me if any updates on this

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by NAEL2XD** [comment]
obs:

**Comment by StinkTheStinker** [comment]
[obs](https://obsproject.com)

**Comment by moxie-coder** [comment]
> ### What feature do you want to get added on the **base** engine?
> idk if this is stupid or would be impossible or not, but what if **you could record a replay as mp4 with no lag?** you could use ffmpeg for this and make it render in another window like zenith or something (if that's possible)
> 
> this would probably be cool, since you wouldn't have to wait for a song to finish at 0.1x speed like watching paint dry tell me if any updates on this
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

obs exists retard

**Comment by JordanSantiagoYT** [comment]
GitHub didn't allow me to be more specific, i hid this comment because it seemed rude.

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> idk if this is stupid or would be impossible or not, but what if **you could record a replay as mp4 with no lag?** you could use ffmpeg for this and make it render in another window like zenith or something (if that's possible)
> 
> this would probably be cool, since you wouldn't have to wait for a song to finish at 0.1x speed like watching paint dry tell me if any updates on this
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

That's actually impossible to implement in smth like FNF, i know there's Black MIDI stuff but FNF.. you can't do smth like that

**Comment by BuatedsFNF** [comment]
oh ok thanks though

**Comment by BuatedsFNF** [comment]
also moxie you didn't have to call me a fuckin retard for that
what i meant by that is it could do it faster instead of having to wait 0.05 seconds for a frame to go by

**Comment by moxie-coder** [comment]
> also moxie you didn't have to call me a fuckin retard for that what i meant by that is it could do it faster instead of having to wait 0.05 seconds for a frame to go by

it's a dumbass question

**Comment by JordanSantiagoYT** [comment]
A similar feature to this has been implemented by HRK_EXEX, so this issue will be opened back up for questioning. https://www.youtube.com/watch?v=5k6PIQUAITc&t=0s

**Comment by moxie-coder** [comment]
interesting

**Comment by JordanSantiagoYT** [comment]
Added in https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/a61415ce11370b39af263ea811272aae5efc6caf
