### ISSUE TITLE
Chars & BG ON

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#148]
### Describe your bug here.

Let's talk a little about bugs (or not). When I have Showcase mode enabled but Chars & BG disabled, bugs occur: long notes go back behind the notes (this does not happen to the opponent), in the kade engine hud the bar now has an unnecessary extra black piece(this bug happens anyway), and rendered notes are no longer reset.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using source code

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
i don't get it, send a video or screenshot of what you are talking about please

**Comment by JordanSantiagoYT** [comment]
1. this is intentional because only Sustains are counted
2. Fixed in latest commit
3. The rendered notes won't be counted or reset if Show Notes is turned off.

**Comment by bimbifan** [comment]
> 3\. The rendered notes won't be counted or reset if Show Notes is turned off.

If show notes is disabled on a rendered note, opp nps and nps will not be displayed.

**Comment by JordanSantiagoYT** [comment]
> > 3. The rendered notes won't be counted or reset if Show Notes is turned off.
> 
> If show notes is disabled on a rendered note, opp nps and nps will not be displayed.

that's because it's intentional. the botplay text is invisible if showcase mode is on

**Comment by bimbifan** [comment]
In general, I mean that if you turn on the showcase mode, then nothing will be visible at all. And when I just turned off Chars&BG, the note rendering became just a counter.

**Comment by JordanSantiagoYT** [comment]
Bug has been identified, the game doesn't kill notes properly by removing them from the 'notes' and 'sustainNotes' FlxTypedGroups

**Comment by moxie-coder** [comment]
> Bug has been identified, the game doesn't kill notes properly by removing them from the 'notes' and 'sustainNotes' FlxTypedGroups

because well, when the members are null, it returns null, and it returns the removed object
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/e6f5bc39-b763-4a0c-8198-6727b7959a31)
it even states in the docs it returns the "removed object"

**Comment by moxie-coder** [comment]
so it weirdly doesn't entirely remove it unless you splice it

**Comment by moxie-coder** [comment]
okay wait nvm, forget everything I said, seems like it's working fine on my end, so @bimbifan I would suggest using the latest version (from actions) since I don't see it happening there, aside from sustain notes going farther out then they should, but it's just a visual bug as far as I know so, shouldn't be too much of an issue
