### ISSUE TITLE
There is a crash when enter any song

### ISSUE THREAD

**Issue by Kokosaurio** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#149]
### Describe your problem here.

_**So. I downloaded the new JSengine vercion and when i go to some song from D&B Nullfield or any song. just
crashed**_
![Captura de pantalla 2024-01-05 213151](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/155786775/cd992b3c-05ef-490c-8b50-4c776bf5bf0a)
**If someone knows why this happend it will appreciate much for the help**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
are you using the box funkin hud? don't use that right now

**Comment by Kokosaurio** [comment]
> are you using the box funkin hud? don't use that right now

yeah. i was using that hud lmao

**Comment by Kokosaurio** [comment]
> > are you using the box funkin hud? don't use that right now
> 
> yeah. i was using that hud lmao

and can i ask. why that happends? just for curiosity

**Comment by JordanSantiagoYT** [comment]
idk it tries making a new timetxt without destroying it first i guess

**Comment by Kokosaurio** [comment]
o

**Comment by Stefan2008Git** [comment]
> idk it tries making a new timetxt without destroying it first i guess

Dude, you should make the different functions for HUD
