### ISSUE TITLE
what  is troll mode and what does it do

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#151]
### What is your question?

tried searching it up but i dindt really find anything about it , what is troll mode supposed to do?

**Comment by NAEL2XD** [comment]
Basically what I know is when the song ends it replays the song and goes to a faster speed, specifically 0.05x per replay

That's all I know

**Comment by JordanSantiagoYT** [comment]
once the song ends, the song loops from the beginning and goes faster until either you cant handle it anymore or it crashes

**Comment by Amgsdfyhadfgybi** [comment]
ohhhhhh
