### ISSUE TITLE
Engine Crashed when i open the Hide HUD option

### ISSUE THREAD

**Issue by Bottlesensce** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#153]
### Describe your bug here.

Look at the Title

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (Line 2146)
flixel/FlxGame.hx (Line 642)
flixel/FlxGame.hx (Line 729)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 550)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
What version of JSE are you using?

**Comment by moxie-coder** [comment]
@JordanSantiagoYT can I be added to the repo? I think it would be a good idea to have additional help

**Comment by Bottlesensce** [comment]
> What version of JSE are you using?

1.18.0

**Comment by JordanSantiagoYT** [comment]
Yeah just realized you reported it as android. not helping with issues for Android, because it's no longer a priority.

**Comment by JordanSantiagoYT** [comment]
> @JordanSantiagoYT can I be added to the repo? I think it would be a good idea to have additional help

soon™️

**Comment by moxie-coder** [comment]
@Bottlesensce try it now on the latest commit, once actions are finished
