### ISSUE TITLE
Mobile switching controls are not working

### ISSUE THREAD

**Issue by LuizFelipePlay** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#154]
### Describe your bug here.

well on android, he have a option ro Switch the control, but it's not working,só fix that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by LuizFelipePlay** [comment]
About the system, i use android

**Comment by JordanSantiagoYT** [comment]
Android is not a priority for me.

**Comment by moxie-coder** [comment]
@LuizFelipePlay can you elaborate further?

**Comment by LuizFelipePlay** [comment]
@moxie-coder Well, when I change controls I can't, the buttons don't work, can you fix the buttons? I really wanted to play in hitbox and more.

**Comment by LuizFelipePlay** [comment]
@moxie-coder you are a coder in js engine for android build? If yes, i cant told you all the bugs on yt

**Comment by moxie-coder** [comment]
> @moxie-coder Well, when I change controls I can't, the buttons don't work, can you fix the buttons? I really wanted to play in hitbox and more.

that doesn't say a lot, and I don't have android

**Comment by moxie-coder** [comment]
can you atleast record an video?

**Comment by LuizFelipePlay** [comment]
@moxie-coder whats you yt? Give me your yt and i mention you

**Comment by LuizFelipePlay** [comment]
Uploading mobizen_20240122_002751.mp4…

@moxie-coder thats the bug

**Comment by moxie-coder** [comment]
> Uploading mobizen_20240122_002751.mp4…
> 
> @moxie-coder thats the bug

you…didn’t upload the video, you have to wait for it to finish uploading before sending

**Comment by LuizFelipePlay** [comment]
@moxie-coder well, you need to do a 1.18.0 hotfix, i will send the vídeos on mediafire

**Comment by LuizFelipePlay** [comment]
But if i can send on github i send here

**Comment by LuizFelipePlay** [comment]
![Screenshot_20240122-140818](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/122581009/b8502403-869f-442a-9b8b-dd514a2895e3)

**Comment by LuizFelipePlay** [comment]
The left and right arrows button dont work @moxie-coder

**Comment by moxie-coder** [comment]
oh okay

**Comment by JordanSantiagoYT** [comment]
> The left and right arrows button dont work @moxie-coder

they do work, the game just has a weird offset when registering them

**Comment by LuizFelipePlay** [comment]
@JordanSantiagoYT whats their offsets? Can you fix this thing

**Comment by LuizFelipePlay** [comment]
Wait what the hell, pressing the Dpad buttons Switch

**Comment by LuizFelipePlay** [comment]
Oh no, it doenst work anymore

**Comment by LuizFelipePlay** [comment]
I love the js engine, the problem is that the port for Android is rubbish, you can't change the controls, the optimization is horrible

**Comment by LuizFelipePlay** [comment]
If you fixed these bugs, more people would use the js engine, but no, with each update it only adds more bugs for the simplest things, which are changing control and optimization
