### ISSUE TITLE
Making a song load faster.

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#155]
### What is your question?

How do I load a song in seconds? My song are loading in a minute or more.

**Comment by JordanSantiagoYT** [comment]
Cannot help with that.

**Comment by StinkTheStinker** [comment]
get better specs

**Comment by StinkTheStinker** [comment]
thats all i know

**Comment by PatoFlamejanteTV** [comment]
IDK try to optimize the chart or try an JS fork

**Comment by JordanSantiagoYT** [comment]
> IDK try to optimize the chart or try an JS fork

this was made before the chart loading rewrite, which loads songs MUCH faster

LOL
