### ISSUE TITLE
simplified rate counter

### ISSUE THREAD

**Issue by TheTrueAccount** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#156]
### What feature do you want to get added on the **base** engine?

Add an option under the "rating counter" option that makes the normal one turn into the one when no bg+showcaste mode one

this also would be useful if you are making showcaste with notes on bc you can actually see the video speedup 

The first image is the old one that is currently in the game

The second one would the new simplified one that is visually a lot more better when using botplay (since the ratings stays at 0 when botplay is on, so they are useless)

![old one](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/144788620/fca59e2f-25dc-4f1e-98c6-04fe5fdf04a5)

![new one](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/144788620/aa1ebbd2-1049-4b24-9149-9e207749b6a3)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
Added in the latest commit.
