### ISSUE TITLE
fnf crashes when load random song 

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#157]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/156928927/83aa93c9-f534-4cb5-aa16-f7d0285aa90e)
when I wanted to make one song, I tested it and the game gave me the following error, I tried to download a clean version without mods, but the problem did not go away, now no song will start :(

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (Line 4193)
PlayState.hx (Line 3951)
PlayState.hx (Line 1642)
flixel/FlxGame.hx (Line 642)
flixel/FlxGame.hx (Line 729)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, only songs

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by moxie-coder** [comment]
firstly, that will be fixed in an upcoming commit, secondly, don’t use dadbattle spotlight outside week 1

**Comment by dimafut** [comment]
but how to not use it? can you tell me please

**Comment by moxie-coder** [comment]
> but how to not use it? can you tell me please

figure that out, I’m not teaching a retard how to code, and you gotta learn somehow
