### ISSUE TITLE
shattering chart

### ISSUE THREAD

**Issue by TankmanUtah** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#158]
### What feature do you want to get added on the **base** engine?

is the shattering chart (sonorous 2) private? or has it not been added yet?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
this just makes no sense

**Comment by NAEL2XD** [comment]
> ### What feature do you want to get added on the **base** engine?
> 
> is the shattering chart (sonorous 2) private? or has it not been added yet?
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> Proper credit that was forgotten

You know there are 2 repositories
One being this repo as a fork and one for mods

Here
https://github.com/JordanSantiagoYT/Mods-for-JS-Engine

**Comment by JordanSantiagoYT** [comment]
what was the point of making this issue exactly? The chart was made by miksel then given to me because I agreed to help him record a showcase. In other words, the chart IS private.
