### ISSUE TITLE
Engine crashes after changing the opponent in the chart editor after pressing enter.

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#159]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

read title

### Command Prompt/Terminal logs (if existing)

```bash
https://cdn.discordapp.com/attachments/979114840037683200/1198373489422381206/2024-01-20_22-06-44.png?ex=65beab48&is=65ac3648&hm=87f3af80b1bb7f2a76c2a253f17cd89777e039033c92b4898ce2945751286916&

copy and paste it on the url
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk if it's considered as an editing but i only added a song on the bulid. it has nothing to do with the song but with the character

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by moxie-coder** [comment]
can you provide logs please?

**Comment by TommykairaXVI** [comment]
> can you provide logs please?

it's on the link

**Comment by moxie-coder** [comment]
update to the latest version
