### ISSUE TITLE
Crashes when you change playback rate after skipping time

### ISSUE THREAD

**Issue by QuandalePr1ngle** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#16]
### Describe your bug here.

After pressing escape it crashes

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/133515732/dc46180a-3fc2-4a9c-920e-1159ad37d4fa

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
Probably double ghost option is turned on

**Comment by QuandalePr1ngle** [comment]
> Probably double ghost option is turned on

Well yes but nah, it doenst crash on songs like philly, thorns (deafult songs in assest folder)
but in other songs that located in mods it crashes

**Comment by QuandalePr1ngle** [comment]
> already know this issue, me and hoovy are working on a fix currently

cool
