### ISSUE TITLE
Live cam movement

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#161]
### What feature do you want to get added on the **base** engine?

Instead of the cam updating after 4 beats, the cam updates live when the character moves (while its idle). Like the Dave and Bambi Camera movement.

_Note: I felt like using the "A good idea" option since it makes it look like actual cam movement, like in tv shows._

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by StinkTheStinker** [comment]
Also, after the video on the 7 event, it doesn't close the game

**Comment by moxie-coder** [comment]
> Also, after the video on the 7 event, it doesn't close the game

it’s not supposed to? wdym

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/df913402-fa1e-44b1-af9b-c4ddd5c03dea)

**Comment by StinkTheStinker** [comment]
wait

**Comment by StinkTheStinker** [comment]
i downloaded the full latest version, not the commit

**Comment by StinkTheStinker** [comment]
i am so fucking stupid

**Comment by StinkTheStinker** [comment]
ok hold up
the video works
it just doesnt close when it ends

**Comment by moxie-coder** [comment]
it should now
