### ISSUE TITLE
Search songs feature

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#162]
### What feature do you want to get added on the **base** engine?

Yes i know that some dude actually coded a search feature in psych engine, but

# I'm so tired of finding the songs i wanna choose
like i have 200+ songs to choose and none is the song that i wanna choose!

it would've been better if there was a search songs feature, because i know the song's name but there are lots of songs that i don't want to.

Here's what it looks like 
![Capture d'écran 2024-01-25 175007](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/108278470/d03eba0e-9b4e-4603-ae13-99d6f0f450be)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by StinkTheStinker** [comment]
that does sound like a good good feature tbh. might take long to code if js agrees

**Comment by JordanSantiagoYT** [comment]
if you have the link to the source code for the engine that has this, link it here and i might add this in

**Comment by moxie-coder** [comment]
> if you have the link to the source code for the engine that has this, link it here and i might add this in

I already know

**Comment by NAEL2XD** [comment]
> if you have the link to the source code for the engine that has this, link it here and i might add this in

Betopia created the search bar
https://github.com/MoonlightCatalyst/Moons-Modded-Psych-Source/blob/9028774629912c45c19aeecdbc9eb9ac43cc9ab3/source/CreditsState.hx
['Betopia',		'nothing',		'Freeplay Search bar creator',								'https://www.youtube.com/channel/UCfjyz9xRhZiRbLMteQloVeg',	'FFFFFF'],

**Comment by NAEL2XD** [comment]
fuck i meant to use freeplaystate link not creditsstate link but here it is

**Comment by NAEL2XD** [comment]
@JordanSantiagoYT

**Comment by JordanSantiagoYT** [comment]
ok

**Comment by JordanSantiagoYT** [comment]
I DID IT

**Comment by JordanSantiagoYT** [comment]
Added in latest commit
