### ISSUE TITLE
psych engine 0.7.1 note color system

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#163]
### What feature do you want to get added on the **base** engine?

i think this would probably be copying but the current color system is really stupid , and those 2 features might be good as an addition

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by StinkTheStinker** [comment]
some notes like the 3d notes from dnb will look weird if it get added

**Comment by JordanSantiagoYT** [comment]
No. this is just too difficult to add.
