### ISSUE TITLE
custom music options | might take a bit though, idk, im dumb

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#164]
### What feature do you want to get added on the **base** engine?

title is explainable. also, the ones im talking about is the "pause and menu" songs. if you dont want them, for example: you want to remove the mashup menu music, you can just remove that

Note: i picked the "Better LUA mod support idea" because some people don't know how to do source coding or just lazy (no offence to that, im lazy to)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Better LUA mod support idea

**Comment by moxie-coder** [comment]
it’s already possible to change the pause songs wtf do you mean by this?

**Comment by StinkTheStinker** [comment]
im saying like, more pause songs (and menu)

**Comment by NAEL2XD** [comment]
> im saying like, more pause songs (and menu)

more pause songs = more size

**Comment by moxie-coder** [comment]
> > im saying like, more pause songs (and menu)
> 
> more pause songs = more size

basically yeah, but it’s already possible to do anyways just by editing the source code, but I will add lua support perhaps soon

**Comment by StinkTheStinker** [comment]
n i c e
