### ISSUE TITLE
watermark text or something

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#165]
### What feature do you want to get added on the **base** engine?

basicly like this:
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/c682aef5-f02b-414d-babd-3f9b40e216da) 
the option is in the data tab in chart editor
also, the reason why i did this is because i tried doing it in lua, and it wouldnt work. even if its in the song data
idk what credit to choose

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
the Song Credit thing was originally planned to just be a watermark when I initially added it, but then I changed it to show only in the song intro because people liked that more
