### ISSUE TITLE
Mac build doesnt work

### ISSUE THREAD

**Issue by CleanerCosine14** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#166]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

When i unzipped the .app file It doesnt let me run it.
It appears the file named "JSEngine" on Contents/MacOS is corrupted and cant run the application.
Now it is requiered to run the application because it is a "Unix Executable File" Which runs the Engine.
So Jordan Santiago Please Fix this so i can create a mod.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by CleanerCosine14** [comment]
Uploading 0127.mp4…

**Comment by CleanerCosine14** [comment]
didnt mean to close the issue

**Comment by CleanerCosine14** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/103971101/469c284a-fa15-41da-9417-0fb72134d0c6

**Comment by moxie-coder** [comment]
we don’t have a Mac, but you should try reinstalling

**Comment by JordanSantiagoYT** [comment]
Don't have a macOS device, so this is unfixable

**Comment by CleanerCosine14** [comment]
Oh okay, so how do I compile your engine then? I am trying to do that for so long and I can’t seem to get the library hmm installed

**Comment by CleanerCosine14** [comment]
Or do I have the wrong version installed?

**Comment by JordanSantiagoYT** [comment]
> 0127.mp4

Hold up, I just checked the Psych Engine Mac action builds and I think they have the same issue

**Comment by CleanerCosine14** [comment]
I can open psych engine with no problem, idk how the compiler of the MacOS version of the engine even bothered checking this

**Comment by CleanerCosine14** [comment]
So, do you mind sending your Haxe library? so I can compile your engine.

**Comment by JordanSantiagoYT** [comment]
> So, do you mind sending your Haxe library? so I can compile your engine.

This was from the linux workflow but i think it should work for Mac

          haxelib install hxcpp 4.2.1
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.1
          haxelib install flixel 5.2.2
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-addons 3.0.2
          haxelib install flixel-ui 2.5.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec 2.6.1
          haxelib install hscript
          haxelib set openfl 9.2.1
          haxelib set flixel-addons 3.0.2
          haxelib set flixel-ui 2.5.0
          haxelib install hxcpp-debug-server
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

**Comment by CleanerCosine14** [comment]
Thanks. Your the goat and your engine will always be the best

**Comment by CleanerCosine14** [comment]
I will let you know if it successfully compiled your engine
