### ISSUE TITLE
I cant select hitbox on mobile

### ISSUE THREAD

**Issue by LuizFelipePlay** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#167]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

The two buttons to change my control on android is not working, can you fix that please? (The build target is Android)

### Command Prompt/Terminal logs (if existing)

```bash
Doenst exist
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by CleanerCosine14** [comment]
just spam until it gets there thats what i had to do

**Comment by LuizFelipePlay** [comment]
Wdym?

**Comment by LuizFelipePlay** [comment]
So well if you guys not fixing that, so just leave the hitbox

**Comment by CleanerCosine14** [comment]
what i mean is click or tap everywhere and spamming it until it changes what ever mobile control you want. its currently bugged but doing what i told actually works

**Comment by LuizFelipePlay** [comment]
I dont wanna hurt my fingers spaming bruh

**Comment by LuizFelipePlay** [comment]
YES FINNALY, after almost breaking my screen i got hitbox

**Comment by CleanerCosine14** [comment]
told ya

**Comment by CleanerCosine14** [comment]
now close this issue

**Comment by moxie-coder** [comment]
don’t make duplicates
