### ISSUE TITLE
shader bug

### ISSUE THREAD

**Issue by RedcappedmelonYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#168]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

i was playing the end of abuse gorefield mod until there was no code generated, even though it's fine

### Command Prompt/Terminal logs (if existing)

```bash
[openfl.display.Shader] ERROR: Error compiling fragment shader
ERROR: 0:62: '=' :  cannot convert from 'const int' to 'float'
ERROR: 1 compilation errors.  No code generated.



		#version 100
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't know

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by moxie-coder** [comment]
incompatible shader, you'll have to modify the shader a bit for it to work

**Comment by StinkTheStinker** [comment]
its true. but if you dont want to do that shit, just remove it and forget it. unless if you have a friend that can does fnf shader coding
