### ISSUE TITLE
IMPORTANT: JS Engine Android Announcement

### ISSUE THREAD

**Issue by JordanSantiagoYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#169]
hey. i have an important announcement to make regarding JS Engine on android.

after considering it a few times now, i’ve decided that im discontinuing JS Engine for android. there’s a few reasons why im doing this.

1. The engine’s performance sucks if you have a low-end Android device.
2. It uses 0.6.3, which is a difficult version to run on Android without performance issues.
3. The engine in its current state is buggy and it’s a bad engine for Android users to use in general.

if you want a better engine/alternative, try [Stefan2008_Official](https://www.youtube.com/channel/UC9Nwf21GbaEm_h0Ka9gxZjQ)‘s engine, [SB Engine](https://gamebanana.com/tools/10824). it’s a much better alternative (for Android users) and has optimization that makes it bearable if not better to run on Android.

i might consider bringing it back in the future but im just not ready to do it right now. if someone does want to bring it back then i’ll still leave the Android code in, and they can improve the engine’s performance to a point where it’s actually possible to run on Android w/ barely any lag.

**Comment by moxie-coder** [comment]
should I remove the android actions then?

**Comment by JordanSantiagoYT** [comment]
I mean that's completely up to you

**Comment by Stefan2008Git** [comment]
Nah, my engine is nothing :| Jordan. No one can help me or send any pull request because i can't everything alone to code. You know me, right?

**Comment by RedcappedmelonYT** [comment]
how the hell should i use it for spammy songs??

**Comment by Stefan2008Git** [comment]
> how the hell should i use it for spammy songs??

💀 Blud loves shitty asshole content that deserves to do not exist anymore

**Comment by NAEL2XD** [comment]
> how the hell should i use it for spammy songs??

use your pc :)

**Comment by Stefan2008Git** [comment]
> > how the hell should i use it for spammy songs??
> 
> use your pc :)

Simple, instead to spend your time on Android phone

**Comment by JordanSantiagoYT** [comment]
It's been 5 months since this issue was made, I believe people shouldve gotten the message by now so I am unpinning this issue.

**Comment by Stefan2008Git** [comment]
Okay Jordan

**Comment by trademarkman** [comment]
i wonder if this is real 😭
