### ISSUE TITLE
"Multi-Copy Section" feature for chart editor

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#17]
### What feature do you want to get added on the **base** engine?

this feature allows you to copy multiple sections, so you dont have to copy it one by one ig (and its for the same section that has same notes to copy like seraphic or something)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
so something like this? ![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/8bc93bac-9749-4f9c-8fce-6498b3c5ed05)

**Comment by JordanSantiagoYT** [comment]
basically what it does is copy the current section's notes, pastes them into the next section, goes to the next section, copies the notes there and repeats until it reaches section (curSection + value)

**Comment by Mushymushroom12** [comment]
yeah but you could paste it anywhere besides copy to the next section
i guess..
