### ISSUE TITLE
GF section (and gf sing notes) don't work

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#170]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

title is self explainable
video of whats going on:

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/225ba40d-9162-4741-92fe-ec7b15a3da83

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just some modding with lua, thats it

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
WHY IS IT LAGGY. HOLD ON

**Comment by StinkTheStinker** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/41de3bbb-336e-48cc-84f4-6f110470da54

**Comment by JordanSantiagoYT** [comment]
which version of JSE is this?

**Comment by StinkTheStinker** [comment]
1.18
[Commit](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/2a6e3336c9933dbc64832290e886d9b070f73454)

**Comment by StinkTheStinker** [comment]
the reason why i didnt update to the other commits after that is because i wanted the video to happen after the 7 event

**Comment by JordanSantiagoYT** [comment]
yeah does nt occur

also if its a gf section why use gf sing notes

**Comment by moxie-coder** [comment]
> the reason why i didnt update to the other commits after that is because i wanted the video to close the game after the 7 event

I already fixed that

**Comment by JordanSantiagoYT** [comment]
> > the reason why i didnt update to the other commits after that is because i wanted the video to close the game after the 7 event
> 
> I already fixed that

yeah i think hes using the commit where thats fixed

**Comment by StinkTheStinker** [comment]
yea, i am

**Comment by StinkTheStinker** [comment]
> also if its a gf section why use gf sing notes

its because that i was using the gf section before the gf notes, but didnt do anything, then i used both, still did not work

**Comment by StinkTheStinker** [comment]
also js, i might know why the "y-value" bug is happening when a dialogue happens

it's from the floating opponent because of lua causing the weird ass bug

**Comment by StinkTheStinker** [comment]
like, when i removed that float script. the bug disapeared. but, when i added it back, bug comes back

**Comment by StinkTheStinker** [comment]
only occurs in story mode though

**Comment by StinkTheStinker** [comment]
is this forgotten?

**Comment by StinkTheStinker** [comment]
i just tested the problem on a new and unmodded version, problem still occuring

**Comment by NAEL2XD** [comment]
should be closed for inactivity

**Comment by Joacx21** [comment]
Its happening again, it doesn't work for me neither
