### ISSUE TITLE
Making JS Engine work with latest libraries

### ISSUE THREAD

**Issue by CaptainBaldi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#171]
### What feature do you want to get added on the **base** engine?

JS Engine uses pretty outdated libraries for compiling the engine. This can cause confusion and difficulty when trying to work with JS Engine and other engines that require latest libraries (such as Psych Engine)

I'd imagine you wouldn't be up to doing this yourself, is it possible you would accept pull requests for it? I would like to at least try and get it working, and maybe make more improvements to the engine along the way, because, no matter how you put it, this engine does have a lot of issues, but they can be fixed, or at least, minimalized.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
if you really feel like it, go ahead.
the only really important issues you'd need to figure out are:
Making the playback rate still work with character sprites
Keeping Rainbow FPS
Keeping Accurate RAM counter

**Comment by CaptainBaldi** [comment]
> if you really feel like it, go ahead. the only really important issues you'd need to figure out are: Making the playback rate still work with character sprites Keeping Rainbow FPS Keeping Accurate RAM counter

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/86160807/5e0d215e-d0f5-44c0-826e-c1b09e8038f1)

The RAM counter already seems to be inaccurate, but I'll take a look at the other things you mentioned

**Comment by JordanSantiagoYT** [comment]
> > if you really feel like it, go ahead. the only really important issues you'd need to figure out are: Making the playback rate still work with character sprites Keeping Rainbow FPS Keeping Accurate RAM counter
> 
> ![image](https://private-user-images.githubusercontent.com/86160807/302007863-5e0d215e-d0f5-44c0-826e-c1b09e8038f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjkwMjcsIm5iZiI6MTcwNjkyODcyNywicGF0aCI6Ii84NjE2MDgwNy8zMDIwMDc4NjMtNWUwZDIxNWUtZDBmNS00NGMwLTgyNmUtYzFiMDllODAzOGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAyNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTk3NDgwMDhhM2I4ZjFjNTA1OTM0NTg5M2UxNGQ4NDQ2NzcxZmM2YmJmOTg1NDJhZDk5ODgwOGI2MzQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TKIr1EEAKx3DH0D6G1XkbH3J49hrSc0dxv6FfwoJBfM)
> 
> The RAM counter already seems to be inaccurate, but I'll take a look at the other things you mentioned

well by accurate i do mean that it doesn't just cap at 2GB, and it kinda shows how much ram it's actually using

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/7b5d1238-6c82-41f6-bb25-926efede9e11)

there

**Comment by StinkTheStinker** [comment]
how in the hell did i misspell usage wrong

**Comment by JordanSantiagoYT** [comment]
> ![image](https://private-user-images.githubusercontent.com/145304742/302009186-7b5d1238-6c82-41f6-bb25-926efede9e11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjY1NDQsIm5iZiI6MTcwNjk2NjI0NCwicGF0aCI6Ii8xNDUzMDQ3NDIvMzAyMDA5MTg2LTdiNWQxMjM4LTZjODItNDFmNi1iYjI1LTkyNmVmZWRlOWUxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMzE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzI5NzdkYWZiZjhjMWIyN2NjZTNmYjIyMjdiODQ0OGU1MjY5ZjhiODkwNjVlZTRjYmMyNDlhZTE5OTgyMGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B07zP_ugD3X2F-jdXXOV6zYzyUi8R8MaZkbDzz0zmdI)
> 
> there

ram usate

**Comment by StinkTheStinker** [comment]
:sob:

**Comment by CaptainBaldi** [comment]
got my wish, i can close this now !!
