### ISSUE TITLE
uhhh, this is strange but like, something REALY strange is ocurring with me

### ISSUE THREAD

**Issue by DustEpicKaiSans** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#174]
### What is your question?

lol, well, like, some not common things is happening with me, like one time i got jumpscared with freddy fazbear... and the game just closed.. i dont think this is normal, and i was doing a chart, and i didnt put ANYTHING that would do that with me even if i pressed a button, like 7, but i was in the charting mode already, and after some time charting it appeard this 
![Desktop Screenshot 2024 02 03 - 23 59 00 71](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150727511/1a0a727f-8ee4-4433-a974-6e3fbca44da6)
uhh, like, wtf? it appeard RAMDOMLY, i was normally charting, is this normal? or something thats just luck? (luck in unluck lol) or i think i know what it could be.
sorry by any dificulty, but if it is what im thinking, the engine is getting files that isnt int the "js engine" local file, like, the whole PC

**Comment by DustEpicKaiSans** [comment]
i got jumpscared by freddy fazbear again, and i just started playing the song

**Comment by moxie-coder** [comment]
disable random botplaytxt setting, it’s a feature, not a bug

**Comment by StinkTheStinker** [comment]
funny
