### ISSUE TITLE
how to disable icon bounce?

### ISSUE THREAD

**Issue by Miuthoi123** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#175]
### What is your question?

i have found some video fnf using js engine but THERE ARE DISABLE ICON BOUNCE
i try update lastest version but i can't found disable icon bounce setting
pls help me

**Comment by JordanSantiagoYT** [comment]
Hey there, I don't know how to disable the icon bounce. It's just a few people who didn't look at their icon bounce settings located in Visuals & UI
