### ISSUE TITLE
Is there any way to remove taunt on go

### ISSUE THREAD

**Issue by TheTrueAccount** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#176]
### Describe your problem here.

I realized that with the new 1.19 update when the countdown finishes on the go bf does the taunt and dad does the up animation
I wanned to ask if there is any way to diseable this on the engine settings, i use this engine to do showcastes and i don't like it a lot

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheTrueAccount** [comment]
This is exacly what i mean by this

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/144788620/94a16e21-7ed1-456f-9ae4-e74061ff2010

**Comment by JordanSantiagoYT** [comment]
you would have to edit the source code to remove it, but i will make a hotfix release that adds an option

**Comment by JordanSantiagoYT** [comment]
> This is exacly what i mean by this
> 
>  the.taunt.thing.mp4

let me guess. this is why you don't use denpa engine

**Comment by TheTrueAccount** [comment]
thanks
