### ISSUE TITLE
the wrong box placement in character editor

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#179]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

when I try clicking on the icon rename box something a little bit weird happened

it didn't decide to type in that box instead it decided to type in the rename and I couldn't rename the icon but to go to notepad and rename the icon

https://youtu.be/CJvLRiCJf2c

please fix this Jorden

### Command Prompt/Terminal logs (if existing)

```bash
idk
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
idk
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by JordanSantiagoYT** [comment]
my guy this footage is NOT clear enough 😭

**Comment by daveandbambifan1234** [comment]
> my guy this footage is NOT clear enough 😭

hold on I will use my Windows computer instead of my dindows, I got the Windows PC from the Milky Way from the other universe

**Comment by daveandbambifan1234** [comment]
https://youtu.be/x7GZK6vW1Do

**Comment by JordanSantiagoYT** [comment]
Issue does not occur for me.

**Comment by moxie-coder** [comment]
closing due to no further response
