### ISSUE TITLE
why did you do this

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#180]
### What feature do you want to get added on the **base** engine?

plus I don't want to type the song's name what if it's a very long name and I am forced to type it please re-add the control C and V back into the engine it saves more time plus it would be better

it's sad that you removed it so I'm saying why are you removing this feature it's really cool and it saves my time while making my mod because I accidentally made it a big update for my mod
I'm trying to update my mod until the end of February

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
I don't even get this at all, but it seems stupid af

**Comment by daveandbambifan1234** [comment]
> I don't even get this at all, but it seems stupid af

I can see why, it probably wasn't you it was probably the thing so I should probably switch this to bug

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> plus I don't want to type the song's name what if it's a very long name and I am forced to type it please re-add the control C and V back into the engine it saves more time plus it would be better
> 
> it's sad that you removed it so I'm saying why are you removing this feature it's really cool and it saves my time while making my mod because I accidentally made it a big update for my mod I'm trying to update my mod until the end of February
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

1. You failed the test.
2. You do realize that.. you don't have to type the song's whole name.. You just have to type what it starts with, the filter will only add songs to the list IF their name starts with whatever you searched.

**Comment by StinkTheStinker** [comment]
for example:
```
you wanted to look for unfairness
you type in unfair
then it finds the song using that, and since unfairness has "unfair", it shows
```

**Comment by StinkTheStinker** [comment]
why did it do that
