### ISSUE TITLE
Copying different sides of a section and a modchart editor in-game.

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#184]
### What feature do you want to get added on the **base** engine?

I want a feature that will allow me to copy a certain side of a section and a feature that can be used to make lua modcharts specifically for moving the notes around. Also,I want another secret menu but for the modchart editor. Thank you for reading this message.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> I want a feature that will allow me to copy a certain side of a section and a feature that can be used to make lua modcharts specifically for moving the notes around. Also,I want another secret menu but for the modchart editor. Thank you for reading this message.
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor and 6K+ support.

asking for a modchart editor is kinda difficult, since nobody has done it before. the only engine i found that has a modchart editor is leather engine, but that engine supposedly removed it due to its bugginess

also, copying a certain side of a section? i might consider it but it's not likely rn

**Comment by moxie-coder** [comment]
@JordanSantiagoYT 
https://github.com/EdwhakKB/FNF-Modcharting-Tools/tree/main

https://github.com/nebulazorua/psych-modchart-thing or you can use the one from troll engine too

**Comment by Happyglitchflyer** [comment]
The modchart stuff looks cool!

**Comment by moxie-coder** [comment]
I might consider adding these soon, if I'm allowed to
