### ISSUE TITLE
notes coming back whenever i deleted it

### ISSUE THREAD

**Issue by rayer2** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#186]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

so basically the bug is like i try to remake the charting of songs that are already charted but i charted it and i delete a note and go to the next section in the chart editor and go back and then the note i deleted is back for some reason so thats why i was wondering if you guys can fix it please?.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt edit anything of the build

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

No

**Comment by JordanSantiagoYT** [comment]
> ### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.
> so basically the bug is like i try to remake the charting of songs that are already charted but i charted it and i delete a note and go to the next section in the chart editor and go back and then the note i deleted is back for some reason so thats why i was wondering if you guys can fix it please?.
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no i didnt edit anything of the build
> 
> ### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?
> None
> 
> ### Did you check for any similar issues to what you're reporting? Check, then come back here.
> No

1. You have to check for a similar issue to what you're reporting. Else if we find a similar one then it'll be marked as a duplicate.
2. This issue doesn't occur for me.
