### ISSUE TITLE
Constant "Null Object Refrence" Error when loading a song with events

### ISSUE THREAD

**Issue by cwill2010** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#190]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

When I boot up a song with 1 or more events, regardless if I launch it from Story Mode or Freeplay, it gives me this error. Do you know how to fix this??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, loading custom songs into base engine.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by moxie-coder** [comment]
it would help if you said what events are in the song, or even showed what events are being used, because this isn’t a lot to work with

**Comment by moxie-coder** [comment]
oh yeah, and provide error logs too

**Comment by BostinTeaParty** [comment]
I have a very similar bug: (Windows, Lua, Latest version(1.20.1): (I loaded into Tutorial, and clicked on any one of the tabs)
flixel/sound/FlxSound.hx (Line 595)
flixel/sound/FlxSound.hx (Line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (Line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (Line 241)
editors/ChartingState.hx (Line 2243)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng

**Comment by JordanSantiagoYT** [comment]
did you delete the click sound effect, located in assets/shared/sounds??

**Comment by moxie-coder** [comment]
> did you delete the click sound effect, located in assets/shared/sounds??

it’s literally a duplicate to #215

**Comment by moxie-coder** [comment]
also closing due to no response

**Comment by cwill2010** [comment]
Sorry for the late response, but here is an example when I ran my remake of REGRET that uses "Change Character" and "Drain" events.

Note.hx (Line 309)
PlayState.hx (Line 5322)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng

**Comment by moxie-coder** [comment]
> Sorry for the late response, but here is an example when I ran my remake of REGRET that uses "Change Character" and "Drain" events.
> 
> Note.hx (Line 309) PlayState.hx (Line 5322) flixel/FlxState.hx (Line 239) flixel/FlxGame.hx (Line 749) flixel/FlxGame.hx (Line 679) flixel/FlxGame.hx (Line 558) openfl/events/EventDispatcher.hx (Line 444) openfl/display/DisplayObject.hx (Line 1400)
> 
> Uncaught Error: Null Object Reference Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag
> 
> > Crash Handler written by: sqirra-rng

things aren't lining up, what version are you on?

**Comment by cwill2010** [comment]
> > Sorry for the late response, but here is an example when I ran my remake of REGRET that uses "Change Character" and "Drain" events.
> > Note.hx (Line 309) PlayState.hx (Line 5322) flixel/FlxState.hx (Line 239) flixel/FlxGame.hx (Line 749) flixel/FlxGame.hx (Line 679) flixel/FlxGame.hx (Line 558) openfl/events/EventDispatcher.hx (Line 444) openfl/display/DisplayObject.hx (Line 1400)
> > Uncaught Error: Null Object Reference Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag
> > > Crash Handler written by: sqirra-rng
> 
> things aren't lining up, what version are you on?

I’m on the latest version
