### ISSUE TITLE
Game keeps crashing randomly when charting a song (possibly) longer than 8 minutes.

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#191]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

No video evidence, due to random crashes to the game

Also, I didn't see any similar issues to this one, since it freezes up, and then crashes, no error message though.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Charting a song (possibly) longer than 8 minutes.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just lua shit, thats it.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by NAEL2XD** [comment]
Are there any popup's saying "Error!" and then a bunch of code of what happend will tell you, if there is send here, it'll be easier

**Comment by StinkTheStinker** [comment]
no, it just freezes, then close's with no window with the error reason at all. thats what i literally just said in the reason section.

**Comment by JordanSantiagoYT** [comment]
There's.. not enough info for me to be able to work on the issue unfortunately

**Comment by StinkTheStinker** [comment]
here, ill try catching the crash. when the crash happens, ill imdediatly start recording and show

**Comment by StinkTheStinker** [comment]
well, try to

**Comment by StinkTheStinker** [comment]
CAUGHT IT, HELL YEA

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a95bfc49-3cb0-4309-b1bb-056eb1cf06df

![Uploading image.png…]()

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/3601d4e9-70ed-46d0-9b57-90d8d817545b)

**Comment by StinkTheStinker** [comment]
autosaved before the crash

made a good choice there :D

**Comment by StinkTheStinker** [comment]
10K MEMORY USED
DAMNN

**Comment by moxie-coder** [comment]
it’s a memory issue with your pc, rn there’s a memory leak that idk how to fix

**Comment by StinkTheStinker** [comment]
what options do you recommend to lessen the chance?

**Comment by moxie-coder** [comment]
is that you save and exit the chart editor, or something like that

**Comment by JordanSantiagoYT** [comment]
you can also hide the grid, for some reason psych engine has a problem where rapidly making grids causes a memory leak

also try turning off "Save Undos" since that also might cause memory leaks when there's a TON of notes

**Comment by moxie-coder** [comment]
> you can also hide the grid, for some reason psych engine has a problem where rapidly making grids causes a memory leak
> 
> also try turning off "Save Undos" since that also might cause memory leaks when there's a TON of notes

✨

**Comment by StinkTheStinker** [comment]
> you can also hide the grid, for some reason psych engine has a problem where rapidly making grids causes a memory leak
> 
> also try turning off "Save Undos" since that also might cause memory leaks when there's a TON of notes

the save undos ill turn off, im just gonna keep "show grid" on because i dont want it lookin weird

**Comment by StinkTheStinker** [comment]
wait, i have one solution

**Comment by StinkTheStinker** [comment]
that might work, idk

when it goes to the next section, it deletes the grid on the one before the next, which might saves memory

**Comment by StinkTheStinker** [comment]
like for example:

you go from section 20>21

it deletes the grid from 20

but, when you go back to a section before that, it deletes the section you were last on, like for example:

20<21
it deletes the grid from 21, and adds back the grid from 20
