### ISSUE TITLE
Uhh, other people play my fnf mod and they crash, but I dont??

### ISSUE THREAD

**Issue by Xenith-MROHIO6337** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#192]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

So, I don't really know if it's my mod that the issue or if it's something that I might have do to with JS Engine or maybe I might have messed with something I shouldn't have messed with, I don't really know?? 

### Command Prompt/Terminal logs (if existing)

```bash
StrumNote.hx (Line 179)
flixel/group/FlxGroup.hx (Line 151)
flixel/group/FlxGroup.hx (Line 151)
flixel/addons/ui/FlxUIState.hx (Line 212)
MusicBeatState.hx (Line 191)
PlayState.hx (Line 4999)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Apparently...
1. My multiple friends opens JS-Engine.
2. They all go into freeplay.
3. They choose ANY Song.
4. Then my friend's crash.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by NAEL2XD** [comment]
inactive for 1 month, someone close this
