### ISSUE TITLE
Engine crashes when i load a non-moving character in a song in chart editor

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#193]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

When i tried to do this on the normal Psych engine, it worked pretty well but idk what is happening on JS engine but it crashes whenever i choose a non moving character in chart editor. A moderator here said to update the egine and instantly closed the thing. It didn't work at all.

### Command Prompt/Terminal logs (if existing)

```bash
https://cdn.discordapp.com/attachments/979114840037683200/1209744447491805235/2024-02-21_07-05-23.png?ex=65e80950&is=65d59450&hm=1343d9a57ce07cd426af7364a2e62f99331e0565b2ac38a520ed742af39b8386&)

Copy and paste it on the url
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
It's pretty easy, use a on moving character like Conbis for example and change characters in chart editor.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added a marathon song with characters and events, that's all

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by JordanSantiagoYT** [comment]
im pretty sure this is an icon issue.

does your icon actually exist? if so, does it have 2 frames or 1?

**Comment by TommykairaXVI** [comment]
Oh my god wait it actually worked. I used other characters icon and worked! Thanks dude :    )
