### ISSUE TITLE
cant compile source code

### ISSUE THREAD

**Issue by FazeBWD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#194]
### Describe your problem here.

i try to compile source code many times but error is appearing saying: certain file missing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i just downloaded the zip and etc

**Comment by FazeBWD** [comment]
discord for dm: mortimer.exe_official

**Comment by FazeBWD** [comment]
also i am the real TOFLMG

**Comment by moxie-coder** [comment]
> ### Describe your problem here.
> i try to compile source code many times but error is appearing saying: certain file missing
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no, i just downloaded the zip and etc

can you atleast show the issue so we can help?

**Comment by JordanSantiagoYT** [comment]
> ### Describe your problem here.
> i try to compile source code many times but error is appearing saying: certain file missing
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no, i just downloaded the zip and etc

1. You didn't provide enough information for us to be able to help.
2. I don't have discord, so giving me your discord is useless.

**Comment by FazeBWD** [comment]
![Uploading Screenshot (6).png…]()
![Uploading Screenshot (7).png…]()
these

**Comment by FazeBWD** [comment]
how do i send images

**Comment by moxie-coder** [comment]
you need to wait for it to finish uploading, please learn how to actually use GitHub 🤦🏻‍♂️

**Comment by FazeBWD** [comment]
I never use GitHub ok? Cut me some slack 😑

**Comment by FazeBWD** [comment]
I go to click on the quick setup, it does it's job, I run lime test windows, and then it says a specific file is missing.

**Comment by FazeBWD** [comment]
Specifically a haxe file. I already got haxe tho.

**Comment by moxie-coder** [comment]
> I go to click on the quick setup, it does it's job, I run lime test windows, and then it says a specific file is missing.

can you copy and paste what the error is? It’s not really helpful if I can’t see what you’re doing

**Comment by StinkTheStinker** [comment]
> Specifically a haxe file. I already got haxe tho.

try using the haxe version that the description of the engine compiling tells you. i did that and it worked for me, don't really know what your talking about, but, that might solve it. who knows

**Comment by JordanSantiagoYT** [comment]
Inactive issue
