### ISSUE TITLE
Question about adding songs

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#195]
### Describe your problem here.

Is there a song based difficulty feature. Like this: Inst-difficulty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by StinkTheStinker** [comment]
if there is, it doesnt work
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/10c91859-1906-4497-aeff-822e82481b6d)

**Comment by StinkTheStinker** [comment]
didnt add the path in there
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/fe73dda5-a27c-46e7-9135-b9744d719d3f)

**Comment by JordanSantiagoYT** [comment]
hey there! no, this engine doesn't have a Difficulty-based song feature.

**Comment by StinkTheStinker** [comment]
if ima be honest, thought there was

**Comment by StinkTheStinker** [comment]
would be a good idea if ima be honest

**Comment by moxie-coder** [comment]
ok

**Comment by NAEL2XD** [comment]
inactive for 1 month, someone close this
