### ISSUE TITLE
finally got it, i was literally recording somthing

### ISSUE THREAD

**Issue by DustEpicKaiSans** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#197]
### Describe your problem here.

bruh, i was doing a chart, and this happens

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150727511/87362eae-fa18-4df3-acd0-5f214e767065

is this something in the game or what

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DustEpicKaiSans** [comment]
pls, dont talk about the unboundhusk lol, and the fnaf shit that happens

**Comment by moxie-coder** [comment]
intentional game design

**Comment by moxie-coder** [comment]
I already said to disable the random bot play texts in settings, under visual ui

**Comment by DustEpicKaiSans** [comment]
but i like the bot play texts

**Comment by DustEpicKaiSans** [comment]
sorry for annoying u, and if i stay 3 minutes, bf will steal my liver? (when the botplay text appeat "3 minutes until I steal your liver.") (joke)

**Comment by PatoFlamejanteTV** [comment]
I'M LAUGHING SO FUCKING LOUD WHY IS THE JUMPSCARE ALMOST SYNC
