### ISSUE TITLE
Solve for that volume bug

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#198]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

you know that when you change the game volume while notes are happening right? why not just remove the volume sound, i mean, almost every part of the engine uses sounds

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
change the game volume while a song is playing
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nuh uh

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

No

**Comment by StinkTheStinker** [comment]
also, the reproduce info section is in code format

**Comment by moxie-coder** [comment]
alright this just makes no sense at all, there’s no way we’re just gonna remove the sounds retard

**Comment by JordanSantiagoYT** [comment]
> alright this just makes no sense at all, there’s no way we’re just gonna remove the sounds retard

you know you don't have to be that rude..

**Comment by moxie-coder** [comment]
> > alright this just makes no sense at all, there’s no way we’re just gonna remove the sounds retard
> 
> you know you don't have to be that rude..

sorry I’m just annoyed by this

**Comment by StinkTheStinker** [comment]
it was just one  small damn thing

**Comment by StinkTheStinker** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/fbe0cc85-4e4b-4f93-a6fb-8dc50241f787

**Comment by StinkTheStinker** [comment]
its still laggy
even when its like that

**Comment by PatoFlamejanteTV** [comment]
Bros phone is on his last breaths 😭😭🙏🙏
