### ISSUE TITLE
help w/ opponent noteskin

### ISSUE THREAD

**Issue by TXGamer56** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#200]
### Describe your problem here.

I need help getting the opponent noteskin in the character editor to work. I follow the instructions but I don't think I have enough information to do so, I just need a more in depth explanation since I don't know what i'm doing ._.

_plz help_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by moxie-coder** [comment]
you would just simply add them in the character editor like you would with a regular noteskin

**Comment by JordanSantiagoYT** [comment]
also note that character noteskins aren't fully working yet, this will be fixed in 1.20.0
