### ISSUE TITLE
game buggy

### ISSUE THREAD

**Issue by Attila2012** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#201]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

im trying to play the game but im getting a error
![problem](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/160651562/c407b02a-8053-49fe-b662-0fd5ad40b420)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by moxie-coder** [comment]
update to the latest version

**Comment by JordanSantiagoYT** [comment]
Issue is inactive.
