### ISSUE TITLE
well explain this bug that happened out of nowhere

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#205]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/b1aa38b6-73f0-469a-9a83-ed9c330c57ee)
I never seen that before when you remove the event it still has the information that I used to have when I remove it

### Command Prompt/Terminal logs (if existing)

```bash
t
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
t
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by JordanSantiagoYT** [comment]
oh yeah, that's kinda present in the version. idk any way to fix this currently
