### ISSUE TITLE
Windows Version not released

### ISSUE THREAD

**Issue by PDL2CGamejolt** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#206]
### Describe your problem here.

The Windows version of v1.20.0 didn't release.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by PDL2CGamejolt** [comment]
nvm

**Comment by JordanSantiagoYT** [comment]
i realized that, stefan broke the release workflow 😭 ive fixed it and im rereleasing it now
