### ISSUE TITLE
uhhh

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#208]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/175d7305-20d1-4e56-8990-199dc882e92c)
please fix this ASAP you broke all of my icons now they're cut off like a joke icon

### Command Prompt/Terminal logs (if existing)

```bash
fdghdfgh
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
fghdfghdfg
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by daveandbambifan1234** [comment]
I'm so upset about this now I have to change the characters icons, literally

**Comment by moxie-coder** [comment]
will be fixed soon
