### ISSUE TITLE
how do i use game rendering?

### ISSUE THREAD

**Issue by MapidsFanAnimator** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#211]
### What is your question?

idk where is the mp4 that i exported a song, but the mp4 of the fnf song not showing, can anyone tell me how to render it as a mp4?

**Comment by JordanSantiagoYT** [comment]
hey there! so the rendered song will be in (JS Engine directory)/assets/gameRenders. Whatever song you play through, the frames for your video will be in a folder that matches the name of the song you played.

There's also a readme file that tells you how to use CMD to render it. You do need FFmpeg though

**Comment by JordanSantiagoYT** [comment]
I will publish a tutorial soon

**Comment by JordanSantiagoYT** [comment]
https://www.youtube.com/watch?v=F1-Ypaf9EwI
