### ISSUE TITLE
this would be extremely cool if you added it

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#212]
### What feature do you want to get added on the **base** engine?

please add this custom hurt note for each note type because when you set your note type to anything then the hurt note texture will be different to match the hurt note for the note art style
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/c86984c4-a233-4168-ba74-72ec9d97872b)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
it would kinda be too much work.
