### ISSUE TITLE
Game render frames saving in main directory in Linux

### ISSUE THREAD

**Issue by cyklusiguess** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#213]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

When using Game Renderer in Linux, it creates folders but doesn't save the frames in the folders, and the names of the frames images are names like "assets\gameRenders\microphobia\0000000", Linux uses / instead of \.

![come on man ples](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100812875/5a574ce6-2b86-411b-848a-591e3fb1435b)

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100812875/f0f1bad8-d2ae-4b8a-8652-6ad58a638a39)

### Command Prompt/Terminal logs (if existing)

```bash
,
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I just enabled Game Renderer
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

No

**Comment by cyklusiguess** [comment]
linux uses / instead of \* fuck you github

well now you know

**Comment by cyklusiguess** [comment]
I CAN'T ENTER THE BACKSLASH IN GITHUB COMMENTS

**Comment by JordanSantiagoYT** [comment]
try the newest commit

**Comment by cyklusiguess** [comment]
it's still being not fixed
![307649367-277ba0f1-529f-4906-9a7d-9521458cb7cc](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100812875/deea285d-9603-47e6-8929-1c895c64ff5b)

**Comment by JordanSantiagoYT** [comment]
try the latest action build, HOPEFULLY it's fixed now
