### ISSUE TITLE
Background Charting music stacking up when realoding a json file

### ISSUE THREAD

**Issue by TheFunnyDav** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#217]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

When pressing 7 on the main menu and after that going into the chart editor if you wait till the background music plays and then reloading a json file the music won't stop, it will just keep playing with the other music because you realoaded a new json file and it plays two songs at the same time.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Waiting for the song to play in the chart editor and then reloading the json the song won't stop it will keep playing with the other song of the realoded json, you can do it mutiple times realoding the jsons even I did it accidentally while charting.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by JordanSantiagoYT** [comment]
Already fixed in latest commit.
