### ISSUE TITLE
crashes when exiting from editors or clicking things in editors (1.20.1)

### ISSUE THREAD

**Issue by randomslovakguy** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#218]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

crashes when exiting from editors or clicking things in editors

example:
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159710048/6aff6ec6-6e53-44a3-8d38-c34700de7ea9

### Command Prompt/Terminal logs (if existing)

```bash
flixel/sound/FlxSound.hx (Line 595)
flixel/sound/FlxSound.hx (Line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (Line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (Line 241)
editors/ChartingState.hx (Line 2243)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 552)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

is this the thing?
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. go to any editor
2. press escape or click anything in the editor
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by JordanSantiagoYT** [comment]
I FINALLY FIGURED OUT WHAT THIS ISSUE IS CAUSED BY

it appears when i run idleMusic.destroy, it destroys the music even if a fadeTween is happening. if fadeTween is running while the music is destroyed, it will crash the game because the tween tries to edit a now null value. This will be fixed!!

**Comment by randomslovakguy** [comment]
when
