### ISSUE TITLE
600 x 300 icon issue

### ISSUE THREAD

**Issue by BlockiiThinkss** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#219]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

I actually don't know why but, when putting a 600 x 300 icon in the game, it crops off, i'm using the latest version

![image_2024-02-28_063336339](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150886698/ea04e3e0-bc8c-4e06-9e90-a5dd04191c8d)

![Screenshot 2024-02-28 063541](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150886698/b71eb98f-c45f-4ac9-9165-902649ed4efc)

![Screenshot 2024-02-28 063554](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150886698/0757267e-575f-4034-b826-354f4bfdcd6f)

![Screenshot 2024-02-28 063613](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150886698/d86fec3b-fe3b-4790-a9e0-6e6f31b8bae6)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I don't think there's nothing I can really do but I tried resizing it, but it makes it way smaller.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by moxie-coder** [comment]
duplicate #208
