### ISSUE TITLE
Chart Editor Section Bug

### ISSUE THREAD

**Issue by Xenith-MROHIO6337** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#220]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

So, whenever the new update came out, it brought a bug to the chart editor for some reason?

What the bug is: so in ANY section that has 4 "Beats Per Section" is 100% fine, the problem is, if I CHANGE it to like, 6, or 8, it will OFFEST when I place the note (in a different section), and that note that I placed will either go LOWER, or HIGHER, depending on what Number the Beats Per Sections IN THAT SECTION, is.

It doesn't crash, but it gets annoying.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

I can use a video to showcase the bug? If needed?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I do not know what I edited Ima keep it real.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by moxie-coder** [comment]
because it’s offsetting to be fitting with the song, it’s been a bug since psych was released and I don’t know how to fix that

**Comment by Xenith-MROHIO6337** [comment]
It does it for ALL the charts I CHART, Even with a CLEAN VERSION.
