### ISSUE TITLE
JS Engine - Known Issues/Suggestions

### ISSUE THREAD

**Issue by JordanSantiagoYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#222]
### What needs to be documented?

this is just a page for those that want to know what issues i'm aware of

## Status Legend
✅ - Fixed/Released
❌ - Not fixed yet
🟢 - Fixed, will release in the next update
🟡 - Working on a fix
🟠 - Low Priority
🔴 - Currently not a priority
⚫ - Unfixable/Unable to implement

# Bugs

Big icons will crop off - 🟡
Sometimes the preloader will crash the engine because of a broken path - 🟡
If you exit an editor while music is fading in, the engine will crash - 🟢
If you reload a JSON in the Chart Editor, the music will stack on top of each other - 🟢
macOS users cannot open the Engine - 🔴 (I do not use macOS.)
Linux users will have frames saved in Rendering Mode save to the main directory instead - 🟢

# Suggestions
Extra key support (up to 18K) - ⚫ (Would break noteskins.)
Modchart Editor - 🔴
Making the engine work with the latest libraries - ✅

**Comment by moxie-coder** [comment]
@JordanSantiagoYT I saw a way to implement extra keys without breaking the note skins, I’ve seen a repo do it before
https://github.com/Starmapo/FNF-PsychEngine-Extra

**Comment by JordanSantiagoYT** [comment]
> @JordanSantiagoYT I saw a way to implement extra keys without breaking the note skins, I’ve seen a repo do it before https://github.com/Starmapo/FNF-PsychEngine-Extra

The base noteskin there is an EK noteskin (aka. one that uses more than 4 keys)

**Comment by moxie-coder** [comment]
> > @JordanSantiagoYT I saw a way to implement extra keys without breaking the note skins, I’ve seen a repo do it before https://github.com/Starmapo/FNF-PsychEngine-Extra
> 
> The base noteskin there is an EK noteskin (aka. one that uses more than 4 keys)
> 
> What I mean by breaking noteskins is that adding EK would make all the current noteskins in this engine (aside from the default one) unusable, because they don't support key counts higher than 4

yeah but checks for ek more skins can be added though, since the xml names and such are different, and we can check if they’re different or not

**Comment by moxie-coder** [comment]
like this, but there’s other methods too

![IMG_4219](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/78aed4d0-9cde-493f-aec1-7cfe4e6d8521)

**Comment by JordanSantiagoYT** [comment]
Starting from 1.36.0 onward, all known bugs from this version and later will be sorted by the update that said bug was first found in.

**Comment by TheStinkern** [comment]
did anyone notice this issue is the 222nd issue
