### ISSUE TITLE
I'm going to use the 1.19.1 version of JS engine for now I'm just going to wait for 1.20

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#223]
### What is your question?

remember the closed issue where Jordan has bugs that he's aware of well I wonder when he will fix them and it might take a long time probably, so I'm just going to use 1.19.1 version of the engine for now

**Comment by daveandbambifan1234** [comment]
I also wanted Jordan to make the icon at any size like all the other versions

**Comment by moxie-coder** [comment]
#222
