### ISSUE TITLE
Error compiling engine when i already have hxdiscordrpc

### ISSUE THREAD

**Issue by CleanerCosine14** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#225]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

What do i need to do?

### Command Prompt/Terminal logs (if existing)

```bash
Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by CleanerCosine14** [comment]
![Captura de pantalla 2024-02-29 170251](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/103971101/b2f8ca41-5a97-46b1-a653-674f4d2eccac)

I already have this library installed but it still gives me an error

**Comment by JordanSantiagoYT** [comment]
are you compiling directly from the jse source code? like, is the .haxelib folder in the same location as the one you're building from

**Comment by CleanerCosine14** [comment]
> are you compiling directly from the jse source code? like, is the .haxelib folder in the same location as the one you're building from

Yes im trying to compile your engine through source. It gives me an error when i compile. i already have hxdiscord_rpc installed but still failed to compile.

**Comment by CleanerCosine14** [comment]
And through C:/HaxeToolKit i already installed that aswell

**Comment by JordanSantiagoYT** [comment]
Try installing hxdiscord_rpc globally. If that doesn't work, remove hxdiscord_rpc and reinstall it

**Comment by moxie-coder** [comment]
> ### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.
> What do i need to do?
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?
> ```
> 
> ### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no
> 
> ### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?
> None
> 
> ### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.
> Yes

it’s a bug with the haxelib, you have to install it globally
