### ISSUE TITLE
Question about force changing an option with lua

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#226]
### Describe your problem here.

how do i make it choose what i want it to choose if theres more than two options?
like, i tried, wont work. 

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/e05a1029-a8ed-4e3a-97cc-fa04110f1dfb

used a different recording app also, idk how laggy or not it is

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by StinkTheStinker** [comment]
holy shit that is smooth. w recording app

**Comment by JordanSantiagoYT** [comment]
okay, first of all why are you still using 1.16.0
second of all, why are you forcing ghost tapping off multiple times
third of all, why is Dave and Bambi not in quotation marks

**Comment by StinkTheStinker** [comment]
im forcing other options, i copied and pasted them, its not changed yet

**Comment by StinkTheStinker** [comment]
the reason why im using 1.16 still is because, i dont know, i just dont want to transfer the mod over to the new version

**Comment by StinkTheStinker** [comment]
also, it was the quotation marks reason
