### ISSUE TITLE
when i chart a song in the chart editor and i press "enter", the engine shows a message and then crashes

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#227]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

read title

### Command Prompt/Terminal logs (if existing)

```bash
flixel/sound/FlxSound.hx (Line 595)
flixel/sound/FlxSound.hx (Line 739)
flixel/sound/FlxSound.hx (Line 563)
flixel/tweens/misc/NumTween.hx (Line 53)
flixel/tweens/FlxTween.hx (Line 1263)
flixel/FlxGame.hx (Line 747)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
duplicate #215
