### ISSUE TITLE
export in source is missing

### ISSUE THREAD

**Issue by glitchyhope** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#228]
### What needs to be documented?

export/release/windows/bin etc.

**Comment by moxie-coder** [comment]
did you check for any errors in your console?

**Comment by JordanSantiagoYT** [comment]
> ### What needs to be documented?
> export/release/windows/bin etc.

When you download the source code, there's no export folder. You have to compile the engine yourself for it to show.

**Comment by moxie-coder** [comment]
yeah, that’s probably what you did
