### ISSUE TITLE
Automatic hidden notes!

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#229]
### What feature do you want to get added on the **base** engine?

I want an automatic hidden notes option that hides the notes if your computer can't handle it or at least if the chart has 1 million+ notes!
My chart:
![JSEngine 2024-03-05 17-40-17-089](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145864869/949b1a15-25ea-4043-a203-00dbe43b30da)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
..why would this be needed in any scenario
