### ISSUE TITLE
Unable to enter charting mode? 

### ISSUE THREAD

**Issue by Loopedrage** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#230]
### Describe your problem here.

I've recently started to use this engine from normal PE, and I've suddenly been unable to press 7 to enter charting/debug mode when I make new charts. I know that I don't have it disabled in settings, since charting mode only works in charts that I've previously made and ported over to this engine. If anyone knows a fix, I would greatly appreciate it!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JordanSantiagoYT** [comment]
Did you set the song's 7 event to something other than "None", "" or null ?

**Comment by Loopedrage** [comment]
The 7 event in every chart I have appears to be null, is it supposed to be something else?

**Comment by JordanSantiagoYT** [comment]
> The 7 event in every chart I have appears to be null, is it supposed to be something else?

It's supposed to be either "", "None" or "---". I will add a check for null however.

**Comment by Loopedrage** [comment]
Got it working with "---", thanks a bunch. It's a bit strange that my ported charts have the exact same "null" settings but can still press 7 to enter charting mode, though.
