### ISSUE TITLE
source code help

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#231]
### Describe your problem here.

i tried to do some compiling with the latest source code, how do i fix this?

`Error: Could not find include file "C:/haxelib/hxCodec/3,0,2/vlc/lib/LibVLCBuild.xml"`

i used that _.bat_ file in the source code as well

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by moxie-coder** [comment]
`haxelib set hxCodec 3.0.2` outside the directory for the engine

**Comment by moxie-coder** [comment]
it’s a bug with the haxelib, that’s already been [fixed before](https://github.com/polybiusproxy/hxCodec/pull/287)

**Comment by StinkTheStinker** [comment]
that should be put in the _.bat_ file. so no duplicates happen

**Comment by StinkTheStinker** [comment]
now its showing this
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/acff19ce-3d23-406c-81c4-17573beacdc3)

**Comment by JordanSantiagoYT** [comment]
also why are you using hxcodec 3.0.2? the recommended version is 2.5.1

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/7c899219-dd24-4fea-843e-e851da14025b)

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/145304742/311040162-7c899219-dd24-4fea-843e-e851da14025b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDk0ODgsIm5iZiI6MTcwOTg0OTE4OCwicGF0aCI6Ii8xNDUzMDQ3NDIvMzExMDQwMTYyLTdjODk5MjE5LWRkMjQtNGZlYS04NDNlLWU4NTFkYTE0MDI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMjA2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWI0ZmRiMmI4ZTk3ZDUxYjNhM2U3MTBjMjlmNWJlN2YyYWVhYTg1MWFhOWUzMDU5MzNhOTJlYWUxMDQ0YTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tLVRIQE8MBfGTKOGB9HE_yQmGDSkE1ZrDUBPqSb6euQ)

do `haxelib set hxCodec 2.5.1` in the same folder as .haxelib, which is the engine folder

**Comment by JordanSantiagoYT** [comment]
> ![image](https://private-user-images.githubusercontent.com/145304742/311040162-7c899219-dd24-4fea-843e-e851da14025b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTk0MzMsIm5iZiI6MTcwOTg1OTEzMywicGF0aCI6Ii8xNDUzMDQ3NDIvMzExMDQwMTYyLTdjODk5MjE5LWRkMjQtNGZlYS04NDNlLWU4NTFkYTE0MDI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwMDUyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGU5YTYzMDAyNTU2N2M1Mzk3NzUxNWM4ZWRhMjljMGRhNzEzMjZhZTFmZDdmNjNjYzVkYmZmZWU1YmVmZDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bHIoOWsXv403V5t-0SuuUWgAb0o9wNGSL9yqzRixUQo)

you did this in the nobotplay lag directory, which likely means you didn't get it globally. go out of the nbl directory and run the same command.
