### ISSUE TITLE
The engine crashes when i load a song

### ISSUE THREAD

**Issue by TommykairaXVI** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#232]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

So uhh i put a .ogg song in mod>songs>(song folder)>the song i insterted and uhh when i load it either on chart editor or play it in freeplay, it crashes by giving me this error:

### Command Prompt/Terminal logs (if existing)

```bash
openfl/media/Sound.hx (Line 407)
Paths.hx (Line 471)
editors/ChartingState.hx (Line 1938)
editors/ChartingState.hx (Line 1922)
editors/ChartingState.hx (Line 602)
flixel/ui/FlxButton.hx (Line 521)
flixel/ui/FlxButton.hx (Line 507)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Error loading sound from file: mods/songs/452/Inst.ogg
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
make sure you’re an valid sound file, and not just a renamed audio file from an different extension to ogg

use audacity to convert it to an ogg
https://manual.audacityteam.org/man/ogg_vorbis_export_options.html

**Comment by TommykairaXVI** [comment]
ok nvm i found a way to fix this
