### ISSUE TITLE
multiple bugs caught

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#233]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

1. when I opened the game up a haxe flixel logo appears and Fades away
2. when I enter a song command prompt opens up for a split second and closes

### Command Prompt/Terminal logs (if existing)

```bash
.
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

noting

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
I caught another one when I went in the song stress the player into girlfriend is black boxes and the notes don't even move they just glitch back and forth

**Comment by daveandbambifan1234** [comment]
> I caught another one when I went in the song stress the player into girlfriend is black boxes and the notes don't even move they just glitch back and forth

and even worse stress is the glitchiest song in the engine

**Comment by JordanSantiagoYT** [comment]
Did you delete the splash folder located inside assets?

**Comment by JordanSantiagoYT** [comment]
> I caught another one when I went in the song stress the player into girlfriend is black boxes and the notes don't even move they just glitch back and forth

Also, this isn't an issue with my engine, it's more of a "your PC didn't have enough memory to load a sprite, therefore the sprite is a black box instead so it avoids crashing your PC" issue

**Comment by moxie-coder** [comment]
all of those are intended features

**Comment by NAEL2XD** [comment]
> > I caught another one when I went in the song stress the player into girlfriend is black boxes and the notes don't even move they just glitch back and forth
> 
> Also, this isn't an issue with my engine, it's more of a "your PC didn't have enough memory to load a sprite, therefore the sprite is a black box instead so it avoids crashing your PC" issue

i did not delete it, instead you did not include splashes in assets on one of your builds

**Comment by NAEL2XD** [comment]
> Did you delete the splash folder located inside assets?

Have you forget to also include the splash folder on builds? because mine seems missing
