### ISSUE TITLE
Notes come back from the dead.

### ISSUE THREAD

**Issue by SuperRyan0308** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#234]
### Describe your problem here.

I don't if this is a bug or I am being dumb but for some reason when I zoom in or out the notes that I removed come back after I zoom in or out. So is this a bug or a feature?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SuperRyan0308** [comment]
I was not modding or anything I was just messing with the chart editor then this random thing happened

**Comment by SuperRyan0308** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/162759283/02d82e0e-f0ac-4ab2-8516-5c44de72b462

**Comment by moxie-coder** [comment]
it’s a bug I’ll try to fix

**Comment by SuperRyan0308** [comment]
yes, I am on the latest version. It first happened on verison 1.20.0.
