### ISSUE TITLE
Bug with health bar intro not moving icons properly

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#235]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

The health bar rising animation does not bring the icons with it.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89111294/2fcd7c73-3730-478b-aa08-b135f458e23d)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Not really.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by TheKamboy** [comment]
Nevermind, I figured out the issue.

**Comment by TheKamboy** [comment]
It was with one of my scripts.

**Comment by TheKamboy** [comment]
Through more testing it has to do with the song Hyperyakuzonal.

**Comment by JordanSantiagoYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/3977b4e9-84c9-4808-b95d-59f06d301081

**Comment by JordanSantiagoYT** [comment]
doesn't occur for me.

**Comment by moxie-coder** [comment]
issues with mods isn’t exactly our issue

**Comment by TheKamboy** [comment]
Well I fixed it with a script, so that's solved.

**Comment by JordanSantiagoYT** [comment]
root cause was identified, and a fix has been pushed out in the latest commit
