### ISSUE TITLE
Going to the chart editor for the first time, BUT NOT in the second time

### ISSUE THREAD

**Issue by cyklusiguess** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#237]
### Describe your problem here.

Why does 7 not work after the second time when charting? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

**Comment by cyklusiguess** [comment]
nvm, i think it got fixed

**Comment by moxie-coder** [comment]
see #230
