### ISSUE TITLE
How to disable the (Bot) thing in the time bar?

### ISSUE THREAD

**Issue by cyklusiguess** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#239]
### Describe your problem here.

title

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100812875/7205f73d-5b72-43ee-8932-5ecfd3732d54)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

**Comment by moxie-coder** [comment]
![IMG_4301](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/4bff95d4-9846-4f0c-be86-5e12b01dc0c9)

**Comment by JordanSantiagoYT** [comment]
> ### Describe your problem here.
> title
> 
> ![image](https://private-user-images.githubusercontent.com/100812875/311523537-7205f73d-5b72-43ee-8932-5ecfd3732d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwOTM3ODQsIm5iZiI6MTcxMDA5MzQ4NCwicGF0aCI6Ii8xMDA4MTI4NzUvMzExNTIzNTM3LTcyMDVmNzNkLTViNzItNDNlZS04OTMyLTVlY2ZkMzczMmQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxNzU4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGYyYzBmODk3MDlmMjNkYWI2ZDE3ZWE2MTEyOTljYjFjZGYwY2UwYTFiNTA4MzlmODA5NzM3ZDU3M2RkODAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ePvude7ewSgzV9f2Q48OAK4VtJBd7OEPd-hJ2gdllSM)
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Linux
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

You don't :D
