### ISSUE TITLE
what the fuck

### ISSUE THREAD

**Issue by newfuckingplayer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#240]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

mousecapade isnt fucking working

### Command Prompt/Terminal logs (if existing)

```bash
StrumNote.hx (Line 185)
flixel/group/FlxGroup.hx (Line 151)
flixel/group/FlxGroup.hx (Line 151)
flixel/addons/ui/FlxUIState.hx (Line 212)
MusicBeatState.hx (Line 84)
PlayState.hx (Line 4945)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
play mousecapade
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

im trying to port something made in psych engine to this engine

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by moxie-coder** [comment]
invalid notes xml, you need to make sure you have a valid note xml

**Comment by newfuckingplayer** [comment]
whats exactly was the xml
