### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Chrominuslol** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#242]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

It says 
Error: Could not find haxelib "hxdiscord_rpc",  even though I used quick setup, tried uninstalling hxdiscord_rpc than quick setup again, still says not found

### Command Prompt/Terminal logs (if existing)

```bash
D:\FNF\JS ENGINE\2\FNF-PsychEngine-NoBotplayLag-main>lime test windows
source/Achievements.hx:255: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
No
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
it’s a bug with that haxelib, open a new command prompt and `haxelib install hxdiscord_rpc`
