### ISSUE TITLE
Screen Shake Append to Character

### ISSUE THREAD

**Issue by ChandelureF-5** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#243]
### What feature do you want to get added on the **base** engine?

This is a humble request to allow for appending Screen Shake values to individual characters. Ideally this would also allow for player characters to shake the screen, but this is only an added layer of flavor. 

How this would work is the intensity increments by 0.01 as opposed to 0.05, while duration still increments in 0.05 so as to not break the schema.

OPTIONAL BONUS: Add the ability to increment shake duration and health drain in lower values than 0.05, such as 0.005 or 0.001. That would certainly make my day much better.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
I’ll see if I can make that happen

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> This is a humble request to allow for appending Screen Shake values to individual characters. Ideally this would also allow for player characters to shake the screen, but this is only an added layer of flavor.
> 
> How this would work is the intensity increments by 0.01 as opposed to 0.05, while duration still increments in 0.05 so as to not break the schema.
> 
> OPTIONAL BONUS: Add the ability to increment shake duration and health drain in lower values than 0.05, such as 0.005 or 0.001. That would certainly make my day much better.
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor and 6K+ support.

This is a cool suggestion, I will add this in!

**Comment by JordanSantiagoYT** [comment]
however, why would shake duration be needed is a question i have?

**Comment by JordanSantiagoYT** [comment]
for a funny should i make the shake duration stack

**Comment by ChandelureF-5** [comment]
yeah, sustains should count as note hits to the shake

**Comment by JordanSantiagoYT** [comment]
Ok
