### ISSUE TITLE
If time bar is set to disabled, the rendering will not kick you out of playstate, unless it is other than "disabled"

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#244]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

So i was rendering my newest video (such as "Cease (REMAKE)" but the rendering wouldn't want to kick me out of playstate, so i just moved on, but when i did with "Agony NULLIFIED" it still wouldn't kick me out, so i checked the options and setted "Time Bar" to anything other than "disabled" and it just kicked me out??  that's why i made an issue about it.

i know this wouldn't be fixed but here is the clip so you would know why: 

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/108278470/8b30aeca-6a64-4fc6-a1ab-b3c8ab39cba9

Song is "Cease (REMAKE)" by kasperfnf

### Command Prompt/Terminal logs (if existing)

```bash
no
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. Go to Options > Game Rendering > Video Rendering Mode and set it to on
2. Go back and instead, go to Visuals and UI
3. Press down button 35 times and Set "Time Bar" to disabled
4. Go to freeplay and play a song
5. Wait until the song's ended, you should be kicked out but you don't
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, didn't edit, only latest action build

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/34dc5a9e-dda8-40ee-a318-8083ed7b924a)
mb i put the rendering mode code in the updateTime function 😭
