### ISSUE TITLE
Option search!

### ISSUE THREAD

**Issue by BostinTeaParty** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#245]
### What feature do you want to get added on the **base** engine?

An ability to search for a specific option, there are so many i cant find them all!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
it just adds more noise in the code, and plus they're already categorized in a way so no

**Comment by JordanSantiagoYT** [comment]
> it just adds more noise in the code, and plus they're already categorized in a way so no

oh






but i already added it?

**Comment by moxie-coder** [comment]
> > it just adds more noise in the code, and plus they're already categorized in a way so no
> 
> oh
> 
> but i already added it?

oh
