### ISSUE TITLE
please add "addWiggleEffect" shader option for lua stages

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#246]
### What feature do you want to get added on the **base** engine?

it would be cool if there's wiggle effect types of it so i can use this for my stages and make it REALLY COOL!!!!

code:
https://github.com/HaxeFlixel/flixel-demos/blob/dev/Effects/BlendModeShaders/source/effects/WiggleEffect.hx

here's what it looks like:
https://haxeflixel.com/demos/BlendModeShaders/

(ps. i love ‎HEAT_WAVE_HORIZONTAL and HEAT_WAVE_VERTICAL shader type so that's why i requested this)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by NAEL2XD** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/108278470/998619ee-68ee-4f28-b682-fb15689b7325)
should be something like this

**Comment by JordanSantiagoYT** [comment]
how would the value strengths work?? like.. does it just multiply those values

**Comment by NAEL2XD** [comment]
uh maybe

**Comment by moxie-coder** [comment]
> how would the value strengths work?? like.. does it just multiply those values

pretty sure those are just for whether how much it wiggles horizontally and vertically

**Comment by JordanSantiagoYT** [comment]
don't the base waveSpeed, waveFrequency and waveAmplitude values handle that though

**Comment by moxie-coder** [comment]
> don't the base waveSpeed, waveFrequency and waveAmplitude values handle that though

I guess, it could just be a multiplier for it though
