### ISSUE TITLE
Error for the Character event

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#247]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

I'm trying to use the Character Switch event, but I'm getting the "Null Object Reference" error.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I can't reproduce the bug since it's an event.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I'm using the built version

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by moxie-coder** [comment]
I can’t do much to help if you can’t reproduce the bug, or anything like that, and we need error logs too

**Comment by Happyglitchflyer** [comment]
I know now that it's the property change for the variable "dad". That's why it's acting crazy.

**Comment by moxie-coder** [comment]
Ok
