### ISSUE TITLE
Comprehensive Lua HUD Utilities

### ISSUE THREAD

**Issue by ChandelureF-5** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#249]
### What feature do you want to get added on the **base** engine?

This is a request that I know will take a LOT longer than the last request, but since hardcoded HUDs are no longer a thing, adding the proper Lua functions and callbacks for all the HUD elements(and maybe even a callback to switch HUD types, but this is purely optional) would be the only logical next step on this venture. After all, with this in place, JS Engine could become even MORE user friendly than it's ever been before.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by moxie-coder** [comment]
I don’t understand this, I think you’re talking about the remake
