### ISSUE TITLE
why does it shows this when i want to set up a new character

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#25]
### Describe your bug here.

i dont understand why whenever i tried to put a character name it only shows up as an image not being a spritesheet
why does this happen?
<img width="434" alt="image" src="https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/0777da0e-6571-4830-9fb3-eec45662bbe3">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
check if the character image you’re loading actually has an xml file, otherwise it’ll display the whole image instead of the animation you actually want

**Comment by Mushymushroom12** [comment]
@JordanSantiagoYT it has, its just idk how it went like this
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/5276550f-ae2c-47d5-bfc7-5dcbbdce8f1c)

**Comment by Mushymushroom12** [comment]
i mean that*

**Comment by JordanSantiagoYT** [comment]
i dunno, but i might be sure that this isnt a js engine-specific issue

**Comment by Mushymushroom12** [comment]
just found out that i had to un-check the "as playable character" option
