### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#251]
### What feature do you want to get added on the **base** engine?

I want JS engine to have a shortcut for the spam tools(The toggle button). I don't want to keep going back in forth just to enable and disable the spam tools.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
but... don't you already have to go to the menu to change the spam count and spam mult

**Comment by moxie-coder** [comment]
> but... don't you already have to go to the menu to change the spam count and spam mult

ikr
