### ISSUE TITLE
how to do the spam thing in the chart editor I can't figure out but it was in OS engine

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#253]
### Describe your problem here.

when I was charting I instantly forgot this one thing how to do the os engine spam

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
Press C while your mouse is in the grid.
