### ISSUE TITLE
More spamchrting tools

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#255]
### What feature do you want to get added on the **base** engine?

I want a spamcharting feature that can change the distance of duplicates.
![JSEngine 2024-03-29 17-04-22-838](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145864869/b1269490-be6e-4c77-a416-1e61e56e9b03)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
You already have one.

The Shift by # Steps Stepper

**Comment by Happyglitchflyer** [comment]
It's mainly for when you have to duplicate it over a certain distance because the step shifter shifts all the notes in a section.

**Comment by JordanSantiagoYT** [comment]
The step shifter also determines the distance of each duplicate

**Comment by Happyglitchflyer** [comment]
But since there is nothing that's used to select certain notes, it's hard to actually shift the notes you want to shift.

**Comment by JordanSantiagoYT** [comment]
Yeah, I can't really add that because it's kinda.......

***d i f f i c u l t***

**Comment by Happyglitchflyer** [comment]
What about using some of the code from CDEV Engine?

**Comment by JordanSantiagoYT** [comment]
wait cdev added that-

**Comment by Happyglitchflyer** [comment]
Yeah. I saw a video for the showcase and it show that feature along with moving them.

**Comment by JordanSantiagoYT** [comment]
Good news is that I will be adding it

**Comment by JordanSantiagoYT** [comment]
ok ive actually reconsidered, since if you select note spam and move it it automatically turns into stacked 16th notes

**Comment by Happyglitchflyer** [comment]
Can't you code something that can override that like maybe changing some of the code from cdev to keep it at no snap?

**Comment by JordanSantiagoYT** [comment]
> Can't you code something that can override that like maybe changing some of the code from cdev to keep it at no snap?

I was gonna consider adding smth like only making it snap the first note (and holding SHIFT removes the snap) then moving the notes based off that note's strum time but didn't really get to see how that would work

**Comment by moxie-coder** [comment]
right now, I don't feel like adding more tools for spamcharting, I might add more later if I don't ever forget, but otherwise I don't feel like adding more rn
