### ISSUE TITLE
Cant place events, Engine crashes!

### ISSUE THREAD

**Issue by Domxoxo** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#256]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

okay, so i go into the Chart edtior, place an event, then start the song. and at the time when the event is placed. it crashes! dont really know what happens. 

so i go into the song.
![opennormally](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159272539/40b43895-fa03-4322-b417-184270806643)

go into the editor, place an event down, then start the song, it crashes at the time of the event! heres a vid.

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159272539/e34a6ce3-7609-4a2b-9f23-3c7475519ca3

im REALLY confused on whats happening, a little help would be useful..
(also the haxe notes,, im REALLY confused.)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

just put an event in the editor, start the song and it crashes when the event is meant to take place.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added mods, added Custom events. and starting working on my OWN mod in it.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by moxie-coder** [comment]
issues with your mods aren’t exactly our problem
