### ISSUE TITLE
Camera breaks when it is under 31 fps

### ISSUE THREAD

**Issue by radishYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#257]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

When you open the game and go to the main menu, it shakes a lot at 30 FPS. From below 30 FPS, it shakes more and more until you can't see anything.
Here's a Video (WARNING: A LOT OF SHAKING): https://drive.google.com/file/d/1vtgl9eLjnpjQWWSi4cYT3U2KFsiR90mN/view?usp=drive_link

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by radishYT** [comment]
> ### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.
> When you open the game and go to the main menu, it shakes a lot at 30 FPS. From below 30 FPS, it shakes more and more until you can't see anything. Here's a Video (WARNING: A LOT OF SHAKING): https://drive.google.com/file/d/1vtgl9eLjnpjQWWSi4cYT3U2KFsiR90mN/view?usp=drive_link
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> None
> ```
> 
> ### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
> ```shell
> None
> ```
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> None
> 
> ### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?
> None
> 
> ### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.
> Yes

**Comment by moxie-coder** [comment]
it's possible to upload the video on github, but I may know a way to fix it since it is frame rated based

**Comment by radishYT** [comment]
If you are wondering at which version it started: "It's been long enough. - 1.19.0"

**Comment by JordanSantiagoYT** [comment]
the engine was updated to support the newest versions of every haxelib library, which means that this is likely a haxe-specific issue and not a js engine-specific issue

**Comment by JordanSantiagoYT** [comment]
yeah nvm this is a js specific issue psych does NOT have that

**Comment by JordanSantiagoYT** [comment]
Found the fix, I will add it in the next commit

**Comment by JordanSantiagoYT** [comment]
nvm bro it ended up making the whole engine worse 💀💀

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/20c2cb2a-745f-4692-8908-83db7aa4800c

**Comment by JordanSantiagoYT** [comment]
ok i was able to fix ChartingState and the character editor but PlayState still has the camera problem

**Comment by JordanSantiagoYT** [comment]
Fixed the options menu camera going crazy at framerates lower than 31, now to fix PlayState

**Comment by radishYT** [comment]
PlayState Camera breaking is still there…

**Comment by JordanSantiagoYT** [comment]
Unfixable for this scenario.

if i fixed it you'd have the camera moving unbearably slowly on higher FPS.

**Comment by JordanSantiagoYT** [comment]
> Fixed the options menu camera going crazy at framerates lower than 31, now to fix PlayState

ok, so if i fix it there's an issue with the Camera moving really really slowly on Higher FPS
