### ISSUE TITLE
Keybind Charting

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#260]
### What feature do you want to get added on the **base** engine?

basically what i mean by this is : you press your note keybinds like Q W O P and it adds the notes for you ( i know how lazy this sounds and how impractical it feels to make but i think this might be a good idea if its possible and im not sure if it already exists )

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> basically what i mean by this is : you press your note keybinds like Q W O P and it adds the notes for you ( i know how lazy this sounds and how impractical it feels to make but i think this might be a good idea if its possible and im not sure if it already exists )
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor and 6K+ support.

It does exist, just enable the Vortex Notes and press keys 1-8

**Comment by moxie-coder** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > basically what i mean by this is : you press your note keybinds like Q W O P and it adds the notes for you ( i know how lazy this sounds and how impractical it feels to make but i think this might be a good idea if its possible and im not sure if it already exists )
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > Stage Editor and 6K+ support.
> 
> It does exist, just enable the Vortex Notes and press keys 1-8

yeah, you’re talking about vortex charting
