### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Joacx21** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#261]
### Describe your problem here.

i'm trying to compile the newest commit, but this is my first time trying to even compile a build, since i normally use releases, i tried and it didn't work, yes, i tried the "quick setup" batch file, didn't work either
![C__Windows_system32_cmd exe 2_04_2024 16_58_01](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153883016/708d1c92-d64d-4b7e-aba4-86c251e3f0ea)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, its just the base one

**Comment by JordanSantiagoYT** [comment]
You're supposed to use hxCodec 2.5.1

**Comment by Joacx21** [comment]
I do have hx codec 2.5.1, so its not that

**Comment by moxie-coder** [comment]
> I do have hx codec 2.5.1, so its not that

`haxelib set hxCodec 3.0.2`

**Comment by Joacx21** [comment]
oh i see the problem now, i think i had 3.0.2 from before and i forgot to uninstall it

**Comment by JordanSantiagoYT** [comment]
haxelib set hxcpp 4.2.1

**Comment by Joacx21** [comment]
i think it has to do with the version of flixel i'm using, since all evidence points towards that

**Comment by Joacx21** [comment]
YES IT FINALLY WORKED
