### ISSUE TITLE
game crashes when i load a song with "show notes off"

### ISSUE THREAD

**Issue by TankmanUtah** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#262]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

the game crashes whenever i load a spam song or just a song in general with show notes on, please help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I dont know

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
can you at least provide error logs?

**Comment by JordanSantiagoYT** [comment]
- make a crash issue
- forget about providing the error logs

gonna need to provide them so we can actually help you
