### ISSUE TITLE
Nonsensical Healthbar (Might add more Ig)

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#263]
### What feature do you want to get added on the **base** engine?

https://gamebanana.com/mods/504179
yeah here
You should put them in secret debug options

**Comment by moxie-coder** [comment]
can just be added via mods so no

**Comment by JordanSantiagoYT** [comment]
Custom health bar options weren't added in 1.23.0, however I do see that you can add them by putting a healthBar.png in mods/images. Also I don't consider this an actual healthbar, so it will not be added anyway.
