### ISSUE TITLE
The Hud options.

### ISSUE THREAD

**Issue by Joacx21** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#264]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

Changing the HUD (Specifically ScoreTxt) to TGT V4 or Dave Engine crashes the game for no reason, also, i originally thought it had to do with compiling issues, until the release happened and i discovered otherwise

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Set ScoreTxt Style to TGT or Dave Engine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, its just the base one

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
will fix soon

**Comment by Joacx21** [comment]
I Discovered the TGT and Dave Engine Time Bars are also a problem since they use the wrong font

**Comment by JordanSantiagoYT** [comment]
This is what happens when you don't double check your code before release







Latest commit should have these fixed
