### ISSUE TITLE
Help me fix this

### ISSUE THREAD

**Issue by Redlmpostor** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#266]
### Describe your problem here.

When I enter a song, it gives me this:

PlayState.hx (Line 7692)
PlayState.hx (Line 1838)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 552)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Installed the JS Engine Mods

**Comment by moxie-coder** [comment]
are you on the latest version? if so update because the lines don’t match up

**Comment by Redlmpostor** [comment]
i updated today but its still not working.

> are you on the latest version? if so update because the lines don’t match up

**Comment by moxie-coder** [comment]
then I need to see the new error message

**Comment by JordanSantiagoYT** [comment]
Pretty sure this is an fcStrings-related crash. Latest release fixes this
