### ISSUE TITLE
the note color texture are default but the note strum texture is from chart

### ISSUE THREAD

**Issue by Miukothoi2011** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#269]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

the proof image is here: 
![noteskin](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/117433468/cb0d44a4-63bc-4a67-9bb5-64b77be98b01)
and i play on newest js engine build.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
Wdym by this? Are you using the "Normal" note colors?

**Comment by JordanSantiagoYT** [comment]
If so, try the latest commit's build like the issue said

**Comment by moxie-coder** [comment]
> If so, try the latest commit's build like the issue said

also there’s note skins for characters too so that might affect that

**Comment by Miuthoi123** [comment]
> Wdym by this? Are you using the "Normal" note colors?

yes

**Comment by Miuthoi123** [comment]
> > If so, try the latest commit's build like the issue said
> 
> also there’s note skins for characters too so that might affect that

i not set noteskin for characters

**Comment by JordanSantiagoYT** [comment]
> > Wdym by this? Are you using the "Normal" note colors?
> 
> yes

I noticed this issue, try the latest commit because it should be fixed: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions/runs/8585549656
