### ISSUE TITLE
Error in rendering songs

### ISSUE THREAD

**Issue by DxrkPxwer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#270]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Js engine always crash after trying to render a song. idk why this is happening (i'm in a rush rn
![imagem_2024-04-07_112906902](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/154340211/70ab1263-6040-4295-a2db-03e44be52653)
)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
PlayState.hx (Line 7837)
RenderingDoneSubState.hx (Line 36)
flixel/FlxGame,hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame,hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)
Uncaught Error. Null Object Reference
Please report this error to the GitHub page https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag
> Crash Handler written
. s Irra-rn
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nuh uh

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there

**Comment by DxrkPxwer** [comment]
> sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there


wait tho i wanna ask smth

**Comment by JordanSantiagoYT** [comment]
> > sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there
> 
> wait tho i wanna ask smth

?

**Comment by DxrkPxwer** [comment]
> > > sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there
> > 
> > 
> > wait tho i wanna ask smth
> 
> ?

when i render songs it goes rlly fast an the 'gamesRender' folder doesn't appears
is this common?

**Comment by JordanSantiagoYT** [comment]
> > > > sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there
> > > 
> > > 
> > > wait tho i wanna ask smth
> > 
> > 
> > ?
> 
> when i render songs it goes rlly fast and the 'gamesRender' folder doesn't appears is this common?

That means you didn't put "ffmpeg.exe" inside the folder where JSEngine.exe is located. If that's the case, Rendering Mode will not start.

**Comment by DxrkPxwer** [comment]
> > > > > sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there
> > > > 
> > > > 
> > > > wait tho i wanna ask smth
> > > 
> > > 
> > > ?
> > 
> > 
> > when i render songs it goes rlly fast and the 'gamesRender' folder doesn't appears is this common?
> 
> That means you didn't put "ffmpeg.exe" inside the folder where JSEngine.exe is located. If that's the case, Rendering Mode will not start.

oh really? lemme check then

**Comment by DxrkPxwer** [comment]
> > > > > > sorry it should be fixed now with the latest commit, hopefully anyways since there wasn’t any safeguards there
> > > > > 
> > > > > 
> > > > > wait tho i wanna ask smth
> > > > 
> > > > 
> > > > ?
> > > 
> > > 
> > > when i render songs it goes rlly fast and the 'gamesRender' folder doesn't appears is this common?
> > 
> > 
> > That means you didn't put "ffmpeg.exe" inside the folder where JSEngine.exe is located. If that's the case, Rendering Mode will not start.
> 
> oh really? lemme check then

it stopped bugging
yippeee i can now render the most memory eating songs with no bugs

**Comment by DxrkPxwer** [comment]
the gameRender folder does not appear

**Comment by JordanSantiagoYT** [comment]
You mean.. you deleted the gameRenders folder??

**Comment by DxrkPxwer** [comment]
I am dumb

> You mean.. you deleted the gameRenders folder??

yes i freaking deleted the gameRender folder. I wonder what's my IQ result (probably negative)

**Comment by JordanSantiagoYT** [comment]
> I am dumb
> 
> > You mean.. you deleted the gameRenders folder??
> 
> yes i freaking deleted the gameRender folder. I wonder what's my IQ result (probably negative)

The readme file in there said that if you deleted the gameRenders folder then ffmpeg won't work... 😭

**Comment by DxrkPxwer** [comment]
i haev an idea

**Comment by DxrkPxwer** [comment]
i will create a folder named gameRenders 
let's see if it works...

**Comment by DxrkPxwer** [comment]
> i will create a folder named gameRenders let's see if it works...

it did work 
however it isn't playing bcs it says that it uses an different type of codification

**Comment by JordanSantiagoYT** [comment]
> > i will create a folder named gameRenders let's see if it works...
> 
> it did work however it isn't playing bcs it says that it uses an different type of codification

oh yeah, you can't play your videos inside Media Player or Windows Movie Player

**Comment by DxrkPxwer** [comment]
> > > i will create a folder named gameRenders let's see if it works...
> > 
> > 
> > it did work however it isn't playing bcs it says that it uses an different type of codification
> 
> oh yeah, you can't play your videos inside Media Player or Windows Movie Player

oh cool
this sucks
can't even play in browser fsr

**Comment by JordanSantiagoYT** [comment]
Your video editor should be able to open them, for me I use capcut

**Comment by DxrkPxwer** [comment]
no way
me 2

**Comment by DxrkPxwer** [comment]
VLC media works tho

> > > > i will create a folder named gameRenders let's see if it works...
> > > 
> > > 
> > > it did work however it isn't playing bcs it says that it uses an different type of codification
> > 
> > 
> > oh yeah, you can't play your videos inside Media Player or Windows Movie Player
> 
> oh cool this sucks can't even play in browser fsr
