### ISSUE TITLE
Game rendering bug

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#271]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when I try to render a song, at the end the screen with information about the render is not shown and the file is damaged, with other songs is no problems

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/156928927/69a00faf-abe1-4d98-84cd-85927e91db80

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
I actually don’t know what causes this, but I do tend to add a library that makes use of ffmpeg that albeit is outdated, I still wanted to try it out

**Comment by JordanSantiagoYT** [comment]
> ### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!
> when I try to render a song, at the end the screen with information about the render is not shown and the file is damaged, with other songs is no problems
> 
>  2024-04-08.18-46-49.mp4 
> ### Command Prompt/Terminal/Crash logs (if existing)
> _No response_
> 
> ### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no
> 
> ### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?
> None
> 
> ### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.
> Yes

that's because you played the song in rendering mode.. in Charting Mode. i haven't added a case scenario for that.

**Comment by JordanSantiagoYT** [comment]
Try latest commit
