### ISSUE TITLE
New song credit data option

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#272]
### What feature do you want to get added on the **base** engine?

There should be a option for what the songcredit theme be like in the data tab on chart editor.

ofc i only have two theme ideas like
- vs nonsense (can be changed a bit if needed)
- vs dave and bambi

im not gonna worry about the "what should NOT be requested", it makes my brain fucking shit

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
just seems like a useless feature
