### ISSUE TITLE
an optimizer?

### ISSUE THREAD

**Issue by cabfile** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#274]
### What feature do you want to get added on the **base** engine?

ive had this idea in mind for some sort of chart optimizing feature. i was thinking of essentially limiting the notes per second, but additionally having every note have a density/worthness/whatever value for nps counters. here's what i managed to do in lua:
```lua
function onCreatePost()
	lasttime = songLength
	for i=getProperty('unspawnNotes.length')-1,0,-1 do
		strumtime = getPropertyFromGroup('unspawnNotes', i, 'strumTime')
		if strumtime == lasttime then
		elseif strumtime > lasttime - 10 + 0.1 then -- limit nps to 100
			removeFromGroup('unspawnNotes',i)
		else
			lasttime = strumtime
		end
	end
end
```
(nothing about the extra values cuz i dont think you can dynamically create properties)
here's also a real-time version that i actually made before that:
```lua
local lastx = 0
local lasty = 0
function onUpdatePost()
	lastx = 0
	lasty = 0
	for i=0, getProperty('notes.length') do
		x = math.floor(getPropertyFromGroup('notes', i, 'x'))
		y = math.floor(getPropertyFromGroup('notes', i, 'y'))
		if lastx == x and lasty == y then
			removeFromGroup('notes',i)
		else
			lastx = x
			lasty = y
		end
	end
end
```
the first one seems to suffer from, for example, making player's notes disappear when the opponent is spamming. and the second one can also have a similar problem in case of a modchart where player's and opponent's notes overlap.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
so this basically nerfs spammy charts but adds some sort of note density/multiplier to make it still true to the og chart (it's kinda like an idea miksel/rei told me about, where if the notes were like 5 pixels apart they'd be put inside a hidden notes array where they would then be hit/played/missed accordingly)
I did try implementing smth like rei's idea but if you missed enough notes you could get it to stop working

This could be a peak optimization

**Comment by JordanSantiagoYT** [comment]
loading times are like over 6x longer when i tried implementing it 😭😭

**Comment by cabfile** [comment]
hmm i suppose optimization shouldnt be done during loading time, but when saving a chart. that might actually make the loading times shorter than they are right now

**Comment by cabfile** [comment]
actually i have two ideas:
- every chart has an additional array with optimized sections and the player can pick if they want to play the real chart or the optimized one
- there will be "save unoptimized" and "save optimized" buttons in the chart editor
