### ISSUE TITLE
shader fix for amd gpus when

### ISSUE THREAD

**Issue by cyklusiguess** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#276]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

title, only wavy bg, chromatic aberration work for me 
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100812875/d5849013-5bfe-416e-a03d-631d58998d7b)
this is also affected on linux

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
when i used initluashader i changed glsl version to 1.20, i hope that fixes it
