### ISSUE TITLE
copy and paste thing

### ISSUE THREAD

**Issue by Akim3000** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#277]
### What feature do you want to get added on the **base** engine?

Hi, Jordan, i’ve got a suggestion for chart editor which is adding these buttons below:
Copy left side
Copy right side
Paste to left side
Paste to right side

With these buttons it could copy sections with different duo placement notes easier to copy if the next section repeats it, it’s a very helpful feature

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
1. You failed the test :3 
2. ..the Duet button exists

**Comment by Akim3000** [comment]
what i meant is if the song has different vocals on the duet and it repeats, those buttons are helpful, cause it only copies each section instead of both, and pasting it to each section yet instead of both

**Comment by moxie-coder** [comment]
you can just copy a section and all that shit, don’t be lazy
