### ISSUE TITLE
can't open the game

### ISSUE THREAD

**Issue by averyhungryOpheebopYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#278]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

so, I got a clean version of the newest updated build of JS Engine... I try opening the .exe file... and.. uh, yeah, that happens.
![Capture d'écran 2024-04-13 202040](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89925435/1f225fc3-e18a-4cca-a10c-04c35bd5f239)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
[lime.utils. Preloader] ERROR: There is no asset library with an ID of "videos"
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I mean.. just tried to get the newest version.. and no I'm not using the source code, I just download the main build.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by averyhungryOpheebopYT** [comment]
oh yeah my bad, forgot to mention, I tried adding the videos folder where the .exe is as well to see if that fixes the issue, but, no, it doesn't.

**Comment by JordanSantiagoYT** [comment]
What version? Also, is there a videos folder in assets?

**Comment by averyhungryOpheebopYT** [comment]
> What version? Also, is there a videos folder in assets?

1. the latest version, v1.23.1
2. yes there is a videos folder in assets

**Comment by JordanSantiagoYT** [comment]
this might sound stupid but did you extract it over an existing js engine folder?

**Comment by averyhungryOpheebopYT** [comment]
uhhhhh
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89925435/3be2be13-342d-4aa5-8d43-2bc784b1e3b7)
..maybe???

**Comment by averyhungryOpheebopYT** [comment]
nah I don't think so

**Comment by JordanSantiagoYT** [comment]
I opened JSE on a clean folder and didn't get that error.

**Comment by cyklusiguess** [comment]
hi so uh averyhungryOpheebopYT is a friend of mine

what's going on here.,.,,f-

**Comment by JordanSantiagoYT** [comment]
> hi so uh averyhungryOpheebopYT is a friend of mine
> 
> what's going on here.,.,,f-

Error: There is NO asset library with an ID of "videos" moment

**Comment by cyklusiguess** [comment]
🔥

**Comment by JordanSantiagoYT** [comment]
The only time I saw something similar was when I compiled VS Impostor (old build) and got that error

**Comment by JordanSantiagoYT** [comment]
which I fixed by setting openfl and lime to earlier versions

**Comment by averyhungryOpheebopYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89925435/40163bc4-c88e-4fbb-b6e0-acec5ff3a074

just to further prove this..

**Comment by cyklusiguess** [comment]
i checked Paths.hx and everything seems to be good

**Comment by JordanSantiagoYT** [comment]
try deleting and re-extracting

**Comment by averyhungryOpheebopYT** [comment]
alright I'll try, I'll tell u if that fixes it

**Comment by cyklusiguess** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100812875/a064148b-bfd8-4072-b40b-1ed3f4058403)
idk if i can show this

**Comment by cyklusiguess** [comment]
this is in my old acc btw

**Comment by JordanSantiagoYT** [comment]
ABANDONING THIS, READ ABOUT ME. 28/02/2024 19:01







dramatic much? 💀

**Comment by JordanSantiagoYT** [comment]
like jeez no need to put it in all caps bro 😭

**Comment by JordanSantiagoYT** [comment]
anyways

**Comment by cyklusiguess** [comment]
> ABANDONING THIS, READ ABOUT ME. 28/02/2024 19:01
> 
> dramatic much? 💀

it wasn't dramatic 🔥

**Comment by JordanSantiagoYT** [comment]
make sure its also extracted normally

**Comment by JordanSantiagoYT** [comment]
> > ABANDONING THIS, READ ABOUT ME. 28/02/2024 19:01
> > dramatic much? 💀
> 
> it wasn't dramatic 🔥

unrelated but people who abandon their discord accs should at the very least delete/deactivate them

**Comment by JordanSantiagoYT** [comment]
not just leave it on there forever

**Comment by averyhungryOpheebopYT** [comment]
> make sure its also extracted normally

I mean, I just select the FNF-JS-Engine.zip, then click on "extract file" and uhh.. yeah

**Comment by averyhungryOpheebopYT** [comment]
I do nuthing else

**Comment by JordanSantiagoYT** [comment]
did it fix ?

**Comment by cyklusiguess** [comment]
> > > ABANDONING THIS, READ ABOUT ME. 28/02/2024 19:01
> > > dramatic much? 💀
> > 
> > 
> > it wasn't dramatic 🔥
> 
> unrelated but people who abandon their discord accs should at the very least delete/deactivate them

about me says i will not delete the acc for archival purposes

**Comment by JordanSantiagoYT** [comment]
> > > > ABANDONING THIS, READ ABOUT ME. 28/02/2024 19:01
> > > > dramatic much? 💀
> > > 
> > > 
> > > it wasn't dramatic 🔥
> > 
> > 
> > unrelated but people who abandon their discord accs should at the very least delete/deactivate them
> 
> about me says i will not delete the acc for archival purposes

keyword
delete/***deactivate***

if they don't want to delete the acc then deactivating it is also ok

**Comment by cyklusiguess** [comment]
why did we switch topics so fast 🔥

**Comment by JordanSantiagoYT** [comment]
> why did we switch topics so fast 🔥

i have no idea 🔥🔥

**Comment by averyhungryOpheebopYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89925435/5dfbaa0c-ee57-4461-a2aa-e7a414a5b41e)
aanndd nope!

**Comment by JordanSantiagoYT** [comment]
idk then

**Comment by cyklusiguess** [comment]
what if you try to open JSEngine.exe in the terminal and see if it prints anything

**Comment by averyhungryOpheebopYT** [comment]
how do that

**Comment by JordanSantiagoYT** [comment]
> what if you try to open JSEngine.exe in the terminal and see if it prints anything

ps theres no code that traces an error when preloading songs

**Comment by cyklusiguess** [comment]
> how do that

./JSEngine.exe i frgort


make sure the terminal is set in js engine's direct roy

**Comment by JordanSantiagoYT** [comment]
> > how do that
> 
> ./JSEngine.exe i frgort
> 
> make sure the terminal is set in js engine's direct roy

wouldn't it be cd (js engine directory) then JSEngine.exe

**Comment by cyklusiguess** [comment]
> > > how do that
> > 
> > 
> > ./JSEngine.exe i frgort
> > make sure the terminal is set in js engine's direct roy
> 
> wouldn't it be cd (js engine directory) then JSEngine.exe

i fucking forgot how to use windows 👍 👍 👍 👍 👍 👍 👍

**Comment by JordanSantiagoYT** [comment]
🔥🔥🔥🔥🔥

**Comment by cyklusiguess** [comment]
i remember i did reboot in cmd and then remembered i was in windows 💀

**Comment by cyklusiguess** [comment]
i wanted to reboot my pc

**Comment by averyhungryOpheebopYT** [comment]
oooooook it gave me a bunch of a text
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89925435/09bc67eb-1e3c-4d5b-a2d8-53073d2a2e41)
("Avery" is just "AveryhungryOpheebop")

**Comment by cyklusiguess** [comment]
damn

it works fine to me in windows

**Comment by JordanSantiagoYT** [comment]
> @JordanSantiagoYT can you check my latest issue too?

ive checked your issue

1. i don't have an amd gpu
2. the shaders were mostly taken from oshit engine, can you check if the shaders are also broken there

**Comment by cyklusiguess** [comment]
> > @JordanSantiagoYT can you check my latest issue too?
> 
> ive checked your issue
> 
> 1. i don't have an amd gpu
> 2. the shaders were mostly taken from oshit engine, can you check if the shaders are also broken there

i checked, they are

oshit engine forgot that amd gpu users exist or something

amd gpus use GLSL 1.10 and the shaders use GLSL 1.20

**Comment by cyklusiguess** [comment]
> how exactly do you know what the shaders are using

... what?

sorry i was confused as fuck 💀 i'm a dumbass

**Comment by JordanSantiagoYT** [comment]
> > how exactly do you know what the shaders are using
> 
> ... what?
> 
> sorry i was confused as fuck 💀 i'm a dumbass

errmmmmm



how exactly do you know if the shaders are using glsl 1.20???

**Comment by cyklusiguess** [comment]
> > > how exactly do you know what the shaders are using
> > 
> > 
> > ... what?
> > sorry i was confused as fuck 💀 i'm a dumbass
> 
> errmmmmm
> 
> how exactly do you know if the shaders are using glsl 1.20???

because in oshit engine it tells you that glsl 1.10 isn't compatible with glsl 1.20 shaders and then crashes

**Comment by cyklusiguess** [comment]
my friend with an nvidia gpu tried it and it worked well without crashes, this is maybe only for amd gpus

**Comment by NAEL2XD** [comment]
check if you have "videos.json" in manifest folder, if you don't have manifest folder that means you'll have to download again from releases

**Comment by moxie-coder** [comment]
from what I can tell, it's an issue with lime's SDL and that you might've put the game folder into a folder where there's special characters which lime does not handle very well, meaning you'll have to move it outside of the folder in question, or your download was corrupted/extraction failed, or you accidentally deleted the videos folder or videos.json

**Comment by moxie-coder** [comment]
and seeing that your pcs language isn't in english, my first assumption might be very correct

**Comment by averyhungryOpheebopYT** [comment]
> and seeing that your pcs language isn't in english, my first assumption might be very correct

holy shirt You were right- it's because my downloads folder is called "Téléchargements", and it probably doesn't support the common "é" in French
thank You so so much!

**Comment by moxie-coder** [comment]
> > and seeing that your pcs language isn't in english, my first assumption might be very correct
> 
> holy shirt You were right- it's because my downloads folder is called "Téléchargements", and it probably doesn't support the common "é" in French thank You so so much!

yeah np
