### ISSUE TITLE
Render mode failure

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#279]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Rendering mode isn't making the video and I have all the files needed for rendering mode.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I tried deleting and reinstalling the ffmpeg files but as soon as the song starts playing, the ffmpeg window closes.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I'm using the built version

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
Did you delete the gameRenders folder inside assets?

**Comment by FazeBWD** [comment]
did JS Engine update to a newer version of video render?

**Comment by moxie-coder** [comment]
> did JS Engine update to a newer version of video render?

have you been keeping up? yeah it has

**Comment by Happyglitchflyer** [comment]
I didn't delete the gameRenders folder and JS engine is updated to the latest version.

**Comment by JordanSantiagoYT** [comment]
> I didn't delete the gameRenders folder and JS engine is updated to the latest version.

Is there a ffmpeg.exe in the same folder as JSEngine.exe?

**Comment by Happyglitchflyer** [comment]
Yes.

**Comment by JordanSantiagoYT** [comment]
yeah idk then. I want video evidence of this happening, this time because every other time you made a crashing error you just said it happened with no crash logs to actually help fix the issue

**Comment by FazeBWD** [comment]
:(

**Comment by Happyglitchflyer** [comment]
https://www.youtube.com/watch?v=Sa8QwLkToNA

**Comment by JordanSantiagoYT** [comment]
I'm looking at your other videos and i can clearly see that rendering mode is working on your engine so i'm closing this as completed.
