### ISSUE TITLE
hiding GF with dialogue crashes the game

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#280]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when I put a dialogue the game crashes

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/5fc7f02e-7dfb-4a6c-9d65-cff940aacaa9)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by daveandbambifan1234** [comment]
yes I am using the latest version

**Comment by JordanSantiagoYT** [comment]
Hey there, did you test this on the latest action build (https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions/runs/8679821735)?
