### ISSUE TITLE
Bigger icons get pushed down

### ISSUE THREAD

**Issue by Joacx21** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#282]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

No, its not a cropping issue, basically, if you use a icon bigger than 300 x 150 or 450 x 150, they will be pushed down, with icons slightly bigger it won't be noticeable, but with a icon that let's say is 600 x 300, it will be easy to see the issue. it doesn't happen in menus but in the song itself its when the bug happens. (i'm using a Manbi phase 2 icon as an example)
![Friday Night Funkin'_ JS Engine - Freeplay Menu 15_04_2024 18_15_47](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153883016/325f1165-35ca-43e8-b796-1e2d2948f85e)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
play a song against a character that has an icon bigger than the usual formats of 300 x 150 or 450 x 150.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by Joacx21** [comment]
![Friday Night Funkin'_ JS Engine - Freeplay Menu 15_04_2024 18_14_47](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153883016/c6171a9d-fe9b-4fc6-8aa0-4d6f70db58fe)
As i said, it's not cropping

**Comment by JordanSantiagoYT** [comment]
What version are you using?

**Comment by JordanSantiagoYT** [comment]
as I looked, and i'm pretty sure that i fixed that in 1.22.0.

**Comment by Joacx21** [comment]
the most recent, its weird

**Comment by JordanSantiagoYT** [comment]
doesn't occur for me.

**Comment by JordanSantiagoYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/4506cdf0-9481-4e29-8214-3324d5737030

**Comment by moxie-coder** [comment]
was already fixed in latest

**Comment by Joacx21** [comment]
it does happen to me on the latest commit. It should be fixed, but it isn't.

**Comment by Joacx21** [comment]
ok i discovered that it doesn't happen in specific bounces, i notice it happens specifically in the gapple and dnb bounces. Also Strident crisis bounce squishes the icon

**Comment by JordanSantiagoYT** [comment]
> ok i discovered that it happens in specific bounces, i notice it happens specifically in the gapple and dnb bounces. Also Strident crisis bounce squishes the icon

I forgot to mention, this is because every other icon bounce type has an updateHitbox function. Gapple and DnB don't have one because if I added them then it wouldn't be accurate to the OG

**Comment by JordanSantiagoYT** [comment]
edit: it's actually just setting the icon offsets. if i did that then the gapple and dnb icon bounces would both be inaccurate.

**Comment by JordanSantiagoYT** [comment]
well.. maybe i could make an additional thing like if the icon width/height is bigger than a normal icon's size

**Comment by JordanSantiagoYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/4734ebc9-885f-4067-8429-10bd01bfcd77

green jumpscare
