### ISSUE TITLE
LOTS OF BROKEN EVENTS

### ISSUE THREAD

**Issue by Joacx21** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#285]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Basically a lot of 0.6.3 events i like to use or have to use due to compatibility issues got broken, the ones included are many cinematic bars events , blammed lights recreations, the badapplelol event, i think it has to do with makeGraphic.
![Friday Night Funkin'_ JS Engine - Test (Freeplay) 17_04_2024 18_04_27](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153883016/db84fff7-252a-48e5-b510-5630fbe7cf62)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
use one of the events i previously mentioned, its just that.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no,

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by Joacx21** [comment]
The screenshot was supposed to be a cinematic bars event but as you see, its broken and the bars are transparent

**Comment by JordanSantiagoYT** [comment]
are you compiling yourself? if so you have to use hxcpp 4.2.1.

**Comment by JordanSantiagoYT** [comment]
and i checked and jse action builds are being compiled using hxcpp 4.2.1.

**Comment by Joacx21** [comment]
oh, ok, thanks for clarifying

**Comment by Joacx21** [comment]
yeah about that, it doesn't let me, it says `Hxcpp` is out of date - please update`

**Comment by JordanSantiagoYT** [comment]
> yeah about that, it doesn't let me, it says `Hxcpp is out of date - please update` and doesn't compile

i think you'll need to also downgrade haxe. I use 4.2.5
