### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#287]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Idk how to explain this

### Command Prompt/Terminal/Crash logs (if existing)

```bash
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 318)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 96)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 57)
StageData.hx (Line 91)
StageData.hx (Line 63)
Song.hx (Line 149)
FreeplayState.hx (Line 571)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 552)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I dont even know LMFAO
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
Your stage JSON is formatted incorrectly.

**Comment by moxie-coder** [comment]
badly formatted stage JSON
