### ISSUE TITLE
Ok what happened to JS Engine 1.24.0

### ISSUE THREAD

**Issue by kipchin1** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#288]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

2 things are broken in JS Engine
![Screenshot 2024-04-19 140827](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/68665586/047737b7-9a0c-47b8-bf7f-8a8884713b4c)
1. the opponents notes show when opponent notes is turned off
![Screenshot 2024-04-19 142046](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/68665586/cacc4832-9f00-4cd7-a2e3-1b2842f64d1a)
2. In Character editor, the crosshair that indicates the camera is missing.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. Turn off Opponent Notes for the first bug
2. Go to Character Editor
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
1. This was an oversight on my end.
2. 
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/a0f33b2b-c86c-45e9-a329-4e4b3d3f8fc2)
The issue is not present for me.

**Comment by kipchin1** [comment]
might be my resolution, mine is 1280x720

**Comment by JordanSantiagoYT** [comment]
uhhh.. i'm also playing on 1280x720?

**Comment by kipchin1** [comment]
well then idk

**Comment by kipchin1** [comment]
I am gonna try the actions build

**Comment by JordanSantiagoYT** [comment]
yeah the action build hasnt fixed that neither

**Comment by kipchin1** [comment]
ok

**Comment by Kipchin1Real** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145127384/14655050-4556-405b-a4f4-e949bddc4d3e)
I downloaded the release build on my computer with a bigger screen.
Same issue.
Can you try downloading the release build? (If you done that, then ok)

**Comment by Kipchin1Real** [comment]
Character Editor btw

**Comment by JordanSantiagoYT** [comment]
huh. it turns out i have the issue on a release build.

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/5f10d5ef-158c-4be5-a6fb-37999cc820f9)
but, on my compiled build it doesn't have the issue?

**Comment by JordanSantiagoYT** [comment]
left = release build, right = my compiled build

**Comment by JordanSantiagoYT** [comment]
it could be because a newer flixel build came out but i'm compiling with 5.6.2

**Comment by JordanSantiagoYT** [comment]
that was exactly the issue :sob:
