### ISSUE TITLE
Vortex editor spam and keybind changing

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#289]
### What feature do you want to get added on the **base** engine?

another probably very hard and impractical to code idea , but basically , you can use more spammable inputs to spam in vortex editor, also add a way to change keybinds for vortex editor

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> another probably very hard and impractical to code idea , but basically , you can use more spammable inputs to spam in vortex editor, also add a way to change keybinds for vortex editor
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

1. stacking notes with vortex editor..
2. ok but realistically what binds would you want to change the vortex thing to

**Comment by Amgsdfyhadfgybi** [comment]
ok so i dindt know that 1 was possible and im not sure how to do it , and the keybind part maybe i would change opponent to q w o p and bf to e r u i

**Comment by JordanSantiagoYT** [comment]
> ok so i dindt know that 1 was possible and im not sure how to do it , and the keybind part maybe i would change opponent to q w o p and bf to e r u i

but.. the w key moves the conductor up in the chart editor, q decreases a note's sustain length, e increases a note's sustain length, and r sets the section back to the start
