### ISSUE TITLE
Note hits not being recognised

### ISSUE THREAD

**Issue by Averagednbfan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#291]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image_2024-04-20_074359508](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/167603785/886d53fa-e7c1-4b7a-a655-c5fb547c1c95)
Whenever I hit a note the score, combo, accuracy, etc. all don't update. Missing notes still correctly subtracts from score & combo, it's only hitting notes that doesn't work. (Bug found in 1.24.1, not present in 1.24.0)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Not a crash
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I tried an unmodified build and the bug still occurred.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by radishYT** [comment]
I have that too, but when you turn on “CommunityGame Botplay Mode” it will fix it.

**Comment by Averagednbfan** [comment]
alr, ill try that rq

**Comment by Averagednbfan** [comment]
ok its all good, i just disabled even less botplay lag in optimizations and it works again (communitygame botplay disables even less lag so thats prob why it worked for you)
thx for the help btw :D
