### ISSUE TITLE
Outdated state for the mods for Js engine

### ISSUE THREAD

**Issue by RedImpostorsSon** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#293]
### What feature do you want to get added on the **base** engine?

I want there to be an outdated message for the Mods for Js engine that is just like the Js engine outdated state because the mods keep updating a lot so fast and I keep having to download it and install it manually and stuff, also I am running out of storage because of this and it takes a while to install them because the files are very big so plz add the outdated state for the mods so it will do it for me and stuff like that.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by JordanSantiagoYT** [comment]
1. You failed the test.
2. ..You're asking for WAY too much, like I can't just do that. Literally no engine has done that before, because doing that is IMPOSSIBLE
3. You can just delete both the mods for js engine zip and the folder that you extracted it to after putting it in js engine/mods??

**Comment by NAEL2XD** [comment]
another label?

**Comment by JordanSantiagoYT** [comment]
> another label?

i'm adding way too many labels :sob:
