### ISSUE TITLE
this is not cool

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#294]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/535d4e7f-94ba-4984-9a6f-0d76e0e88022)
can someone explain this and why is it happening because my computer is now messed up and every JS engine available is now like this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by moxie-coder** [comment]
either you’re just not waiting for it to load, or it’s an issue with your pc that I can’t fix

**Comment by daveandbambifan1234** [comment]
> either you’re just not waiting for it to load, or it’s an issue with your pc that I can’t fix

yeah I was right my computer was having very bad issues now it's time for me to reset my computer sadly
thankfully I have every mod folder archived
