### ISSUE TITLE
Noteskin Bug

### ISSUE THREAD

**Issue by MisuTheKitsune** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#295]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

So there is this bug where JS Engine will use the same noteskin from a previous song

I was Using the song "Bopeebo" To test a different noteskin
![Screenshot 2024-04-23 051104](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/167863491/3a6bd8ba-301a-4cf7-afce-fb008adb307a)

After that the notes are using the same noteskin as seen in the other image
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/167863491/ecd7459a-8aa2-47cc-8171-a49590ffd239)

I checked in Chart Editior and it says there is no custom noteskin added in the chart
I clicked on change notes to see if it fixes it, but it doesn't work
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/167863491/fa51ab66-f594-4939-8f42-8bcb0fbdbc59)

This bug also applies if you change the note style back to "Default" after using a different noteskin other then "Default"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
hey there, i've already detected this issue. please try the latest commit as it should be fixed there!
