### ISSUE TITLE
Custom Song keeps on crashing.

### ISSUE THREAD

**Issue by rbeou** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#296]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Hi! Im Truss Dover. I recently recreated Thearchy but everytime I tried to test out the song it would always crash. So I saved it into freeplay and it still crashes. I do not know how to fix this problem so I decided to ask you.
![image_2024-04-23_221804064](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153855107/7eb90795-7f00-4e38-a7c8-1c22a084aa93)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not.

**Comment by JordanSantiagoYT** [comment]
missing json

**Comment by moxie-coder** [comment]
missing character JSON

**Comment by rbeou** [comment]
I am not missing a character's json.

**Comment by moxie-coder** [comment]
that error says otherwise

**Comment by rbeou** [comment]
?

**Comment by JordanSantiagoYT** [comment]
the end of the crash error says "picospeaker.json"

picospeaker is a character..

**Comment by JordanSantiagoYT** [comment]
however your characters folder might be missing picospeaker.json, check that

**Comment by rbeou** [comment]
Could you send me the "picospeaker.json" thing i can add back?

**Comment by moxie-coder** [comment]
> Could you send me the "picospeaker.json" thing i can add back?

it’s in [here](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/tree/main/assets/preload/characters)

**Comment by rbeou** [comment]
Ok i got the picospeaker.json now where do i put it in?

**Comment by moxie-coder** [comment]
> Ok i got the picospeaker.json now where do i put it in?

in the characters folder

**Comment by moxie-coder** [comment]
> mods character folder or normal character folder?

normal

**Comment by rbeou** [comment]
So i putted it in the assets then characters folder and replaced the normal one that was inside it with the "picospeaker.json" i have so when I went in my song it showed the error again.

**Comment by rbeou** [comment]
what do i do then?
