### ISSUE TITLE
ffmpeg crashing when render song

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#297]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when I trying to render one song the ffmpeg is crashing and the video is cutting in second minute, help, please

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
not enough info given to actually get anywhere with this.

info needed:
crash logs

**Comment by dimafut** [comment]
I don't have crash log, the ffmpeg is crashing, FNF is fine

**Comment by dimafut** [comment]
I have already solve it

**Comment by moxie-coder** [comment]
![hFk9fBi](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/964314bb-111c-4aa5-8077-921f99456c1a)
