### ISSUE TITLE
Bullet Note Texture is not showing

### ISSUE THREAD

**Issue by kipchin1** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#299]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

The texture is not showing.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/68665586/4c8764d9-4e5a-492b-b3ec-cc91e8395db7)
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/68665586/94ceda78-c2e2-406f-ab23-98567aced4f4)
It still works though
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/68665586/0c5870e0-1a29-4c1f-88fa-036beac8187c)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by kipchin1** [comment]
Release build btw

**Comment by kipchin1** [comment]
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is a halfdamage
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet_Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'mechanics/nerf'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'multSpeed', 1); --Change note speed (holy shit 0.6 is good)
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false
-- taken from Fanmade Gunfight Hank mod

dodgeAnimations = {'dodge', 'dodge', 'dodge', 'dodge'}
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		-- bf anim
		characterPlayAnim('boyfriend', 'hurt', true);
		setProperty('boyfriend.specialAnim', true);

		-- dad anim
		characterPlayAnim('dad', animToPlay, true);
		setProperty('dad.specialAnim', true);

		-- health loss | || || |_
		setProperty('health', getProperty('health') - 0.5);
	end
end

local healthDrain = 0;
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		characterPlayAnim('boyfriend', dodgeAnimations[noteData+1], true);
		setProperty('boyfriend.specialAnim', true);
	end
end

**Comment by JordanSantiagoYT** [comment]
Try latest commit, I'm about to publish it now

**Comment by kipchin1** [comment]
ok
