### ISSUE TITLE
making the game still playing while you are opening website or other apps

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#3]
### What feature do you want to get added on the **base** engine?

could you like make this feature because it kinda annoys me if it freeze/auto-pauses (or somthin like that) when i open other apps or browsing on web

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
1. you failed the test
2. this option exists ![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/68c14295-25b8-4c0a-a47d-ab920a59f343)
