### ISSUE TITLE
powerful idea

### ISSUE THREAD

**Issue by Hiho2950** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#30]
### What feature do you want to get added on the **base** engine?

add mod loader from github to play songs without need to install mods just using internet
i know it's hard but not impossible

### To test your sight, and reliability, please select the option of what should be requested.

Useful feature

**Comment by JordanSantiagoYT** [comment]
failed test

also, i won't be able to do this. i know a few mods have done it but this is too complex for me, sorry man

**Comment by Hiho2950** [comment]
> failed test
> 
> also, i won't be able to do this. i know a few mods have done it but this is too complex for me, sorry man

for me i can do it with chart texts scripts but not sprites or sounds

**Comment by Hiho2950** [comment]
> failed test
> 
> also, i won't be able to do this. i know a few mods have done it but this is too complex for me, sorry man

can you try my edited port after finish compile: https://github.com/Hiho2950/FNF-PsychEngine-Modded/actions/runs/6060584883

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/0f85102d-d987-4962-9927-a3938cc7855a)

**Comment by Hiho2950** [comment]
> ![image](https://user-images.githubusercontent.com/61796448/265233012-0f85102d-d987-4962-9927-a3938cc7855a.png)

move sounds folder to mods folder there is a lot of errors cuz of assets folder just move the content of assets and assets/shared to mods folder

**Comment by Hiho2950** [comment]
if you wanna play a normal song like week 7 just copy the content of assets/week7 to mods

**Comment by Hiho2950** [comment]
and i had fix a fps drop or lag strike a little bit

**Comment by JordanSantiagoYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/5d3faa05-abad-4faa-91e4-2d676d3a0bef

it works!! and i also found this issue LOL

**Comment by JordanSantiagoYT** [comment]
oh yeah i also found a potential memory leak, in freeplay if you try exiting the gameplay changer state it just goes back to that state and you can't exit

**Comment by Hiho2950** [comment]
> oh yeah i also found a potential memory leak, in freeplay if you try exiting the gameplay changer state it just goes back to that state and you can't exit

im i got this issue when i had try to fix gameplaychangers on pause menu substate it works on substate but i need to fix on other states

**Comment by Hiho2950** [comment]
> 2023-09-03.05-35-14.mp4 
> it works!! and i also found this issue LOL

about this i didnt find anything that makes this issue
