### ISSUE TITLE
auto save history

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#300]
### What feature do you want to get added on the **base** engine?

can there be a feature where you can see the last auto saves. and load that auto save?

clicked the "save to auto save" button when i was on a different song about to load the unfinished chart (hint, i reopened the game because i dont want the memory cap happening), and i lost all of my fucking progress because of it

that shit took almost 1 and a half hours to chart, and now its gone

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by JordanSantiagoYT** [comment]
thing is, this would bloat your save file size and over time make it take progressively longer to load even your normal save. so No.
