### ISSUE TITLE
all my note are turning into left notes

### ISSUE THREAD

**Issue by Coolman12662726266** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#301]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![Screenshot 2024-04-28 113459](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140287530/ddf07591-51f5-4d0b-b359-72c5c4b2a294)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
none
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
i tried checking the note skins but nothing i got to reopen the game to get rid of it
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i mod with lua

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
you likely screwed up your noteskin’s xml, or your playing with one K modifier, which you can disable by pressing ctrl in freeplay or story mode
