### ISSUE TITLE
Where to find crash/terminal logs (if they exist)?

### ISSUE THREAD

**Issue by Loopedrage** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#302]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

I've been trying to figure out how to get Rendering Mode working, but the game just force closes if I try to enter any song-- regardless of status with it on. Otherwise, everything works just fine. It force closes similarly to how the game crashes if I try to enter the Mods section in the main menu, but I ended up shrugging it off since I could just live without ever needing to look in there. I've been lead to believe that crash logs for the engine _do_ exist, and they should help with identifying the problem-- but I've found no such instance of them. Thanks again

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JordanSantiagoYT** [comment]
(JS Engine directory)/crash

**Comment by Loopedrage** [comment]
There's, uh.... no crash folder. I just updated the engine a few hours ago but I've never come across any folder with that name in the directory

**Comment by moxie-coder** [comment]
we don’t do android no more

**Comment by JordanSantiagoYT** [comment]
probably forgot to tell you but uhh.. rendering mode doesn't work on macOS because of the fact that FFmpeg for macOS doesn't exist

**Comment by moxie-coder** [comment]
oh oops

**Comment by cyklusiguess** [comment]
> probably forgot to tell you but uhh.. rendering mode doesn't work on macOS because of the fact that FFmpeg for macOS doesn't exist
> 
> I can tell that the issue author is a macOS user because uhhh... JSEngine.app

it literally does :skull: 
https://evermeet.cx/ffmpeg/

**Comment by JordanSantiagoYT** [comment]
> > probably forgot to tell you but uhh.. rendering mode doesn't work on macOS because of the fact that FFmpeg for macOS doesn't exist
> > I can tell that the issue author is a macOS user because uhhh... JSEngine.app
> 
> it literally does 💀 https://evermeet.cx/ffmpeg/

are you actually serious, i meant that when you go to the ffmpeg-builds you can't find a macOS build.

**Comment by JordanSantiagoYT** [comment]
also, i'm not able to implement a working reworked render mode for macOS because i ain't a macOS user, so my point still stands

**Comment by JordanSantiagoYT** [comment]
not just that, but i have NOT found enough people that use macOS for this to be a real issue
