### ISSUE TITLE
Add support for other video formats for Rendering Mode

### ISSUE THREAD

**Issue by cabfile** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#303]
### What feature do you want to get added on the **base** engine?

FFmpeg supports many other video formats, not just mp4. Although, not all encoders are compatible with, lets say, webm.
Oh and can you add the `mpeg2video` encoder to mp4 please

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> FFmpeg supports many other video formats, not just mp4. Although, not all encoders are compatible with, lets say, webm. Oh and can you add the `mpeg2video` encoder to mp4 please
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor and 6K+ support.

ive actually tried other encoders, and any ones other than the options given to you in 1.25.0 i tried just.. don't work because they export glitchy videos

**Comment by JordanSantiagoYT** [comment]
also, i prefer using MP4 only because it's the most compatible.
