### ISSUE TITLE
deleting very much sections in one click

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#304]
### What feature do you want to get added on the **base** engine?

I think that this feature will economy lot of time, and here how I imagine it:
Delete sections from (number) to (number)
I hope that this function will be added in the engine ;)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
i don't know anyone that would use it though

**Comment by moxie-coder** [comment]
> i don't know anyone that would use it though

yeah just seems pointless

**Comment by JordanSantiagoYT** [comment]
so For now this will not be planned.
