### ISSUE TITLE
The funni spam feature from OS engine.

### ISSUE THREAD

**Issue by SuperRyan0308** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#305]
### What feature do you want to get added on the **base** engine?

I feel like to make spam even easier then it already is, is by adding the feature from OS engine that lets you make spam with holding RMB with shift key. the dave and bambi fans will probably like this.

### To test your sight, and reliability, please select the option of what should NOT be requested.

6K and stage editor

**Comment by moxie-coder** [comment]
already implemented if I remember correctly

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> I feel like to make spam even easier then it already is, is by adding the feature from OS engine that lets you make spam with holding RMB with shift key. the dave and bambi fans will probably like this.
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 6K and stage editor

press c while in the chart editor

**Comment by SuperRyan0308** [comment]
ok thanks
