### ISSUE TITLE
Can't open video renders

### ISSUE THREAD

**Issue by u0-a63** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#306]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

When I render a song, I can't play the rendered video because Windows complains about the codec being 'unsupported'.

Is this a problem with FFmpeg or JS Engine?

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
On Windows 11 23H2, the rendered video just won't play, it complains about an incompatible codec.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just wanted to render a song but it won't let me play the rendered video. I am not trying to make a mod.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by u0-a63** [comment]
Sorry if I put this in the wrong place, but it's annoying as f**k.

**Comment by JordanSantiagoYT** [comment]
that's intentional. just like zenith, you can't open your rendered videos using a normal video player. use smth like vlc, or put it into a video editor and it should work just fine

**Comment by moxie-coder** [comment]
> that's intentional. just like zenith, you can't open your rendered videos using a normal video player. use smth like vlc, or put it into a video editor and it should work just fine

yeah probably due to how ffmpeg encodes the videos though, some video players may not support the rendered videos or some shit like that
