### ISSUE TITLE
the images explains everything

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#309]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/18514f12-46e6-4491-8158-00f700a3536f)
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/13be4134-8282-4567-95ba-a4f4aa1e0d33)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
jgh
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
ghjfghj
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
yeah, idk how to fix this 🤷‍♂️

**Comment by Joacx21** [comment]
yeah, it happens to me too, it doesn't annoy me since it doesn't get in the way of charting

**Comment by Stefan2008Git** [comment]
Oh no, a blud just fucked up the custom note types system 💀. How sadly for JS Engine users

**Comment by daveandbambifan1234** [comment]
#evryone it's the hurt notes skin
