### ISSUE TITLE
Character preview

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#31]
### What feature do you want to get added on the **base** engine?

This feature will add a character preview of bf variants skin or even opponents that can be play-able just like from the dave and bambi, whatever song you'd choose it will take you to the character preview!

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by JordanSantiagoYT** [comment]
i mean you can technically do that in the character editor? just press through the animations
