### ISSUE TITLE
all custom stages won't load

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#311]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when I try to put some custom stage (from other engine or mine) the stage is just black, also I checked stage in Manny Edition and the stage works wery well
![Friday Night Funkin'_ JS Engine - end-of-the-world (Story Mode) 07 05 2024 13_17_20](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/156928927/5f8f9c01-d87b-4995-862b-a7851768467d)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by dimafut** [comment]
also, here is the code of stage: 
function onCreate()
	-- background shit
	makeLuaSprite('yey', 'yey', 0, 0);
	setScrollFactor('yey', 1, 1);
	addGlitchEffect('yey', 1, 1);
        scaleObject('yey', 2.5, 2.5)
	

	addLuaSprite('yey', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

**Comment by JordanSantiagoYT** [comment]
i can see an addGlitchEffect in your script

do you have the "shaders" option turned on?

**Comment by dimafut** [comment]
it was turned off, but now I turned it on an I can see the stage, thank you!
