### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by OrcaTheBeginner** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#312]
# [MacOS 64-bit application](https://youtu.be/GbD7BxRCtGQ?si=ly34FtJXGV0ma2JG)

**Comment by JordanSantiagoYT** [comment]
i don't use macos.. 😭

**Comment by moxie-coder** [comment]
neither do I, I have WSL but I can’t do testing with it, only compiling
