### ISSUE TITLE
Greenscreen gifs into png spritesheets

### ISSUE THREAD

**Issue by ThatOneFLMGuy** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#314]
### What is your question?

how do you turn gifs into spritesheets while getting rid of the greenscreen there? Do i just do it manually or is there something I can do to make it go away and have a spritesheet that does not have a greenscreen on it? (Example of the gifs im talking about in the Google Drive NotFNF Trauma Edition TOFLMG True Form Concept Sprites link: https://drive.google.com/drive/folders/1_HUu6qbUa1VOV_8J2TFSmDNWyVL1uMfc folder is by JJ1982 not me)
(Github wont let me put images or gifs in here)

**Comment by ThatOneFLMGuy** [comment]
lmao coincidence its number 314 as in 3.14159 Pi

**Comment by moxie-coder** [comment]
the greenscreen can be removed with an image editor, and you can use this to make spritesheets https://github.com/UncertainProd/FnF-Spritesheet-and-XML-Maker
