### ISSUE TITLE
A different way of loading JSON files.

### ISSUE THREAD

**Issue by Happyglitchflyer** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#316]
### What feature do you want to get added on the **base** engine?

A different way to save and load files. Maybe it could save a chart (16.8 million / notes in the chart) times and it could load these charts depending on the number. The original chart won't have a number while the other parts will and the order of being loaded depends on the number in the name.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
saving a chart like that would be good however idek how to do it, and barely any charts will use it except for ones that go past 16m.

**Comment by moxie-coder** [comment]
> saving a chart like that would be good however idek how to do it, and barely any charts will use it except for ones that go past 16m.

this just seems ridiculous to do

**Comment by moxie-coder** [comment]
maybe we can find a better solution to this, because this would just make loading times more longer, so this isn’t an efficient solution
