### ISSUE TITLE
Crash when i use video lua script

### ISSUE THREAD

**Issue by Moltrix101** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#317]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

i got a video under HUD script from https://gamebanana.com/tools/12156 , and after putting the script with the video name WITHOUT typos,it crashes with the crash log below popping up, and the video i used was the darnell cutscene from weekend 1, its a port to js engine, heres the script below too if it helps with bugfixing or smthn 

-- change the video name here	->  var filepath = Paths.video('name');	
--												     		   ^^^^^^^
-- or put the video whit name " name" on videos folder

function onCreate()

makeLuaSprite('black', '', 0, 0);

makeGraphic('black', 2500, 2500, '000000');

--setScrollFactor('black', 0, 0);
setObjectCamera('black', 'game');

setObjectCamera('videoSprite', 'game');

setObjectOrder('black', 99999);

screenCenter('black');

addLuaSprite('black', true);

	setProperty('skipCountdown', true)

	makeLuaSprite('videoSprite','',0,0)
	addLuaSprite('videoSprite')

	addHaxeLibrary('MP4Handler','vlc')
	addHaxeLibrary('Event','openfl.events')

	runHaxeCode([[
		var filepath = Paths.video('name');		
		var video = new MP4Handler();
		video.playVideo(filepath);
		video.visible = false;
		setVar('video',video);
		FlxG.stage.removeEventListener('enterFrame', video.update); 
	]])
end

function onUpdatePost()
	triggerEvent('Camera Follow Pos', '640', '360')

	runHaxeCode([[
		var video = getVar('video');
		game.getLuaObject('videoSprite').loadGraphic(video.bitmapData);
		video.volume = FlxG.sound.volume + 100;	
		if(game.paused)video.pause();
	]])
end

function onResume()
	runHaxeCode([[
		var video = getVar('video');
		video.resume();
	]])
end
function onCreatePost()
	getObjectOrder('videoSprite')
	setObjectOrder('videoSprite', 100000)
end

function onUpdate()
	triggerEvent('Camera Follow Pos', '640', '360')
end

### Command Prompt/Terminal/Crash logs (if existing)

```bash
vlc/MP4Handler.hx (Line 81)
vlc/bitmap/VlcBitmap.hx (Line 480)
vlc/bitmap/VlcBitmap.hx (Line 246)
vlc/bitmap/VlcBitmap.hx (Line 331)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: VLC caught an error!
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing source code related, just ports of mods (weekend 1, whitty, and roadkill)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by moxie-coder** [comment]
I feel like the changes I did broke it, mb I can’t revert rn
@JordanSantiagoYT you can revert it btw I think I broke lua scripts 😭

**Comment by JordanSantiagoYT** [comment]
also, i don't use that video sprite script, i use this one

```
--bbpanzu
--[[

you could call it like

addLuaScript('videoSprite')

and it'll pop up right then and there




]]

function onCreate()

	makeLuaSprite('videoSprite','',-100,0)
	addLuaSprite('videoSprite')
    setProperty('gfGroup.visible', false);
	-- makes the video sprite

	addHaxeLibrary('MP4Handler','vlc')
	addHaxeLibrary('Event','openfl.events')
	--add needed haxe libraries for video and openfl events

	--run the main haxe code
	runHaxeCode([[

		var filepath = Paths.video('1');
		//get the video path
		
		var video = new MP4Handler();
		//create the video object

		video.playVideo(filepath);
		//play the video file

		video.visible = false;
		//make the video object overlay invisible

		setVar('video',video);
		//set global variable

		FlxG.stage.removeEventListener('enterFrame', video.update); 
		//removes the native update event the video has (disables skipping pressing enter)
	]])


end

function onUpdatePost()


	--run the main haxe code
	runHaxeCode([[
		var video = getVar('video');
		//get video object variable

		game.getLuaObject('videoSprite').loadGraphic(video.bitmapData);
		//set video sprite's graphic as the video's bitmap data

		video.volume = 0 + 0;
		//set video volume as the game's volume (plus 0.4 idk psych has that for some reason)
		
		if(game.paused)video.pause();
		//pause video if the game is paused

	]])

end


function onResume()

	--run the main haxe code
	runHaxeCode([[
		var video = getVar('video');
		//get video object variable

		video.resume();
		//resume video when game is resumed
	]])

end
```
