### ISSUE TITLE
Song crashes when I try to go in the chart editor

### ISSUE THREAD

**Issue by rbeou** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#318]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

So I was trying to test out my custom character I made so I went in my song and when I clicked 7 key on it it crashed.
![error](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153855107/fea0a79b-911b-4843-9924-2476fb3a6a13)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not im pretty sure

**Comment by JordanSantiagoYT** [comment]
you're missing a json named "thearchy-reboundway-hard"

**Comment by moxie-coder** [comment]
> you're missing a json named "thearchy-reboundway-hard"

👆
