### ISSUE TITLE
Auto note remover for the chart editor.

### ISSUE THREAD

**Issue by SuperRyan0308** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#319]
### What feature do you want to get added on the **base** engine?

Are you tired of tapping the notes constantly after accidentally spawned a huge set of spam notes? well this feature would be that in the chart editor if you press this button, you can hover your mouse over the notes to clear them easily.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
Press CTRL+C in the chart editor, then hover over a note :)

**Comment by moxie-coder** [comment]
already a feature
