### ISSUE TITLE
adding the ability to have multiplayer on one screen

### ISSUE THREAD

**Issue by fnfporterhi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#32]
### What feature do you want to get added on the **base** engine?

basically there’s this one mod i saw for vanilla FNF that allows 2 people on 1 keyboard to play opponent side and player side for the 2.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by fnfporterhi** [comment]
also big fan btw

**Comment by NAEL2XD** [comment]
There's that 1 Lua that makes it playable for 2 players but idk what the link js

**Comment by Hiho2950** [comment]
> There's that 1 Lua that makes it playable for 2 players but idk what the link is

yep there is

**Comment by fnfporterhi** [comment]
i knew that i meant like officially added as an option

**Comment by Hiho2950** [comment]
for me it's something hard a little

**Comment by Hiho2950** [comment]
unless if we take the lua script and convert it to a hx code on source code

**Comment by Hiho2950** [comment]
i will try to do it on mine
