### ISSUE TITLE
why does my icon not Bop on my computer

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#321]
### What is your question?

that's all I have to say

**Comment by moxie-coder** [comment]
what do you mean, this doesn’t say much

**Comment by JordanSantiagoYT** [comment]
> ### What is your question?
> that's all I have to say

it is possible that you have your Icon Bounce set to "None", or you don't have your icon bop trigger option set to "Every Beat" or "Every Note Hit"
