### ISSUE TITLE
Copy to left section, Copy to right section

### ISSUE THREAD

**Issue by SuperRyan0308** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#323]
### What feature do you want to get added on the **base** engine?

So lately I have been trying to chart Omission but I think a good feature would be to add a feature that lets you copy Left or right section so you don't have to copy a duel section and clear the left or right section.

### To test your sight, and reliability, please select the option of what should NOT be requested.

6K+ and stage editor

**Comment by moxie-coder** [comment]
no

**Comment by SuperRyan0308** [comment]
alr nvm
