### ISSUE TITLE
Character editor crashing

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#325]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

[I FINALLY CAUGHT IT!](https://drive.google.com/file/d/1vfWYiJcCM14c5gxLw82ipNX9_rPIjmnQ/view?usp=sharing) (skip to like 1 minute in) I've been having this problem since psych engine & I don't know what causes it or how to fix it. It doesn't just happen with changing the fps either, it most commonly happens when I change and animation or xml name

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Just mess around in the character editor for long enough. Idk how to perfectly recreate it
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Mostly events but nothing major

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
you could've just uploaded the video on here

**Comment by moxie-coder** [comment]
nvm I'll do it for you

**Comment by moxie-coder** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/e160ad34-7e42-4b95-beb8-f9a489cf9990)
hm

**Comment by moxie-coder** [comment]
so from what I'm seeing, it's due to an invalid animation or name you added that's not in the xml

**Comment by SMWpalkia** [comment]
What exactlt do you mean by invalid animation or name that's not in the xml? I've had multiple instances where I entered the wrong name from the xml but it doesn't crash
