### ISSUE TITLE
shader addition

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#326]
### What feature do you want to get added on the **base** engine?

that one jitter glitch like in shredder from dave and bambi
i dont know what else to say
i know where the shader is though

its in [this](https://github.com/Lokitot/VsDaveArchived/blob/main/source/Shaders.hx) 

its on line 172 and 420

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by JordanSantiagoYT** [comment]
peak

also, You failed the test.

**Comment by StinkTheStinker** [comment]
i wasnt gonna try filling that out, getting tired of it
