### ISSUE TITLE
BUG: Noteskin is retained in chart editor from previous song if Shift + Enter into song

### ISSUE THREAD

**Issue by moxie-coder** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#327]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/37b78018-1b1d-41e8-a7fb-b06a44454817)

In the latest commit, shift entering from a song with a different noteskin (week 6 demonstrated) will keep it and make the notes invisible apart from sustains

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
erm actually, if you enter a week 6 song and go to the chart editor it duplicates the behavior.

this is because normal note loading works differently from the week 6 note loading
