### ISSUE TITLE
i need help on the source coding

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#328]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/18a9d423-e901-480b-8027-c8629201654b)
how do i fix this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

source coding

**Comment by JordanSantiagoYT** [comment]
i dunno, i never got that issue

**Comment by StinkTheStinker** [comment]
forgot to tell you that the source code is on 1.19
you already know why im using 1.19

**Comment by moxie-coder** [comment]
your visual studio MSVC compiler got corrupted during install

**Comment by StinkTheStinker** [comment]
no fucking way

what the cmd for it again?

**Comment by StinkTheStinker** [comment]
unless if its an app issue

**Comment by StinkTheStinker** [comment]
now this is popping up
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/0a9d8760-9f69-4369-b5f6-2d4f026b06f9)

**Comment by StinkTheStinker** [comment]
nothing??

**Comment by JordanSantiagoYT** [comment]
i never had that issue, so i can't do much here

**Comment by StinkTheStinker** [comment]
FUCK

**Comment by StinkTheStinker** [comment]
even this is not getting any answers
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/aee95954-d61e-4802-9fad-211f879dacd0)
![waaaaaaaaaaaaa](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/994743be-382e-4017-a659-48cfedd94fd9)

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/bb25e78c-d532-4fe6-8943-cfff5c709761)
uh

**Comment by TumoPlayz** [comment]
you might not wanna use powershell for this kinda stuff

**Comment by moxie-coder** [comment]
yeah just install the program normally instead of using curl

**Comment by StinkTheStinker** [comment]
> yeah just install the program normally instead of using curl

heres the question, how
im usually stupid

**Comment by TumoPlayz** [comment]
> > yeah just install the program normally instead of using curl
> 
> heres the question, how
> im usually stupid

😐😐😐You just run the setup exe, but not using curl.

**Comment by StinkTheStinker** [comment]
> > > yeah just install the program normally instead of using curl
> > 
> > 
> > heres the question, how
> > im usually stupid
> 
> 😐😐😐You just run the setup exe, but not using curl.

it opens on default

**Comment by StinkTheStinker** [comment]
> > > > yeah just install the program normally instead of using curl
> > > 
> > > 
> > > heres the question, how
> > > im usually stupid
> > 
> > 
> > 😐😐😐You just run the setup exe, but not using curl.
> 
> it opens on default

by power shell

**Comment by StinkTheStinker** [comment]
figured it out, now getting this problem
![image](https://github.com/user-attachments/assets/bf38002b-ddbe-4b08-ab0d-ca401bd7dd40)
idk what i did, i only changed the main menu shit, not freeplay

**Comment by StinkTheStinker** [comment]
flixel/effects/FlxFlicker.hx (Line 171)
flixel/util/FlxTimer.hx (Line 230)
flixel/util/FlxTimer.hx (Line 320)
flixel/FlxGame.hx (Line 748)
flixel/FlxGame.hx (Line 680)
flixel/FlxGame.hx (Line 553)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
Crash dump saved in crash/JSEngine_2024-08-10_00'30'29.log

theres the error thingy

**Comment by StinkTheStinker** [comment]
figured it out

**Comment by moxie-coder** [comment]
okay great
