### ISSUE TITLE
Rainbow Eyesore

### ISSUE THREAD

**Issue by rbeou** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#329]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

how do I use rainbow eyesore

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not

**Comment by JordanSantiagoYT** [comment]
it works exactly like how it's used in strident crisis.

1. add a rainbow eyesore event
value 1 is the step that it will stop at. so 128 will stop it at curStep 128
value 2 is the speed of the eyesore.

PS: if you turn off Flashing Lights, the shader will not toggle on when the event is used

**Comment by moxie-coder** [comment]
yeah it isn’t that hard to use

**Comment by rbeou** [comment]
where can I find the step?

**Comment by rbeou** [comment]
oh nvm sorry i forgot to enable flashing lights
