### ISSUE TITLE
ability for people to have no backgrounds and no characters 

### ISSUE THREAD

**Issue by fnfporterhi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#33]
### What feature do you want to get added on the **base** engine?

basically optimization mode on kade engine. i thought it’d be cool to add it to where like no characters, no background, only health bar, accuracy bar, and notes.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by NAEL2XD** [comment]
There's one in optimizations > chars & bg

**Comment by Hiho2950** [comment]
just disable chars and bg on optimization options but i will crash game at line where gfghost copy scale from gf

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/6cbb37db-ad9e-4442-b445-0bf940b2b767)
already exists

**Comment by fnfporterhi** [comment]
oh sorry
