### ISSUE TITLE
why notes look like this?

### ISSUE THREAD

**Issue by Spectricium** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#331]
### What is your question?

so i updated from 1.24.2 to 1.25.0 and i found a weird visual glitch that looks like this
![bug](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/113564281/0409359b-2e5d-4754-976c-98345da7254a)
its not a big problem but i just wanted to report this

**Comment by JordanSantiagoYT** [comment]
that's because i switched from sorting the notes every frame to sorting every beat, like in normal psych. if you want the sorting every frame wait until 1.26.0 (tomorrow) or use rendering mode

**Comment by moxie-coder** [comment]
> that's because i switched from sorting the notes every frame to sorting every beat, like in normal psych. if you want the sorting every frame (aka. fixed note sorting) wait until 1.26.0 (tomorrow) or use rendering mode

👆
