### ISSUE TITLE
Brginning skip.

### ISSUE THREAD

**Issue by darklegion2605** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#334]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Every time I press enter during the intro screen before the starting screen where I press enter to begin, it shows this error messsage:
"Invalid fiield:timestamp" #332 
![Screenshot 2024-05-18 192250](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/163363593/497bf232-87a5-4f1f-8593-8ccacc537993)

Maybe retry checking the timestamps & matching them with the configured field or something to broadcast the flash & skip to the "PRESS ENTER TO BEGIN" screen...

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just reported the issue.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
but.. when you press ENTER, it does FlxG.switchState(TitleState.new);

**Comment by darklegion2605** [comment]
now i cant even go to the main menu

![Screenshot 2024-05-18 192250](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/163363593/20d8416b-c16f-4904-a1f9-1d5bf9f5ef2f)

**Comment by darklegion2605** [comment]
the only thing i can do now is click, any key i press and it says i cant go to main menu


https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/163363593/ebda75f0-507d-48a5-a2fc-532e80d796e6


![Screenshot 2024-05-19 185752](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/163363593/fefc1aa1-97f3-46c1-ba2f-65ea9fe3319a)

**Comment by darklegion2605** [comment]
maybe it has something to do with the timming of the intro screens?

**Comment by JordanSantiagoYT** [comment]
there could be a slight possibility that your installation is corrupted. try reinstalling jse

**Comment by darklegion2605** [comment]
i already did, that video was my 2nd attempt for my 1-2 comment, the photo is from my 3rd trying to see what happens if i wait for the last intro text state

**Comment by darklegion2605** [comment]
im gonna try one more time without using win rar

**Comment by darklegion2605** [comment]
didnt work

**Comment by JordanSantiagoYT** [comment]
Yeah idk. i don't get the error so i can't help you.

**Comment by darklegion2605** [comment]
ill just wait for next version then (ill have my pc updated by then)

**Comment by darklegion2605** [comment]
congratulations, you fixed the error i was having, it now works and i can use your engine 100% again
