### ISSUE TITLE
Wrong Audio.

### ISSUE THREAD

**Issue by BryceLegendzPlayz** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#337]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

I'm testing a spamchart song called "botspam." I copied the folders where the songs exist (I found 2), renamed them, and in the one on the "songs" folder, I replaced the "Voices" and 'Inst" Ogg files with my own. I made sure they were the right name, and I made sure they were an Ogg. In the one in the "data" folder, I renamed the JSON files to my song name. (e.g. botspam-hard.json) I even looked into them, and I replaced `"song":"Stress"` to `"song":"Botspam"`. But when I play it in the editor, it only plays the instrumental of Stress. And for some reason, the screen zooms in at 9 seconds.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
There are no crash logs.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
that's likely because you loaded the stress song first, and either you didn't press reload audio after changing the song name to "Botspam" or you pressed reload audio but the engine didn't find the song files
