### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by uhhhhhhhhhfffa** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#338]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

PlayState.hx (Line 7422)
PlayState.hx (Line 6245)
PlayState.hx (Line 5772)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
from what i checked, you likely tried adding custom rating quotes but you forgot to have at least one for 100% accuracy

**Comment by uhhhhhhhhhfffa** [comment]
ok
