### ISSUE TITLE
crash!!!

### ISSUE THREAD

**Issue by sigma993240** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#339]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

im playing a high effort mod and it just crashed!
heres a link:https://gamebanana.com/mods/502370

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Paths.hx (Line 159)
NoteSplash.hx (Line 111)
NoteSplash.hx (Line 68)
NoteSplash.hx (Line 44)
PlayState.hx (Line 1331)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 552)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt add anything

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
i should add.. if you're playing a mod which uses custom note splashes, you'll need to put the note splashes in a folder called 'noteSplashes'.

i'm saying this because if you don't do it the game basically tries looking for "noteSplashes/Splashes/(your note splash)". it doesn't find anything so it crashes.

**Comment by JordanSantiagoYT** [comment]
also, don't put 0.7.3 mods in 0.6.3 as.. they aren't going to work fully.

**Comment by moxie-coder** [comment]
yeah 0.7 mods are definitely not entirely backwards compatible with 0.6.3
