### ISSUE TITLE
What do i want

### ISSUE THREAD

**Issue by XenonHedgehog** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#341]
### What feature do you want to get added on the **base** engine?

BPM Detector (Chart Editor)
I wanna use that option cuz i wanna make charts of songs that doesn't have BPM in it/description

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by XenonHedgehog** [comment]
Please close this cuz i need to change it

**Comment by moxie-coder** [comment]
there’s a close button moron

**Comment by XenonHedgehog** [comment]
Oh sorry

**Comment by moxie-coder** [comment]
also you can just edit the issue too

**Comment by moxie-coder** [comment]
btw bpm detection in flixel is possible, but I need to find an library and make bindings to that library to make it even remotely possible, and I'm lazy so I don't wanna bother with that

**Comment by JordanSantiagoYT** [comment]
BPM Detector (Chart Editor)
I wanna use that option cuz so i can make charts of songs that doesn't have BPM in it/description

Unneeded.

Hitbox display (not FNF Android's hitbox buttons)
Do you want to play FNF with hitboxes of hitting notes?
Just lets you see the hitbox of notes, not needed.

Character-Specific pause music (Animation Editor)
Do you want your bambi to have his pause music?
Can be made with lua, so no.

Mario (mario)
Just
Just mario

..No
