### ISSUE TITLE
Character Editor

### ISSUE THREAD

**Issue by rbeou** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#343]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Every time I go in character editor and try to rename something it doesn't select it. I can only click buttons thats it. How do I fix?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
you have to reset the camera zoom to normal to use the rename things first

**Comment by JordanSantiagoYT** [comment]
i tried fixing it but the fix didn't work so

**Comment by rbeou** [comment]
Ok thank you but maybe use the psych engine character editor and add the misc there. Maybe it will work. Thanks Jordan!

**Comment by JordanSantiagoYT** [comment]
> Ok thank you but maybe use the psych engine character editor and add the misc there. Maybe it will work. Thanks Jordan!

..this is a fork of psych engine, which uses the psych engine character editor 💀

**Comment by rbeou** [comment]
> > Ok thank you but maybe use the psych engine character editor and add the misc there. Maybe it will work. Thanks Jordan!
> 
> ..this is a fork of psych engine, which uses the psych engine character editor 💀

i just realised
