### ISSUE TITLE
Old rendering mode

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#346]
### What feature do you want to get added on the **base** engine?

i just hate when if i use ffmpeg to render on new rendering mode, ffmpeg just quits and closes itself, i just want the old rendering mode to be back!!!!

why i want old rendering mode to be back:
it's because ffmpeg + engine = a bigathon of cpu and ram, which also means ffmpeg closes itself

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
okay, but..

with the old memory mode it's basically a ram eater + cpu destroyer for low end pcs.

**Comment by moxie-coder** [comment]
yeah so there’s no good reason to add it back really

**Comment by NAEL2XD** [comment]
?? Why not add it as a separate option?

**Comment by JordanSantiagoYT** [comment]
> ?? Why not add it as a separate option?

ps: check latest commit
