### ISSUE TITLE
missing libraries 

### ISSUE THREAD

**Issue by colejrlol** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#347]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when i execute the linux file it says:error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

### Are you modding a build from source or with Lua?

no  i dident mod anything

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no i dident

**Comment by JordanSantiagoYT** [comment]
yeah, i don't use linux so i can't help you with that. i do have another friend who does use linux though, he might be able to help you

**Comment by JordanSantiagoYT** [comment]
@cyklusiguess

**Comment by Stefan2008Git** [comment]
> yeah, i don't use linux so i can't help you with that. i do have another friend who does use linux though, he might be able to help you

My modified Psych fork on Linux is working perfectly fine. Old linc_luajit is outdated and it will throw many errors on Linux build target, so i am recommending to switch on latest linc_luajit one from PE 0.7+
