### ISSUE TITLE
trying to port a character

### ISSUE THREAD

**Issue by nikitabaev71** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#348]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

im trying to port a character from another mod but it wont let me to

### Command Prompt/Terminal/Crash logs (if existing)

```bash
flixel/graphics/title/FlxDrawQuadsltem.hx (Line 119)
flixel/FlxCamera.hx (Line 772)
flixel/FlxGame.hx (Line 873)
flixel/FlxGame.hx (Line 565)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)
Null Object Reference
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. Open JS Engine
2. Open Character Editor (i think the name is like that)
3. Open up the character that you ported
4. Done! An error!
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, im not even modding

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
your character graphic is missing or not in the right path, this is from flixel attempting to add an shader to an nonexistent/null graphic

**Comment by nikitabaev71** [comment]
i have the png xml and json on the right place and theyre not null

**Comment by JordanSantiagoYT** [comment]
are you sure that you don't get a haxeflixel logo when doing that?

**Comment by nikitabaev71** [comment]
i do get it, i forgot to say one step, an haxeflixel logog pops up, click reload image.

**Comment by JordanSantiagoYT** [comment]
you're pointing to a nonexistent character image file then
