### ISSUE TITLE
Video Renderer

### ISSUE THREAD

**Issue by rbeou** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#349]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

yes ik its me again but hwo do you use Video render in game rendering? I have ffmpeg but every time i try to play a song to record it. It always gets rid of the songs sound and it doesnt actually convert it into .mp4. it doesnt even record the song!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
you have to put your ffmpeg.exe in the same folder that JSEngine.exe is located in.

getting rid of the songs' sound is intentional, when the video is playing obviously it won't have any audio

**Comment by rbeou** [comment]
![error](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153855107/cee05f4e-ee27-4490-a3a0-db7c79420e9a)
I did it but whenever i go into a song with video renderer on it shows this error.

**Comment by rbeou** [comment]
how do i fix?

**Comment by JordanSantiagoYT** [comment]
idk man, i don't get that error so i can't help you

**Comment by rbeou** [comment]
dang

**Comment by Stefan2008Git** [comment]
> idk man, i don't get that error so i can't help you

Simple answer:
Missing the dll file

**Comment by rbeou** [comment]
Ok so basically I renderered a song then I go in cmd and run the command 'ffmpeg -r 60 -i ./RAGE/%07d.jpg  rage.mp4' It does it but then this message comes up 
![error](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153855107/75c1bb6d-6a7c-4989-991d-9ade64cffc6a)

**Comment by JordanSantiagoYT** [comment]
..when formatting to a song path the game doesn't put capital letters

**Comment by rbeou** [comment]
what i dont understand. I made the name (RAGE) lowercased but it still didnt work.

**Comment by rbeou** [comment]
Ok I finally fixed the problem! and i blame myself for this.. I forgot to add ffmpeg to same folder as js engine. The only thing I need to do is add the sound and yeah. Thanks Jordan 👍
