### ISSUE TITLE
Crash moment

### ISSUE THREAD

**Issue by Akim3000** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#35]
### Describe your bug here.

So, this happened when i wanted to play song
Character.hx (line 358)
PlayState.hx (line 6161)
PlayState.hx (line 5909)
PlayState.hx (line 5783)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
who can help me with this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i drag and dropped mod from OS engine.

**Comment by Akim3000** [comment]
oh well, how i need to fix this, i need to delete the compatibility or what?

**Comment by MemeHovy** [comment]
> oh well, how i need to fix this, i need to delete the compatibility or what?

you need to fix the animation names

**Comment by Akim3000** [comment]
thanks, i fixed the error :D

**Comment by MemeHovy** [comment]
np
