### ISSUE TITLE
[Linux] More notes spawn even off screen, while Windows doesn't causing more lag on Linux.

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#351]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

There seems to be more notes being rendered when on Linux than Windows. This causes more lag.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. Be on Linux
2. Play using JS Engine
3. Play any super spammy song.
4. Way more lag than what you would experience on Windows
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
..can you check on linux that the option "Dynamic Note Spawn Time" is on

**Comment by TheKamboy** [comment]
Damn, I'm a dumbass. Thanks for the help!

**Comment by JordanSantiagoYT** [comment]
LOL you're welcome though, sometimes we all make easy-to-fix mistakes
