### ISSUE TITLE
Gf bent keeps appearing

### ISSUE THREAD

**Issue by HelloPleaseUabeIsDestoryingMyBrain** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#352]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

For some reason whenever i play a song gf is turned into gf-bent for some reason and when i try to change it it wont change and turns it back into gf-bent please fix this!

### Command Prompt/Terminal/Crash logs (if existing)

```bash
idk
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
The only thing thats working is using the change character event
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
you enabled the community game mode option in the settings
