### ISSUE TITLE
this engine keeps getting more complex make it way more easier and simplified

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#354]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

https://youtu.be/MjT85vpZoWk
the game keeps reading it as another song and not the song that it's supposed to be

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by daveandbambifan1234** [comment]
I swear if this is a bug then it must be a major one

**Comment by moxie-coder** [comment]
I’m not understanding this

**Comment by daveandbambifan1234** [comment]
> I’m not understanding this, that video did not help

I'm going to give you every single detail of what I mean

the sound file isn't working and the song name is exact I tried doing everything I could putting it to other folders trying to do everything but nothing would work

**Comment by daveandbambifan1234** [comment]
@moxie-coder I'm going to give you every single detail of what I mean

the sound file isn't working and the song name is exact I tried doing everything I could putting it to other folders trying to do everything but nothing would work

**Comment by JordanSantiagoYT** [comment]
are you sure you didn't just take an mp3 file and change the file extension to .ogg

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/65e75f5f-31bb-4c55-9a18-385e64591b84)
also, what is this directory naming? it should be obvious why it isnt working 😭😭

**Comment by JordanSantiagoYT** [comment]
the game is looking for 'mods/sleepover/songs/house-party' but you're putting the directory as 'mods/sleepover/mods/songs/house-party'

if you were running the engine inside the sleepover folder then it would work as intended..

**Comment by daveandbambifan1234** [comment]
> are you sure you didn't just take an mp3 file and change the file extension to .ogg

no I saved my song as ogg

**Comment by JordanSantiagoYT** [comment]
> the game is looking for 'mods/sleepover/songs/house-party' but you're putting the directory as 'mods/sleepover/mods/songs/house-party'
> 
> if you extracted the engine into mods/sleepover and then ran it from there THEN it would work.

this is your issue.!!

**Comment by TofpFL** [comment]
Jesus Christ even new people can get mixed up. The stuff is in the Mod folder and the game looks for the stuff in the mod folder. You dont make another mod folder for songs because it's already on the mod folder 2 directories past.
