### ISSUE TITLE
annoying crash

### ISSUE THREAD

**Issue by quinmane** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#355]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

PlayState.hx (Line 5324)
PlayState.hx (Line 6229)
PlayState.hx (Line 5772)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
erm, try the current action builds cause the issue's already been fixed

**Comment by moxie-coder** [comment]
> erm, try the current action builds cause the issue's already been fixed

what he said

**Comment by quinmane** [comment]
> erm, try the current action builds cause the issue's already been fixed

how i do dat

**Comment by moxie-coder** [comment]
> > erm, try the current action builds cause the issue's already been fixed
> 
> how i do dat

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions

**Comment by quinmane** [comment]
> > > erm, try the current action builds cause the issue's already been fixed
> > 
> > 
> > how i do dat
> 
> https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions

all i see is a bunch of code what do i do with it

**Comment by moxie-coder** [comment]
> > > > erm, try the current action builds cause the issue's already been fixed
> > > 
> > > 
> > > how i do dat
> > 
> > 
> > https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions
> 
> all i see is a bunch of code what do i do with it

you just click on the latest action and scroll down to artifacts
