### ISSUE TITLE
Fixed Camera

### ISSUE THREAD

**Issue by 0mnilion** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#356]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

i dont really like the camera movement since when 2 people are singing it only focuses on one and i like animations
is there a way to have the camera fixed into the middle

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by 0mnilion** [comment]
also i dindt ask this in questions because this was the first thing i saw

**Comment by JordanSantiagoYT** [comment]
use "Follow Camera Pos" and set it to the middle of the stage

**Comment by 0mnilion** [comment]
is that an event?

**Comment by 0mnilion** [comment]
if it is then, im not charting something. im just playing random mods i find that are actually hard to play, is there something similar to this?

**Comment by moxie-coder** [comment]
> is that an event?

yeah

> if it is then, im not charting something. im just playing random mods i find that are actually hard to play, is there something similar to this?

you can google up scripts for that
