### ISSUE TITLE
FNF CRASHING DURING RANDOM MOMENT WHILE RENDERING A SONG

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#358]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

I chart an 20 minutes long song and during 3rd or 4th minute it gives me an error with null object refference, this error appears for no reason

### Command Prompt/Terminal/Crash logs (if existing)

```bash
NULL OBJECT REFFERENCE
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
sigh...

PLEASE give a crash log, PLEASE i cannot stress this enough this is the 4th time you've made this mistake 😢

**Comment by dimafut** [comment]
IT'S JUST SAYS NULL OBJECT REFERENCE! I CHECKED CRASH FOLDER BUT THERE'S NOTHING ABOUT THAT

**Comment by moxie-coder** [comment]
yeah neither can I if you’re not giving anything remotely helpful
