### ISSUE TITLE
JS Engine: Common Issues and Fixes

### ISSUE THREAD

**Issue by JordanSantiagoYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#359]
This issue is for documenting issues that I see could be reported often, and the fixes for them.

Issue: Game crashes with "[lime.utilis.preloader] ERROR: there is no asset library with an id of "videos"
Fix: The directory that you're using to run JS Engine might contain a character that Lime cannot parse. This includes punctuation or characters that aren't in English. To fix this, you'll need to remove any of those characters.

**Comment by pik3-4** [comment]
how do i get the song to put it in the editor?

**Comment by TheStinkern** [comment]
> how do i get the song to put it in the editor?

the most confusing question of all time
