### ISSUE TITLE
Increasing the combo limit

### ISSUE THREAD

**Issue by PDL2CGamejolt** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#36]
### What is your question?

How can I increase the combo limit from 1.79e+308 to like, idk, 1.45e+10000 or something like that?

**Comment by NAEL2XD** [comment]
I can't find any to change combo Luke 1e10 or more, but there's that other thing where you can set to thousand, million, billion, etc.

**Comment by JordanSantiagoYT** [comment]
you can't, the combo is a float and the max it can go up to is 1.79e+308, any higher and the game will immediately crash
