### ISSUE TITLE
I don't even know what to say about this

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#360]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

All I did was open the game, enter the song name, & press enter. I can't even tell what the [issue](https://drive.google.com/file/d/1AbqThbRZKQOr7858Qiv9xik7iTDtCf38/view?usp=sharing) is 

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
No
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing important. I haven't edited anything since I started this build & I'm just now seeing this

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
the issue is that you're specifying a note splash texture, but it isn't in images/noteSplashes

**Comment by moxie-coder** [comment]
yeah I was going to say that but I was too tired
