### ISSUE TITLE
Playable Characters Flag not set correctly

### ISSUE THREAD

**Issue by TumoPlayz** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#361]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

When I load mods into the engine and play a song, the playable characters are offset wrong. I go to check the character editor and the playable character box isn't checked, even though it usually would be (I played the same mod on base psych and it was in fact marked as a playable character).

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
that's intentional. in 1.25.0 i reworked how playable characters work, so you'll have to go to the character editor, check "Playable Character" and save the character.

**Comment by Stefan2008Git** [comment]
> that's intentional. in 1.25.0 i reworked how playable characters work, so you'll have to go to the character editor, check "Playable Character" and save the character.

Bruh, why?

**Comment by JordanSantiagoYT** [comment]
> > that's intentional. in 1.25.0 i reworked how playable characters work, so you'll have to go to the character editor, check "Playable Character" and save the character.
> 
> If I'm being honest it might need to be changed. Having to go to the character editor every time new character I see in a mod is not really what I wanna do

i also wanted to make it so that if a character's left animation contained "right" then it would also use player offsets

But that breaks Pico and Mom

**Comment by TumoPlayz** [comment]
I mean nice call on the offset correction but I think you should really do
something about pre existing mods
