### ISSUE TITLE
*what does this bug mean*

### ISSUE THREAD

**Issue by Ghost2000gmd** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#362]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![Screenshot 2024-06-04 10 46 30 AM](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/148468646/0095b6b5-efc3-4198-87f6-eab8468805b4) (*)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
dont have it
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
nope it when i load a bg called phobiaHell
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NAEL2XD** [comment]
shader issue, make sure shader is compatible for haxe : https://theleername.github.io/ShadertoyToFlixel/

**Comment by JordanSantiagoYT** [comment]
the cpu you're using uses a GLSL version that's too old to use the bloom shader, in that case i can't help you.
