### ISSUE TITLE
Confusion about the "Noteskin" feature in character editor

### ISSUE THREAD

**Issue by CollinBlue209** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#365]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

There's something I'm having a bit of trouble with in the character editor, I'm unsure how to properly use the noteskin feature.

If I type just the image name of the noteskin, nothing happens.
If I type it in like "images/noteskin" nothing happens.

If you could tell me how this feature works I would appreciate it a ton ^ ^

![noteskin1](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/171882519/b8dc2183-dcba-4ccb-9269-cf768f45f354)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
you're supposed to put your noteskin file in 'images/noteskins/', with the filename matching EXACTLY what you put in the character editor
