### ISSUE TITLE
can you please remove the mix menu song

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#366]
### What feature do you want to get added on the **base** engine?

a

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by JordanSantiagoYT** [comment]
why?

also, you failed the test.

**Comment by moxie-coder** [comment]
yeah, why?

**Comment by daveandbambifan1234** [comment]
> why?
> 
> also, you failed the test.

no I didn't fail the test I passed it in school

**Comment by daveandbambifan1234** [comment]
> yeah, why?
I just got an idea maybe set the default menu theme to Dave and Bambi and if someone wants to change it to the mix theme they can it's just they have to change it

**Comment by moxie-coder** [comment]
you can just easily replace the menu theme dude

**Comment by daveandbambifan1234** [comment]
> you can just easily replace the menu theme dude

you're right I think I lost brain cells from something
