### ISSUE TITLE
Random rendering error on a frame?

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#367]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Sooo i was rendering a song and then some time later at frame 2769, this happens. not sure why?
![Capture d'écran 2024-06-08 004751](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/108278470/ce07a1e5-b1e2-4406-8b35-e32e4af9c856)

i think i'm using the commit 8eb9514 

### Command Prompt/Terminal/Crash logs (if existing)

```bash
^^
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
1. Turn on Video Rendering Mode at Game Renderers
2. Turn on Old Video Rendering Mode
3. Render a song
4. Wait
5. Crash. (Probably luck)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

noh

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Maybe?

**Comment by NAEL2XD** [comment]
actually let me try latest commit and see if the issue is fixed

**Comment by NAEL2XD** [comment]
let me close this, if i get the same error i'll open again

**Comment by JordanSantiagoYT** [comment]
this is luck-based and i have no way of fixing it currently
