### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by UnderFellSansRed2** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#37]
### Describe your bug here.

In android build something gives me an flxsound error

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JordanSantiagoYT** [comment]
know this, for some reason JS Engine can't read the assets folder. as a temporary workaround, move everything inside assets and assets/shader into mods. in mods/sounds, move everything in the hitsounds folder outside to mods/sounds.
