### ISSUE TITLE
how to make opponent's notes visible as shown here?

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#370]
### What is your question?

![Friday Night Funkin' - Taimuresu but the chart is FLP-accurate - YouTube - Google Chrome 09 06 2024 18_30_07](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/156928927/aef89098-21bd-4b8f-b404-78fe32d063a8)

**Comment by moxie-coder** [comment]
they already are by default, you probably changed an option
