### ISSUE TITLE
Compiling Issue 

### ISSUE THREAD

**Issue by jwalls1104** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#372]
Im using the latest Haxe Version And I Installed in everything but for some reason this shows when i compile the source
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:6504: characters 6-57 : Cannot add Void and Int
source/PlayState.hx:6671: characters 5-56 : Cannot add Void and Int
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSounds 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jwalls1104** [comment]
ok new issue

source/flixel/FlxGame.hx:6: characters 8-39 : Type not found : flixel.util.typeLimit.NextState
source/flixel/FlxGame.hx:96: characters 20-29 : Type not found : NextState

**Comment by moxie-coder** [comment]
use haxe 4.2.5 when compiling this

**Comment by jwalls1104** [comment]
> use haxe 4.2.5 when compiling this

got a 2nd error

**Comment by jwalls1104** [comment]
> use haxe 4.2.5 when compiling this

got a 2nd error                                                                                                                                                                                                        C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,8,0/flixel/FlxObject.hx:1215: characters 3-9 : Warning : object.health is being removed in version 6.0.0
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,8,0/flixel/FlxObject.hx:1215: characters 12-18 : Warning : object.health is being removed in version 6.0.0
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,8,0/flixel/FlxObject.hx:1216: characters 7-13 : Warning : object.health is being removed in version 6.0.0
source/Achievements.hx:255: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/FlxUIDropDownMenuCustom.hx:367: characters 18-35 : Warning : FlxButton.PRESSED is deprecated, use FlxButtonState.PRESSED
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/frames/FlxAnimateFrames.hx:166: characters 13-27 : Warning : `framesHash` is deprecated, use `getByName()` or `exists()`
C:\Users\johnn\Downloads\FNF-PsychEngine-NoBotplayLag-main\FNF-PsychEngine-NoBotplayLag-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by jwalls1104** [comment]
Nevermind another different error                                                                                                                                   C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,8,0/flixel/FlxObject.hx:1215: characters 3-9 : Warning : object.health is being removed in version 6.0.0
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,8,0/flixel/FlxObject.hx:1215: characters 12-18 : Warning : object.health is being removed in version 6.0.0
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flixel/5,8,0/flixel/FlxObject.hx:1216: characters 7-13 : Warning : object.health is being removed in version 6.0.0
source/Achievements.hx:255: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/FlxUIDropDownMenuCustom.hx:367: characters 18-35 : Warning : FlxButton.PRESSED is deprecated, use FlxButtonState.PRESSED
C:/Users/johnn/Downloads/FNF-PsychEngine-NoBotplayLag-main/FNF-PsychEngine-NoBotplayLag-main/.haxelib/flxanimate/git/flxanimate/frames/FlxAnimateFrames.hx:166: characters 13-27 : Warning : `framesHash` is deprecated, use `getByName()` or `exists()`
Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?

**Comment by JordanSantiagoYT** [comment]
haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc

**Comment by jwalls1104** [comment]
> haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc

still got the same error for some reason

**Comment by JordanSantiagoYT** [comment]
also i use flixel 5.6.2, because on the newer flixel versions the crosshair in the character editor doesn't show

**Comment by jwalls1104** [comment]
> also i use flixel 5.6.2, because on the newer flixel versions the crosshair in the character editor doesn't show

I installed flixel 5.6.2 too

**Comment by JordanSantiagoYT** [comment]
i dunno then

**Comment by jwalls1104** [comment]
> i dunno then

oh well also can noteskins work with their xml files too or No?

**Comment by moxie-coder** [comment]
> > i dunno then
> 
> oh well also can noteskins work with their xml files too or No?

yeah they’re needed
