### ISSUE TITLE
Null object reference

### ISSUE THREAD

**Issue by raxyd** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#375]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

When I make a new character, it always says null object reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. Only adding songs and images

**Comment by JordanSantiagoYT** [comment]
..can you give a crash log

**Comment by TofpFL** [comment]
Try adding the images or following a tutorial, because the game looks for specific files and if the file isn't there then it might crash.

**Comment by raxyd** [comment]
sorry, I will give you guys a crash log image
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/130116093/a38e9627-b9d6-4b0b-a421-8fca86b37dc9)

**Comment by raxyd** [comment]
I figured it out, I need an icon for my character, or it won't work
