### ISSUE TITLE
How to use .frag shaders in JS Engine

### ISSUE THREAD

**Issue by TofpFL** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#377]
### What is your question?

How to take a shadertoy shader and implement it as a background and or stage?

**Comment by JordanSantiagoYT** [comment]
it's the same as how you would use it in Psych 0.6.3

**Comment by moxie-coder** [comment]
yes because it’s a psych fork

**Comment by JordanSantiagoYT** [comment]
also should prob mention; @TofpFL in 2 of your js/bambi fansong submissions the links to the songs and flms you sent were both links to the form that you were submitting the songs on

**Comment by TofpFL** [comment]
What do you mean? Can you show me images? Also I know that you fo shit the same in psych engine but there is no yt tutorial on how to actually make a frag shader file like in triklizo chart made by TheTrueAccount.

**Comment by JordanSantiagoYT** [comment]
> What do you mean? Can you show me images or provide context? I'm pretty sure that's how it's supposed to work. Also I know that you do shit the same in psych engine but there is no yt tutorial on how to actually make a frag shader file like in triklizo chart made by TheTrueAccount. Nor how to actually softcode it in.

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/0fcdff30-5462-4cb8-b732-6cd7e619a874)

the links are both the same link and lead to this form

**Comment by TofpFL** [comment]
The only reason it's the same link is because the song isn't on YouTube

**Comment by JordanSantiagoYT** [comment]
> The only reason it's the same link is because the song isn't on YouTube. It leads you to the exact same drive. I can't exactly use SNIFF because the BPM is higher than 522

i mean.. if i'm charting it you don't need to exactly use SNIFF
