### ISSUE TITLE
null

### ISSUE THREAD

**Issue by raxyd** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#378]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Every time I make a character with my blood, sweat and tears, it just says null object reference. It never tells me what is a null, but always say null.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit this in any way yet.

**Comment by JordanSantiagoYT** [comment]
Again, no crash log given. you need to give it.

**Comment by moxie-coder** [comment]
you seriously need to give crash logs, because you're not being helpful by giving nothing to work with

**Comment by PatoFlamejanteTV** [comment]
ALWAYS AN NULL 🗿🗿🔥🔥🔥❤️‍🔥❤️‍🔥 WHEN HAVE TEARS AND BLOOD 🔥🔥🔥🗿🗿🗿🗿
