### ISSUE TITLE
Replay previous runs on songs just like how osu, kade engine and leather engine did those a long while ago.

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#379]
### What feature do you want to get added on the **base** engine?

Title.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
no.

i've seen another psych engine mod do this, and it absolutely breaks stages when you load a replay.

**Comment by NAEL2XD** [comment]
well ok
