### ISSUE TITLE
why does it crash when i load every song? i even have the load songs options on 

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#38]
### Describe your bug here.

idk what's the cause but it happened recently everytime i load a song
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/5cbbd1e6-0922-40a2-b4bc-9847f431662c)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nuh uh

**Comment by JordanSantiagoYT** [comment]
engineWatermark.

are you using a hud which contains enginewatermark

**Comment by TheKamboy** [comment]
Hey I had an issue similar to this and I fixed it by changing the Hud in settings to a different Hud, then switching it back
