### ISSUE TITLE
the game keeps on crashing for no reason

### ISSUE THREAD

**Issue by Coolman12662726266** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#380]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

some thing about events
![image_2024-06-14_233647694](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140287530/6c367fe1-868f-41c8-918b-de668fb8bebc)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
PlayState.hx (Line 1958)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
i dont have steps
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
you destroyed botplayTxt.

**Comment by AnnaRaii** [comment]
i'm having the same issue but botplayText is definitely still there, unless it's a different file

**Comment by Coolman12662726266** [comment]
> you destroyed botplayTxt.

oh i did in lua ill fix it

**Comment by moxie-coder** [comment]
Imma assume you fixed it already
