### ISSUE TITLE
How to rename YT watermarks

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#381]
### What is your question?

Like i want the the watermark to be "@NonsensicalGH"
![Screenshot 2024-06-15 030844](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/165565402/88308995-d4e7-488b-a2a6-1f5004cbd05e)

**Comment by JordanSantiagoYT** [comment]
navigate to assets/data and edit ytWatermarkInfo.txt

**Comment by NonsensicalGH** [comment]
Thank You!!!
