### ISSUE TITLE
freeplay & story mode = crash

### ISSUE THREAD

**Issue by insertnameuserhere** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#382]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

if i go to freeplay the game crashes same for story mode

### Command Prompt/Terminal/Crash logs (if existing)

```bash
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 318)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 85)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 57)
WeekData.hx (Line 224)
WeekData.hx (Line 192)
WeekData.hx (Line 180)
StoryMenuState.hx (Line 57)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Invalid char 125 at position 496
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!


now here's the one for freeplay:
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 318)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 85)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 57)
WeekData.hx (Line 224)
WeekData.hx (Line 192)
WeekData.hx (Line 180)
FreeplayState.hx (Line 85)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Invalid char 125 at position 496
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i added my mods from psych engine 0.7.3

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
Your week JSON is formatted incorrectly.

**Comment by insertnameuserhere** [comment]
thx for the info
![Desktop Screenshot 2024 06 15 - 10 13 46 69](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/164517573/0dc66d7e-a808-4d18-8576-9f30d44d3886)
