### ISSUE TITLE
how use bot energy

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#385]
### What is your question?

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/115115978/4423691d-fa3c-4a9d-adc2-05a4b17d18fb

**Comment by JordanSantiagoYT** [comment]
step 1. go to chart editor and place an "Enable Bot Energy" event.

when you reach the point in the song where you placed that event, bot energy will automatically turn on.
when it's active, press CTRL and hold down any strum and the game will automatically hit the notes perfectly as if a bot was playing it.

**Comment by Amgsdfyhadfgybi** [comment]
oh alright, also can you add it as a setting? it seems better that way imo

**Comment by Amgsdfyhadfgybi** [comment]
maybe you could add it in a bugfix update as a little extra thing

**Comment by JordanSantiagoYT** [comment]
i am not adding it as an option. it makes more sense to leave it as an event

**Comment by JordanSantiagoYT** [comment]
even the original person who suggested that feature said it should be an event

**Comment by Amgsdfyhadfgybi** [comment]
oh alright
