### ISSUE TITLE
I have a bug with the engine, but it might just be me?

### ISSUE THREAD

**Issue by Xenith-MROHIO6337** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#388]
### What is your question?

PlayState.hx (Line 7644)
PlayState.hx (Line 6463)
PlayState.hx (Line 5994)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, if you're making a GitHub issue you might want to send that!

That's the crash stuff above.

I don't know if I deleted or replaced something that is important but, what this bug is, is that whenever I hit the first note in my songs, I always crash. But if I miss the first note and hit the second and the rest of the notes, its fine?

Please help me.🥹🙏

**Comment by JordanSantiagoYT** [comment]
You added custom rating quotes, but you forgot to put one for 100%

**Comment by Xenith-MROHIO6337** [comment]
> You added custom rating quotes, but you forgot to put one for 100%

I am sorry, but I don't understand what you mean?

**Comment by Xenith-MROHIO6337** [comment]
I am sorry but i dont know what you mean

**Comment by JordanSantiagoYT** [comment]
basically in 1.26.0 i added the ability for you to customize your rating quotes, which added a ratingQuotes folder in assets/data. if that's not there, you basically deleted it.

**Comment by Xenith-MROHIO6337** [comment]
i did, bro i feel so stupid 😭 
are you able to send me that file? or am i going to have to re-download it??

**Comment by JordanSantiagoYT** [comment]
[ratingQuotes.zip](https://github.com/user-attachments/files/15855469/ratingQuotes.zip)

**Comment by moxie-coder** [comment]
maybe I should make it more clear not to delete that file, or add a failsafe if you do
