### ISSUE TITLE
How to show how many notes you hit aswell as the opponents note hit count

### ISSUE THREAD

**Issue by Ghost2000gmd** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#389]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

-

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
go to options
go to visuals & ui
turn on Rating Counter
scroll until you find "Opponent Note Hit Count"
enable that as well

**Comment by Ghost2000gmd** [comment]
thx

**Comment by Ghost2000gmd** [comment]
i have a new question how do i add subtitles to my song bcz im charting sarvatrika atmahatya and i would like to know
