### ISSUE TITLE
(REMASTERED/MORE UNDERSTANDABLE) "Multi-copy section: option in chart editor"

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#39]
### What feature do you want to get added on the **base** engine?

Just like "Copy next to.." but this option will have an extra checkbox on the bottom left but upper on the lil' buddies, and it shows a text like "sections checked: (example:2)", so when you check it the current section turns green, you could like press the checkbox as many section you want, then it will have another option right under the "sections checked" text that says "Copy the checked sections" hope this helps for you to understand more!!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by JordanSantiagoYT** [comment]
i don't understand this

**Comment by JordanSantiagoYT** [comment]
Added in https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/4a95aac1a2d3b93d32e61846ee67b3deb7c48f9c!
