### ISSUE TITLE
one note gives me two note for no reason

### ISSUE THREAD

**Issue by Coolman12662726266** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#391]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image_2024-06-16_002231840](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140287530/3f0c9334-3c10-430c-9042-0b8b5d47972e)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
none
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i mod with lua

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
go to the gameplay modifiers menu and double check that you didn't set Jack Amount to 1.
