### ISSUE TITLE
strident crisis feature

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#394]
### What feature do you want to get added on the **base** engine?

can you add a special thing in freeplay where if you put (week name)-freeplay into the week folder will make the free play look different it'll make it look like the strident crisis free play menu which is basically sorting out all of this stuff in each category

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by JordanSantiagoYT** [comment]
no, just a useless feature

**Comment by moxie-coder** [comment]
no

**Comment by PatoFlamejanteTV** [comment]
Bro how did you failed the test
