### ISSUE TITLE
Error when compiling JS Engine out of the box

### ISSUE THREAD

**Issue by ARandomGuylol** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#395]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Tried to compile the engine after downloading the zipped code, this is what i got:
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/101367788/96c43c6b-27e0-4a08-9c83-a448259f531c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, straight out of the box.

**Comment by JordanSantiagoYT** [comment]
i don't really understand this, so i can't really give a fix.

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/8c21ca19-5831-47eb-b6f2-1ca84a218a65)

**Comment by moxie-coder** [comment]
yeah, if you're using haxe 4.3, downgrade to 4.2.5

**Comment by Stefan2008Git** [comment]
> yeah, if you're using haxe 4.3, downgrade to 4.2.5

I don't understand why people cannot use latest stable Haxe version. The Haxe 4.2.5 is older, so

**Comment by moxie-coder** [comment]
> > yeah, if you're using haxe 4.3, downgrade to 4.2.5
> 
> I don't understand why people cannot use latest stable Haxe version. The Haxe 4.2.5 is older, so

4.3 changed a lot from 4.2.5, so much it broke a lot of things

**Comment by Stefan2008Git** [comment]
> > > yeah, if you're using haxe 4.3, downgrade to 4.2.5
> > 
> > 
> > I don't understand why people cannot use latest stable Haxe version. The Haxe 4.2.5 is older, so
> 
> 4.3 changed a lot from 4.2.5, so much it broke a lot of things

What if i told you that the latest Haxe version is stable instead of 4.3+?
I don't see anything broken on my modified Psych fork

**Comment by moxie-coder** [comment]
> > > > yeah, if you're using haxe 4.3, downgrade to 4.2.5
> > > 
> > > 
> > > I don't understand why people cannot use latest stable Haxe version. The Haxe 4.2.5 is older, so
> > 
> > 
> > 4.3 changed a lot from 4.2.5, so much it broke a lot of things
> 
> What if i told you that the latest Haxe version is stable instead of 4.3+? I don't see anything broken on my modified Psych fork

it has trouble compiling old projects, and most fnf mods because FNF source was made before 4.3 ever came out and 0.3 updated it to be made for 4.3

**Comment by moxie-coder** [comment]
And Psych engine 0.6 and below was made before 4.3 ever came out, so it has trouble compiling there too

**Comment by Stefan2008Git** [comment]
> And Psych engine 0.6 and below was made before 4.3 ever came out, so it has trouble compiling there too

Are you so lazy to fix this error by removing some folder from Flixel and change functions too?

**Comment by moxie-coder** [comment]
> > And Psych engine 0.6 and below was made before 4.3 ever came out, so it has trouble compiling there too
> 
> Are you so lazy to fix this error by removing some folder from Flixel and change functions too?

wanna see the problems? fine, here you go
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/709365e7-59de-47f6-b504-1cfb780755f0)

**Comment by moxie-coder** [comment]
we don't know why it happens, and it only happens on haxe 4.3, not 4.2.5

**Comment by Stefan2008Git** [comment]
> we don't know why it happens, and it only happens on haxe 4.3, not 4.2.5

It literally teels you what you need to fix

**Comment by JordanSantiagoYT** [comment]
> > we don't know why it happens, and it only happens on haxe 4.3, not 4.2.5
> 
> It literally teels you what you need to fix

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/eb7b5637-badf-4a65-9d9a-b9bb4b79fc2e)
hard to do that when this is what the error is saying to fix

**Comment by JordanSantiagoYT** [comment]
new commit that fixes this issue, may have had to add 2 lines of code but it's worth making sure the new haxe can compile it

(even though it's absolutely stupid that i had to do that)
