### ISSUE TITLE
ratings/judgements don't show at all

### ISSUE THREAD

**Issue by Maks7594** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#397]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

the ratings, judgements, combo don't even show when i press a note (yes i enabled them)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
nope
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
you just load into a song and click a note, no judgement shows up
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

what? i just downloaded the release

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
are you SURE that you've enabled "Show Ratings & Combo" and disabled "Even LESS Botplay Lag"?

**Comment by Maks7594** [comment]
> are you SURE that you've enabled "Show Ratings & Combo" and disabled "Even LESS Botplay Lag"?

im sure about enabling show ratings and combo but didnt think about the botplay setting, ima try

**Comment by Maks7594** [comment]
> > are you SURE that you've enabled "Show Ratings & Combo" and disabled "Even LESS Botplay Lag"?
> 
> im sure about enabling show ratings and combo but didnt think about the botplay setting, ima try

idk how this worked but it worked thanks
