### ISSUE TITLE
Crash when hit note

### ISSUE THREAD

**Issue by PHGaming121** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#4]
### Describe your bug here.

when i hit the first note of ANY song, my game crashes with a null object reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no edits on code

**Comment by JordanSantiagoYT** [comment]
the engine usually shows a window if it crashes, can you crash it again like this and show me what it says?

**Comment by PHGaming121** [comment]
![Captura de Tela (468)](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/76562427/93293895-5ce6-4c47-8f99-8aafbb8a56d4)

**Comment by JordanSantiagoYT** [comment]
according to what i found, it crashes because goodNoteHit calls popUpScore, which makes the scoretext pop up. however since 'Hide ScoreTxt' is enabled it crashes. try turning off 'hide scoretxt' in the visuals & ui settings and then try hitting a note again

**Comment by JordanSantiagoYT** [comment]
fixed in 1.7.0
