### ISSUE TITLE
Game crashes when song loads

### ISSUE THREAD

**Issue by ScrumptiousBrownie** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#40]
### Describe your bug here.

everytime i enter a song once it loads it just crashes
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/132102005/9b74af07-2c5e-418c-85bc-8b40f98e03a8)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
invalid note textures/XML

**Comment by ScrumptiousBrownie** [comment]
how do i fix that?

**Comment by MemeHovy** [comment]
by fixing up the animation names

**Comment by ScrumptiousBrownie** [comment]
i dont have adobe animate

**Comment by MemeHovy** [comment]
then you will have to do it manually in the xml file

**Comment by ScrumptiousBrownie** [comment]
no way
