### ISSUE TITLE
Exit anticheat script

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#402]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Can there be a script to prevent people from exiting a song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment]
not really

**Comment by StinkTheStinker** [comment]
ill try doing it that way

**Comment by StinkTheStinker** [comment]
real quick
how do i fix this shit again
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/13d5001f-8d28-4251-901d-6e4ed500aba0)

**Comment by JordanSantiagoYT** [comment]
idk
