### ISSUE TITLE
Update broken?

### ISSUE THREAD

**Issue by Nowthiscomesfrominside** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#405]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

So I open JSEngine after like not playing for a month, so it tells me theres an update, shocking right? But when I pressed enter to update it, it finished, but it just crashed and gave me a file and an assets folder, so I go and check temp for the .zip file, I extract it and the first thing I see when I enter is the haxel logo and then it crashes.
Either its mods or something is broken. I already know nobody gonna reply with shit but if you do yeah, thats my information about it.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 318)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 147)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (Line 57)
TitleState.hx (Line 178)
flixel/FlxGame.hx (Line 639)
flixel/FlxGame.hx (Line 726)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 552)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Invalid char 0 at position 0
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Enter the fucking game.
It just breaks and crashes.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
unfinished update, try installing from github
