### ISSUE TITLE
some custom player characters in other mods poses not in the correct position

### ISSUE THREAD

**Issue by SPC-JustARandomImpostor** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#406]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

so for some mods the custom player's posees dont move in the right position. don't know what causing this, not a big issue but if you can, pls fix this.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
i dont know if there is a way to replicate this bug, i guess use a player character this isnt bf, idk.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
that's because in newer versions i reworked how playable characters work. if your mod is affected by this you'll need to edit your character. it won't break if the character name ends with "player" or "playable"

**Comment by SPC-JustARandomImpostor** [comment]
alr, sounds good.
