### ISSUE TITLE
i keep crashing

### ISSUE THREAD

**Issue by Ghost2000gmd** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#407]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

[JSEngine_2024-06-24_15'14'08.log](https://github.com/user-attachments/files/15957757/JSEngine_2024-06-24_15.14.08.log)
[JSEngine_2024-06-24_09'29'10.log](https://github.com/user-attachments/files/15957758/JSEngine_2024-06-24_09.29.10.log)
[JSEngine_2024-06-24_09'26'56.log](https://github.com/user-attachments/files/15957760/JSEngine_2024-06-24_09.26.56.log)
[JSEngine_2024-06-24_09'19'03.log](https://github.com/user-attachments/files/15957761/JSEngine_2024-06-24_09.19.03.log)
[JSEngine_2024-06-17_19'35'06.log](https://github.com/user-attachments/files/15957762/JSEngine_2024-06-17_19.35.06.log)
[JSEngine_2024-06-17_18'51'51.log](https://github.com/user-attachments/files/15957763/JSEngine_2024-06-17_18.51.51.log)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
06-24 errors: the png/xml that your character json is pointing to doesn't exist.
06-17 errors: your stage json is formatted incorrectly.

**Comment by moxie-coder** [comment]
> 06-24 errors: the png/xml that your character json is pointing to doesn't exist. 06-17 errors: your stage json is formatted incorrectly.

yeah I guessed that
