### ISSUE TITLE
How to make Health drain happen during a song?

### ISSUE THREAD

**Issue by SuperRyan0308** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#409]
### What is your question?

So, I am making a chart for "Fuming", and I was going to make Bambi have health drain, but I can't seem to get it working so is there a way to make it work?

**Comment by moxie-coder** [comment]
did you enable it in the character editor? and did you fill out these?
![IMG_9271](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/124418090/c05de850-8ca7-4549-a21b-38201bf48a64)

**Comment by SuperRyan0308** [comment]
uhhh....no I never used that method, I was gonna use it only for the song I was charting.

**Comment by moxie-coder** [comment]
> uhhh....no I never used that method, I was gonna use it only for the song I was charting. Also, I never saw or used the drain amount and drain floor code

then you can go ahead and google a script for if you wanna use it during a song

**Comment by SuperRyan0308** [comment]
I see what you're saying but the scripts I used before weren't working, that was the main problem.
