### ISSUE TITLE
Icons right off the bar

### ISSUE THREAD

**Issue by ScrumptiousBrownie** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#41]
### What feature do you want to get added on the **base** engine?

Using botplay (with practice mode and opponent drain) if the opponent makes you lose all health with practice the healthdrain will continue even off the bar
![out of here icons](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/132102005/e4e26421-3e2b-46f4-9661-0020043da88d)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor and 6K+ support.

**Comment by JordanSantiagoYT** [comment]
not a necessary addition, when the health is below like -70% the icons wouldn't even be visible

**Comment by JordanSantiagoYT** [comment]
BUT i will consider adding it

**Comment by JordanSantiagoYT** [comment]
added in https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/2b1e00b55cbc5f800cfdcead874f6aa193a7dc6b
