### ISSUE TITLE
customization for free play menu

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#412]
### What feature do you want to get added on the **base** engine?

the idea: how about you can make a different BG image for the weeks, this will make things look much cooler also if you want to choose a different BG for a specific song There can be a toggle for that in a future update also you can add the wavy BG and there can be a toggle for that too because it will write a script with the week to make the BG wavy. sorry this was a long idea but I'm pretty sure you'll add more to it in future updates

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by Stefan2008Git** [comment]
No one needs this to engine 👎🏻

**Comment by moxie-coder** [comment]
yeah I’m not doing this
