### ISSUE TITLE
game crashes on hurt note (in a mod)

### ISSUE THREAD

**Issue by Maks7594** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#415]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

when a hurt note gets rendered, the game crashes

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Note.hx (Line 436)
PlayState.hx (Line 4389)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
place a hurt note, and render it when playing or playtesting chart in a custom mod
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by Maks7594** [comment]
wait lemme try this in clean version

**Comment by Maks7594** [comment]
alr it still breaks itself in clean version

**Comment by JordanSantiagoYT** [comment]
colorswap.

did you turn enable color shader on?

**Comment by Maks7594** [comment]
> colorswap.
> 
> did you turn enable color shader on?

note color style?

**Comment by JordanSantiagoYT** [comment]
> > colorswap.
> > did you turn enable color shader on?
> 
> note color style?

no, the one above it
