### ISSUE TITLE
character menu problem

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#416]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

it happens in the character debug

now I have to rechart the song thanks to this horrible bug, now my chart is now lost so I have to start from the beginning thanks to this horrible bug

### Command Prompt/Terminal/Crash logs (if existing)

```bash
editors/ChartingState.hx (Line 1035)
flixel/ui/FlxButton.hx (Line 521)
flixel/ui/FlxButton.hx (Line 507)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
I will explain it in words

so when I was adding my new character to the mod I accidentally renamed "character name down" to "character name" I tried fixing it and when I tried fixing it and clicked add/update the game crashed

this bug was found on version 0.19.1
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

the bug happened in my fnf mod

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
..

don't use 1.19.0 first of all

**Comment by moxie-coder** [comment]
yeah update to the latest version, since that might’ve fixed that issue in a newer version

**Comment by daveandbambifan1234** [comment]
> ..
> 
> don't use 1.19.0 first of all

idk why i use 1.19.0
