### ISSUE TITLE
Invalid cast error

### ISSUE THREAD

**Issue by FinderFromMac** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#417]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

I added this mod of Suffering Siblings v3 charted into the JS engine and it keeps crashing with an "Invalid cast error"
https://gamebanana.com/mods/483736

### Command Prompt/Terminal/Crash logs (if existing)

```bash
StrumNote.hx (Line 243)
PlayState.hx (Line 6807)
PlayState.hx (Line 6391)
PlayState.hx (Line 4419)
flixel/group/FlxGroup.hx (Line 770)
PlayState.hx (Line 4417)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Invalid Cast
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
No, I don't know what is causing it or how, In psych 6.3 it doesn't crash, But in the JS engine with the recent version (which has 6.3ver of Psych) it crashes with the error mentioned before

I used an online XML validator by codebeautify to check if it was valid, but it kept crashing with an invalid cast error
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
this means you changed the note color settings to "char-based" and turned off "enable color shader" which means the shader never gets initialized

**Comment by FinderFromMac** [comment]
Turning shaders off actually worked

Thanks

**Comment by FinderFromMac** [comment]
@moxie-coder thx for referencing!

**Comment by moxie-coder** [comment]
> @moxie-coder thx for referencing!

np
