### ISSUE TITLE
Play As Opponent Glitch

### ISSUE THREAD

**Issue by PDL2CGamejolt** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#42]
### Describe your bug here.

The entire thing is messed up.
The icons are in the wrong place, the arrows on the left side is going on the right side, and arrows on the right side is going on the left side!
![212121](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/94698464/9f4e8ae7-d104-4e3a-b7c3-be842ded7ea1)
Don't ask.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Development on EVERY INITALIZATION FAILED THING BE LIKE + Unholy Dimension

**Comment by JordanSantiagoYT** [comment]
pretty sure this only happens if you switched the "Play as Opponent" toggle during a song. did you do that?

**Comment by PDL2CGamejolt** [comment]
I don't think I did it DURING a song, I did it BEFORE the song.

**Comment by MemeHovy** [comment]
I've been unable to reproduce this issue as of the latest version, @PDL2CGamejolt you think you could try updating the engine? and then seeing if that fixes the issue?
