### ISSUE TITLE
Game keeps crashing everytime i play songs without botplay

### ISSUE THREAD

**Issue by Gatocat939** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#420]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

so yeah i was just testing out the new songs from the mods for js engine and it just kept crashing everytime i tried playing it normally but playing it with botplay doesnt crash

### Command Prompt/Terminal/Crash logs (if existing)

```bash
PlayState.hx (Line 7614)
PlayState.hx (Line 6529)
PlayState.hx (Line 6051)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yep i tried putting all the files again and still doesnt work

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
you deleted the `ratingQuotes` folder, then tried playing a song.

**Comment by Gatocat939** [comment]
nope. its still there i just dindt delete it @JordanSantiagoYT

**Comment by JordanSantiagoYT** [comment]
right, which version?

**Comment by Gatocat939** [comment]
new one

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/81cc9117-4a12-4c17-848f-9452695e5be3)
..that is what the faulty line is referring to.

**Comment by JordanSantiagoYT** [comment]
if it's crashing but it's there, that means you tried adding a new set of rating quotes but didn't add one for 100% accuracy

**Comment by Gatocat939** [comment]
do i just have to reinstall the game

**Comment by JordanSantiagoYT** [comment]
you need to edit your quote file to add ("Quote name here", 1)

**Comment by Gatocat939** [comment]
ok but like

**Comment by Gatocat939** [comment]
i dont see any ratingquote file
i kinda dont know if its there

**Comment by JordanSantiagoYT** [comment]
so.. you deleted the files inside it but not the folder

**Comment by Gatocat939** [comment]
i think

**Comment by JordanSantiagoYT** [comment]
[ratingQuotes.zip](https://github.com/user-attachments/files/16075306/ratingQuotes.zip)
here's a clean copy of ratingQuotes

**Comment by Gatocat939** [comment]
now where do i place it

**Comment by JordanSantiagoYT** [comment]
place the folder inside in assets/data/ratingQuotes

**Comment by Gatocat939** [comment]
alright done

**Comment by Gatocat939** [comment]
and it works fine

**Comment by Gatocat939** [comment]
ty for helping me

**Comment by JordanSantiagoYT** [comment]
yw!
