### ISSUE TITLE
Fix your fork or else i am gonna start to hate it

### ISSUE THREAD

**Issue by Stefan2008Git** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#421]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

This is a issue when i enter to mod songs, even OG songs, the game just make my laptop to immediately crash your fork so badly and also i am the Linux user, also you seriously need to fix bunch of bugs ands errors for PlayState, like there is a lot of them and people are getting many issues about that and they reporting to me instead on your repository

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Tf? I already say the issue what i got and i didn't get a crash logs. Do i need to explain better or what do you want me to do?
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Unknown unfortunately
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, i am simply here to report some people issue

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
i need crash logs or can't fix them.

**Comment by Stefan2008Git** [comment]
> i need crash logs or can't fix them.

Fuck it. I don't have it. Don't you know what "immediately crashed game" means? It means if your games crashes immediately you are not getting any crash logs or something. Do i have to explain better or?

**Comment by cabfile** [comment]
the error handler is not the only way that can be used to find and fix errors jordan

**Comment by Stefan2008Git** [comment]
> the error handler is not the only way that can be used to find and fix errors jordan

He made the fork, so he need to fix the issue duh

**Comment by JordanSantiagoYT** [comment]
> the error handler is not the only way that can be used to find and fix errors jordan

okay, but it's the most helpful way

the 2nd most helpful is to list the steps to reproduce the issue, but that's not listed now is it? because he only says "it immediately crashed"

**Comment by cyklusiguess** [comment]
also, in linux, some uppercase songs crashes because it is case sensitive

**Comment by moxie-coder** [comment]
> also, in linux, some uppercase songs crashes because it is case sensitive

yeah that’s true

**Comment by Stefan2008Git** [comment]
You know what y'all. Screw this

**Comment by cyklusiguess** [comment]
lil bro raged

**Comment by cyklusiguess** [comment]
> also, in linux, some uppercase songs crashes because it is case sensitive

it honestly angers me so much because i need to rename it to lowercase

**Comment by Stefan2008Git** [comment]
> lil bro raged

Exsume me, but do you think how old am i?
