### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#422]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

error: hxdiscord_rpc is not installed, I installed it (although it was in the installer) and then the same thing again😥

### Command Prompt/Terminal/Crash logs (if existing)

```bash
D:\FNF-PsychEngine-NoBotplayLag-1.28.0>haxelib run lime test windows
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Achievements.hx:255: characters 30-54 : Warning : (WDeprecated) `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/frames/FlxAnimateFrames.hx:166: characters 13-23 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?

D:\FNF-PsychEngine-NoBotplayLag-1.28.0>haxelib install hxdiscord_rpc 1.1.1
Downloading hxdiscord_rpc-1,1,1.zip...
Download complete: 0.25KB in 0.3s (0.7KB/s)
Download complete: 4.58MB in 0.9s (4963.2KB/s)
Installing hxdiscord_rpc...
  Current version is now 1.1.1
Done
Installing dependency hxcpp 4.3.2
You already have hxcpp version 4.3.2 installed
Set hxcpp to version 4.3.2 [y/n/a] ? y
Library hxcpp current version is now 4.3.2

D:\FNF-PsychEngine-NoBotplayLag-1.28.0>haxelib run lime test windows
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Achievements.hx:255: characters 30-54 : Warning : (WDeprecated) `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/frames/FlxAnimateFrames.hx:166: characters 13-23 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
honestly I do not know
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
did you try running hmm?

**Comment by JordanSantiagoYT** [comment]
haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc

**Comment by bimbifan** [comment]
> haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc

dont work

**Comment by bimbifan** [comment]
> did you try running hmm?

install, dont work

**Comment by JordanSantiagoYT** [comment]
try removing it and reinstalling it

if this doesnt work, try running haxelib --global git, then cd to the source code directory and run the command

**Comment by bimbifan** [comment]
> попробуйте удалить его и переустановить
> 
> Если это не сработает, попробуйте запустить haxelib --global git, затем перейдите в каталог с исходным кодом и запустите haxelib git

TYSM, but now the exact same situation with hxCodec

**Comment by bimbifan** [comment]
> ```shell
> d to be installed?
> ```

D:\FNF-PsychEngine-NoBotplayLag-1.28.0>haxelib run lime test windows
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Achievements.hx:255: characters 30-54 : Warning : (WDeprecated) `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:/FNF-PsychEngine-NoBotplayLag-1.28.0/.haxelib/flxanimate/git/flxanimate/frames/FlxAnimateFrames.hx:166: characters 13-23 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
Error: Could not find haxelib "hxCodec", does it need to be installed?

D:\FNF-PsychEngine-NoBotplayLag-1.28.0>haxelib install hxCodec
You already have hxCodec version 3.0.2 installed
