### ISSUE TITLE
i literally cant put a song in chart debug part

### ISSUE THREAD

**Issue by DustEpicKaiSans** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#423]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

i cant put a song, everytime i put the name of the song and click "reload song" it crashes, same when i have the name folder and the inst.ogg part, heres a video 

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/150727511/8bca08ed-3104-49df-8a41-23e4dd168343

yeah, everytime, i already tried 4 times or more, and see the options to see if anything was off, like "load songs" i think, that last time, i think, it did that. and no, it does not do a error/crash log

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment]
when you put the inst.ogg, are you sure you didn't just put an mp3 and rename it to "inst.ogg"?

**Comment by JordanSantiagoYT** [comment]
also, have you tried any other song besides thearchy?

**Comment by DustEpicKaiSans** [comment]
> when you put the inst.ogg, are you sure you didn't just put an mp3 and rename it to "inst.ogg"?

Yeah, I use a site that make mp3 to ogg, I could try and redo it

> also, have you tried any other song besides thearchy?

No, I could try later, I'll try later actually, I can't rn, but asap I'll try, and even see if the rest works normally, I got quite "stressed", not literally, but something close to it, and left the game, I'll try if the rest works normally too

**Comment by DustEpicKaiSans** [comment]
> also, have you tried any other song besides thearchy?

with any other song works normally, even in the chart debug, so or it is some bug that make the game crash if it acces new songs or this engine has Thearchyphobia or someshit

**Comment by DustEpicKaiSans** [comment]
ill try to redo the file transition, and if it was that, ill fucking rage, and sorry if was that too

**Comment by DustEpicKaiSans** [comment]
> ill try to redo the file transition, and if it was that, ill fucking rage, and sorry if was that too

yeah no, it wasnt

**Comment by JordanSantiagoYT** [comment]
my thearchy works, maybe you can try that one and see if it works
[Inst.zip](https://github.com/user-attachments/files/16118114/Inst.zip)

**Comment by NAEL2XD** [comment]
> my thearchy works, maybe you can try that one and see if it works [Inst.zip](https://github.com/user-attachments/files/16118114/Inst.zip)

also if the person says it doesn't work, tell them to use audacity as it has a higher success rate than any of the site

**Comment by DustEpicKaiSans** [comment]
> my thearchy works, maybe you can try that one and see if it works [Inst.zip](https://github.com/user-attachments/files/16118114/Inst.zip)

ill see, and your file is bigger than the mine thearchy, your is 2mb and mine is 1

**Comment by DustEpicKaiSans** [comment]
it fucking worked, i hate that shit


> > my thearchy works, maybe you can try that one and see if it works [Inst.zip](https://github.com/user-attachments/files/16118114/Inst.zip)
> 
> also if the person says it doesn't work, tell them to use audacity as it has a higher success rate than any of the site

oh, ok, ill try using that, never happened that with mine, so prob it was the file, sorry if this took too much time of yall

**Comment by DustEpicKaiSans** [comment]
now, just a question, whats thearchy bpm? its really 400? or idk

**Comment by JordanSantiagoYT** [comment]
> > my thearchy works, maybe you can try that one and see if it works [Inst.zip](https://github.com/user-attachments/files/16118114/Inst.zip)
> 
> also if the person says it doesn't work, tell them to use audacity as it has a higher success rate than any of the site

true that

**Comment by JordanSantiagoYT** [comment]
> now, just a question, whats thearchy bpm? its really 400? or idk

i used 200

**Comment by DustEpicKaiSans** [comment]
lol, that was the exactly bpm i was thinking it was, thanks
