### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Dimarar** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#424]
### What is your question?

1(for moxie-coder). what the build you mean?
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/112246243/02d30dc2-d669-4496-85a3-048a1356c7ff)
2 (for jordan santigo). when you made a update what fixes the note hit bug ( #396 ) and why your discord acc is deleted?

**Comment by moxie-coder** [comment]
1. The one in actions https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions
2. I don’t know and he doesn’t use discord
