### ISSUE TITLE
How to stop vanilla girlfriend replacing other characters assigned as gf

### ISSUE THREAD

**Issue by FinderFromMac** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#430]
### What is your question?

Since I'm new to modding I assigned a character as gf in the chart editor, but the engine refuses to change the vanilla girlfriend sprite to the character, this applies to every song in vanilla fnf and the mod. how do I fix this?

EDIT: This does not happen in psych
EDIT 2: Happens with all vanilla songs and with the mod, and yes I'm using a clean version

**Comment by JordanSantiagoYT** [comment]
please be more clear about your issue.

**Comment by FinderFromMac** [comment]
Sorry, I was in a hurry

Basically when a character is assigned as 'gf' the engine refuses to change the 'gf-bent' sprite to the assigned character's sprite

**Comment by JordanSantiagoYT** [comment]
go to options -> gameplay and turn off "communitygame mode"

additionally, try the latest action build (i removed this option)

**Comment by FinderFromMac** [comment]
Thanks 
(Sorry if I look like a retard to you, I'm new to the engine and modding 😅)
