### ISSUE TITLE
Cannot access

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#432]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Cannot access (error from vscode, I'm saying just in case)

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Haxe server restart requested: DisplayArguments configuration was changed
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Restarted Haxe server: DisplayArguments configuration was changed
Failed - try fixing the error(s) and restarting the language server:

source/DiscordClient.hx:3: characters 8-25 : You cannot access the cpp package while targeting hl (for cpp.ConstCharStar)
source/Main.hx:16: characters 8-21 : ... referenced here
[Error - 10:15:34 PM] Request textDocument/hover failed.
  Message: You cannot access the cpp package while targeting hl (for cpp.ConstCharStar)
  Code: -32603
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
NNOO
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment]
make sure you’re not trying to build towards Hashlink, because the error states that you are
