### ISSUE TITLE
the editor note tap sound thingy

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#436]
### What feature do you want to get added on the **base** engine?

it scares me when it's on full spanking volume
there is a problem with the note sound in the chart editor because it's a little way too loud so make a setting option where you can make it so you can optimize the volume of the sound

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by daveandbambifan1234** [comment]
I know there is already an option in the charter editor but it doesn't save

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/user-attachments/assets/4ab6cd43-20e9-4d2c-8c49-8c8608dd9666)
actually there is an option to mute the sounds entirely, and it DOES save.

**Comment by JordanSantiagoYT** [comment]
i am not going to add a full option for it, because it's unnecessary.

**Comment by daveandbambifan1234** [comment]
![image](https://github.com/user-attachments/assets/0611b062-69a0-48de-aea3-31d76f17b608)
nope that's something different from what I'm trying to talk about
