### ISSUE TITLE
JS Engine: The Return to Android

### ISSUE THREAD

**Issue by JordanSantiagoYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#437]
so... it's been 5 months since ive discontinued JS Engine for the Android devices.

have you missed using JS Engine's newest updates on your Android device, and don't want to be stuck just using 1.18.0 anymore?

well... JS ENGINE FOR ANDROID IS BACK!!
i have not officially brought it back yet, but someone out there has (for some reason) decided to port JS Engine back to Android devices! if you're an iOS user, you get to share the fun with those Android users as this engine has also been ported there!!

this (unofficial) android port can be downloaded here: https://github.com/MobilePorting/JS-Engine-Mobile/releases/latest

# IMPORTANT

**PLEASE,** if you find an issue/bug, ***REPORT IT HERE FIRST!!!*** if i do determine that it's an android-specific issue THEN you can report it to the android github but this is a **"just to be safe"** thing because i don't want people incorrectly reporting js engine issues (that are in all versions) to the github for mainly the mobile versions.

**Comment by moxie-coder** [comment]
thanks

**Comment by mcagabe19** [comment]
@JordanSantiagoYT we're team not "someone"

**Comment by moxie-coder** [comment]
> @JordanSantiagoYT we're team not a "someone"

I can fix it hun

**Comment by moxie-coder** [comment]
nvm he fixed it

**Comment by JordanSantiagoYT** [comment]
This will be unpinned to provide help on checking for issues.
