### ISSUE TITLE
Crediting Issue: Update Screen

### ISSUE THREAD

**Issue by Core5570RYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#438]
### What is your question?

Hello there! I'm the main developer of **CDEV Engine.**
I've noticed that **JS Engine** used the same Updater Screen like in **CDEV Engine**.
Upon further inspection in the source code, turns out JS Engine used a similar code that's used in CDEV Engine

| #    | JS Engine | CDEV Engine |
|------|-----------|-------------|
| In-Game UI |![image](https://github.com/user-attachments/assets/fecb19ed-c5a7-4d26-873b-51127b74d7f7)|![image](https://github.com/user-attachments/assets/f2833575-335f-4b4d-adf1-9f06ef8e32e8)|
| Source Code | ![image](https://github.com/user-attachments/assets/f6a67a62-81b2-4726-81b5-6090f4e312b4) ![image](https://github.com/user-attachments/assets/6181fa6e-d8c2-49eb-9ed6-c68dffa0fb8d) | ![image](https://github.com/user-attachments/assets/a195f991-4b5c-47e7-bee5-628d52301463) ![image](https://github.com/user-attachments/assets/c8c2ceb6-42fd-4840-be2b-b9aa64c0e6b1) |

It would be really helpful if you credited me for the Update Screen code, Thank you!

**Comment by NAEL2XD** [comment]
lemme make a pr incase if jordan can't credit for the 567744531321th time

**Comment by Stefan2008Git** [comment]
> lemme make a pr incase if jordan can't credit for the 567744531321th time

![skeleton](https://github.com/user-attachments/assets/38c70cbb-2ffa-4e43-8f45-280fed1aab30)
You guys are seriously joking, right?

**Comment by moxie-coder** [comment]
you also could've made this an discussion @Core5570RYT
