### ISSUE TITLE
"shit" judgement has disappeared

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#443]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

i saw that something strange is happened, when I spam, the "shit" judgement won't counting and it's always zero, I went in the option and there wasn't "shit" judgement

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by dimafut** [comment]
here is the image
![Friday Night Funkin'_ JS Engine - marathon (Freeplay) 16 07 2024 20_16_37](https://github.com/user-attachments/assets/932443d4-15af-41e7-8108-c671cd09bf21)

**Comment by JordanSantiagoYT** [comment]
that's because for a shit, you have to hit a note at a window WORSE than the bad window

**Comment by moxie-coder** [comment]
yeah this is more of a case of stupidity
