### ISSUE TITLE
The Object does not have the property Alpha error

### ISSUE THREAD

**Issue by FinderFromMac** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#447]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

When loading the script at a song the engine itself crashes, the script below makes the game crash
```lua
function onCreate()
	makeLuaSprite('mails', 'ss/mails', 275, 100)
	setObjectCamera('mails', 'camHUD')
	scaleObject('mails', 0.35, 0.35)
	addLuaSprite('mails', true)
	setProperty('mails.alpha', 0)
end

function onUpdate()
    if curStep == 3 then
        doTweenAlpha('mails', 'mails', 1, 2, 'linear')
    end
    if curStep == 99 then
        doTweenAlpha('mails', 'mails', 0, 2, 'linear')
    end
end
```
![mails](https://github.com/user-attachments/assets/e7ac071f-fdb3-4867-bf6c-4238bb1e3093)
above is the image linked to the script
other scripts that have 'makeLuaSprite()' on doesn't crash the game

### Command Prompt/Terminal/Crash logs (if existing)

```bash
flixel/tweens/misc/VarTween.hx (line 99)
flixel/tweens/misc/VarTween.hx (line 55)
flixel/tweens/FlxTween.hx (line 1099)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: The object does not have the property "alpha"
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
probably because the tween name is the same as the sprite which you're changing the alpha of??

**Comment by moxie-coder** [comment]
a tween name shouldn't be the same as a sprite name

**Comment by FinderFromMac** [comment]
works, thx
