### ISSUE TITLE
the hell is this?

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#449]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

the chart does not move to the next section and continues to go on one section, even if it has ended

https://github.com/user-attachments/assets/0281ca74-2d21-431b-897e-9730042c030b

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NAEL2XD** [comment]
i wonder what causes this... 
![image](https://github.com/user-attachments/assets/b26e4308-c1f0-447b-963e-5322e9725d9e)

**Comment by dimafut** [comment]
I'm going to check

**Comment by dimafut** [comment]
oh, TYSM
