### ISSUE TITLE
Freeplay songs and mods crash

### ISSUE THREAD

**Issue by REALCraylenGD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#45]
### Describe your bug here.

Invalid char 118 at position 0
This is a new build
I investigated and it's a mod bug
![Screenshot 2023-10-13 100708](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/77181802/53df918c-3ba9-471f-a02c-dac6c40c99a3)

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by REALCraylenGD** [comment]
I changed the ModsList.txt but no luck.

**Comment by JordanSantiagoYT** [comment]
you messed up one of your week jsons, check each week json in (mod name)/data/weeks

**Comment by JordanSantiagoYT** [comment]
it’s an issue with your week jsons, the thing i suggest is to delete the mods in your build one by one until your engine stops crashing

**Comment by REALCraylenGD** [comment]
I deleted literally everything and it finally stopped crashing. I deleted "the frame of wiring" last so it must be that

**Comment by REALCraylenGD** [comment]
nope, when I put everything back, it crashed again

**Comment by JordanSantiagoYT** [comment]
now try removing each mod and put them back one by one until it crashes again, make sure to reopen the engine each time you put the next mod in

**Comment by REALCraylenGD** [comment]
ok

**Comment by REALCraylenGD** [comment]
when I add ANY MOD, it crashes, WHAT

**Comment by JordanSantiagoYT** [comment]
that’s weird but idk how to help as none of these crash for me

**Comment by REALCraylenGD** [comment]
okay I changed some of the values in modsList and the only ones that display in freeplay are: Jordan's Large FNF Charts & The Charts

**Comment by REALCraylenGD** [comment]
turns out, you have to delete the jsons with the links, and i did that BUT the songs just crashed the engine when I played them. No error, just crash.

**Comment by REALCraylenGD** [comment]
it only crashes on the mod songs... not on the fnf songs.

**Comment by REALCraylenGD** [comment]
i tweaked the settings but nothing worked. i don't get it.

**Comment by JordanSantiagoYT** [comment]
oh. i’m sorry idk how to help as none of them crash for me

**Comment by JordanSantiagoYT** [comment]
I've found the culprit for the week JSON crash. Git LFS apparently messed up some of the week JSONs.

**Comment by JordanSantiagoYT** [comment]
A commit has been pushed to the repository hopefully fixing all the crashes. Be sure to delete the mods you currently have installed and reimport the new ones.

**Comment by REALCraylenGD** [comment]
:O Thank you

**Comment by REALCraylenGD** [comment]
IT WORKED
