### ISSUE TITLE
Scripts not reading in song's data folder

### ISSUE THREAD

**Issue by FinderFromMac** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#451]
### What is your question?

I found this weird issue of scripts not loading inside a song's data folder, how do I fix it?

**Comment by JordanSantiagoYT** [comment]
it loads scripts inside a song's data folder just fine. can you show a video?

**Comment by FinderFromMac** [comment]
Fixed it myself

**Comment by moxie-coder** [comment]
can you say how you fixed it? Also others can know how to?

**Comment by FinderFromMac** [comment]
You need to match the data folder to the song folder so that the scripts can load

**Comment by moxie-coder** [comment]
> You need to match the data folder to the song folder so that the scripts can load

alright, and yeah they do need to match since the game can’t find the song files if the song and data folders don’t match
