### ISSUE TITLE
sustain note coloring in chart editor removed

### ISSUE THREAD

**Issue by FuseIsHere813** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#456]
### What needs to be documented?

i swore there was sustain note coloring in 1.29, was it considered useless?

![Screenshot 2024-07-26 064643](https://github.com/user-attachments/assets/30a35e04-5ede-40a5-bb2e-e100f539d32a)
![Screenshot 2024-07-26 064654](https://github.com/user-attachments/assets/94150349-6ef3-4d52-b3e2-583586502d6b)

**Comment by JordanSantiagoYT** [comment]
they ARE supposed to be colored. however there's an issue with action build compiling rn which means i cant put hxcpp, as a result this happens

**Comment by JordanSantiagoYT** [comment]
fixed in 1.30.1
