### ISSUE TITLE
I need Help With Adding The Charts

### ISSUE THREAD

**Issue by wowthisisarandomuser** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#46]
### Describe your problem here.

i dont really know how i do it so can anyone help me with it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by NAEL2XD** [comment]
1. Make sure the song and the chart is the same

1.1. Check song name in json file, it should be located all the way down that says song

2. Go to chart editor, type song name in songs tab, press reload, if you get a crash error that means you either typed it incorrectly or song and chart isn't equal

**Comment by wowthisisarandomuser** [comment]
ok ill try that thanks!

**Comment by wowthisisarandomuser** [comment]
ive done the charts but i get this message now
![image_2023-10-13_193624733](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/120335948/e52b793b-ce70-438d-9e74-fa94bde05eb2)
