### ISSUE TITLE
Charts In The Right Place But Not Working

### ISSUE THREAD

**Issue by wowthisisarandomuser** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#47]
### Describe your bug here.

i put the file into mods and tried using js engine 1.11 as a bit of help but it just crashed after trying to go through the main menu

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I Didnt

**Comment by JordanSantiagoYT** [comment]
I've found the culprit for the week JSON crash. Git LFS apparently messed up some of the week JSONs.

**Comment by JordanSantiagoYT** [comment]
A commit has been pushed to the repository hopefully fixing all the crashes. Be sure to delete the mods you currently have installed and reimport the new ones.
