### ISSUE TITLE
Notetypes don't work at all.

### ISSUE THREAD

**Issue by DuskDragonNight75** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#49]
### Describe your bug here.

To put it simply, no notetypes i put in work, not even the hurt notes or "Hey" notes. They all just show up as normal notes and act the same as normal notes.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100539847/ec244b74-f5ae-4f12-a902-008621ffcc0e)
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/100539847/bb2b6ead-c79f-4e68-ac05-278d7f213fd2)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not really anything, I just added a mod. I even removed it and it still kept happening.

**Comment by JordanSantiagoYT** [comment]
alright, so let me ask 1 question:

Did you or did you not have Optimized Chart Loading turned on? cause having it turned on causes note types to just not work

**Comment by MemeHovy** [comment]
Optimized Chart Loading has since been removed in 1.13.0 so this is pretty much outdated

**Comment by JordanSantiagoYT** [comment]
> Optimized Chart Loading has since been removed in 1.13.0 so this is pretty much outdated

yeah, i removed it shortly after this post was made

**Comment by JordanSantiagoYT** [comment]
Optimized Chart Loading was removed, so this is resolved i guess?
