### ISSUE TITLE
crashes when trying to load song

### ISSUE THREAD

**Issue by Tyshaun-l** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#5]
### Describe your bug here.

When i try to load a song it crashes (i'm using wine)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no(wtf does this mean)

**Comment by JordanSantiagoYT** [comment]
ok, heres info
1. provide a screenshot of the crash log
2. its basically asking you if you changed any of the engine's code

**Comment by Tyshaun-l** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/141663511/e5c25d5c-1552-41c2-b874-6b1188951ada)

**Comment by JordanSantiagoYT** [comment]
hmmm.. according to what i see, you tried reloading a song, but pinkwave-hard's json might be missing. try reimporting it then try again

**Comment by Tyshaun-l** [comment]
same issue keeps crashing

**Comment by JordanSantiagoYT** [comment]
i have no idea, its never occured for me

**Comment by MemeHovy** [comment]
@Tyshaun-l the reason this error is occurring due to a missing song JSON
