### ISSUE TITLE
game crashes when i play a song

### ISSUE THREAD

**Issue by duskyyyyy** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#50]
![Screenshot 2023-10-25 164247](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/148952026/206d3564-ed50-44d7-8161-690492371128)
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

**Comment by MemeHovy** [comment]
seems to be an issue involving bot play text although considering you’re using an older version, try turning optimized chart loading

**Comment by duskyyyyy** [comment]
when you said something about botplay i remembered about that showcase mode thing or whatever and i turned it off

huh what a shocker it's fixed (thank you)

**Comment by MemeHovy** [comment]
oh okay, np
