### ISSUE TITLE
Automatic Chart

### ISSUE THREAD

**Issue by 4stacks67** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#53]
### What feature do you want to get added on the **base** engine?

A Useful Feature For People Who Are Tired Of Charting/Can’t Chart

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by MemeHovy** [comment]
you failed the test and plus it's not possible at all due to the implementation of the charting system so no

**Comment by 4stacks67** [comment]
MAN FRIC-

**Comment by JordanSantiagoYT** [comment]
1. You failed the test.
2. this feature is impossible to add

**Comment by StinkTheStinker** [comment]
> 1. You failed the test.
> 2. this feature is impossible to add

fr
