### ISSUE TITLE
Android version doesn't detect assets

### ISSUE THREAD

**Issue by boristsve** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#54]
### Describe your problem here.

Hello, I'm trying to play this engine on android, I extracted the assets to the .JSEngine folder, but the game still says I haven't extracted it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JordanSantiagoYT** [comment]
yeah, you're supposed to put those files in the .PsychEngine folder, not the .JSEngine folder
