### ISSUE TITLE
Mobile char and bg crash bug

### ISSUE THREAD

**Issue by Roaming77321** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#55]
### Describe your bug here.

When I tried to play a song with BG and char disable it crashes 

### Command Prompt/Terminal logs (if existing)

```bash
Uncaught Error: Null Object Reference
PlayState.hx (Line 1317)
flixel/FlxGame.hx (Line 642)
flixel/FlxGame.hx (Line 729)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 550)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by MemeHovy** [comment]
did you remove gf during a song?

**Comment by JordanSantiagoYT** [comment]
workaround: turn off double note ghosts

**Comment by Roaming77321** [comment]
> workaround: turn off double note ghosts

OK thanks its work
