### ISSUE TITLE
Every song I load crashes

### ISSUE THREAD

**Issue by Kelnamed** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#57]
### Describe your bug here.

![Friday Night Funkin'_ JS Engine - Freeplay Menu 31_10_2023 7_26_08 PM](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/149486000/4f5669f1-ece4-409b-ab12-a614448c52cf)
Basically, the title I made is self-explanatory. Yes, including Week 1-Week 6 songs that I load experience the same issue. Strangely enough, the older version I had (JS Engine 1.11) works without any issues at all. It loads songs just fine although I'm unsure whether it might be due to compatibility issues or not.

### Command Prompt/Terminal logs (if existing)

```bash
No command/terminal logs.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by MemeHovy** [comment]
disable community game bot mode for now, I'll fix it

**Comment by Kelnamed** [comment]
Alright, it works now. Good to know about it.

**Comment by MemeHovy** [comment]
> Alright, it loads songs as expected now. Thanks for the quick temporary solution.

np
