### ISSUE TITLE
Pressing 7 to go to the Chart Editor no longer works in the latest action build

### ISSUE THREAD

**Issue by miksel1** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#59]
### Describe your bug here.

even when i set the 7 event to none it doesnt work

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/117042313/e502de39-cacb-495a-ba1f-72ae7de99f1c

![Screenshot_116](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/117042313/8b178d13-4f9d-437b-ba97-50393164761e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by MemeHovy** [comment]
okay so not only do I know the reason why, I also know a fix, it's due to a little oversight by not adding a missing case for "None"

**Comment by JordanSantiagoYT** [comment]
latest commit fixed this
