### ISSUE TITLE
songs wont load or even crash even when i have the jsons and inst, voices

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#6]
### Describe your bug here.

i dont know how the heck this happened but, whenever i tried to load a song it wont play or well load, it just keeps showing 00:00 or something like that and even crashes, even tho i have the files and jsons
![aue2](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/02ee4b1e-f6ae-415b-88e0-ccec35e15847)
![aue3](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/82dfe77b-0982-4f00-9285-1acea8e6351f)

![aue](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/7be175c4-6387-4c95-a703-7c00310c1abf)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
you turned off the "load songs" option

turn it back on in options / optimizations

**Comment by Mushymushroom12** [comment]
oh okay thanks
