### ISSUE TITLE
health drain bug

### ISSUE THREAD

**Issue by Marioispro1** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#62]
### Describe your bug here.

when you use health drain the health in the info bar doesnt update until bf hits a note

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/133698570/a1b7315e-4c6f-4241-91bd-fc760f36bb66)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
will fix in 1.14.0
