### ISSUE TITLE
🆘

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#63]
### Describe your bug here.

Started compiling and got this:

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:29: characters 8-36 : Type not found : sys.thread.ElasticThreadPool
source/Main.hx:129: characters 31-48 : Type not found : ElasticThreadPool
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

**Comment by JordanSantiagoYT** [comment]
just remove the threadpool and any related code from Main, from what ive seen it does relatively nothing to help performance

**Comment by bimbifan** [comment]
> просто удалите пул потоков и любой связанный с ним код из Main, насколько я видел, он практически не влияет на производительность

source/openfl/display/FPS.hx:89: characters 27-67 : Not enough arguments, expected Precision:Int

**Comment by JordanSantiagoYT** [comment]
fixed in latest commit for source code
