### ISSUE TITLE
ISSUE IS FOUND!!111111!11!!!!!

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#64]
### Describe your problem here.

There is this weird Haxel thing here and I not know how to fix it, can somebody help me with this?
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/f5623051-4860-439e-b2bf-b41dfd742634)

Note: Can't tell if it's a bug report or a help. So I picked one of them.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, It's something about a stage.

**Comment by JordanSantiagoYT** [comment]
that simply means you're missing a png, be sure the path to the image is correct

**Comment by StinkTheStinker** [comment]
> that simply means you're missing a png, be sure the path to the image is correct
> 
> also, make sure you don't put ".png" at the end

This looked like this already. I don't even know why I didn't add this to the Description.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/37fd29d9-35e1-48be-803e-50ef10da7157)

**Comment by StinkTheStinker** [comment]
Here is the video for a bit of more context.

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/f010e461-3902-48f1-b899-193ea2dcd543

**Comment by JordanSantiagoYT** [comment]
ah, another script may be causing that

be sure to send me the full cheating bg png so i can be sure that the haxe logo isnt a part of the bg

**Comment by StinkTheStinker** [comment]
![cheater](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/ecebaee9-95b9-46c7-ada4-0721305decee)

**Comment by JordanSantiagoYT** [comment]
yeah, it's possible another script you have might be causing that

**Comment by StinkTheStinker** [comment]
This is the only script, it's for an event. Which shakes the screen and the game.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/e014d459-8686-4bbd-a9c4-2f5d42f85bf5)

**Comment by StinkTheStinker** [comment]
Let me add another video with the event activated on it. Just give me a sec.

**Comment by JordanSantiagoYT** [comment]
well one other solution you can try is to try doing this in psych to see if it's js-specific

**Comment by StinkTheStinker** [comment]
Good point hold on.

**Comment by StinkTheStinker** [comment]
It will be a different song by the way.

**Comment by StinkTheStinker** [comment]
Psych Engine: 

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/fe66c62c-bff6-4306-aa9a-f7e9ec7cc7c8

**Comment by StinkTheStinker** [comment]
Event thing:

Uploading 2023-11-04 17-18-09.mp4…

**Comment by StinkTheStinker** [comment]
fuck it was still uploading

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/c751f688-e22d-46c1-b305-1f939614ac1c

**Comment by JordanSantiagoYT** [comment]
wait, it may be because of a song-specific script maybe?

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/800c6dee-b1f7-4780-be0c-0a36ecd710a8)

**Comment by StinkTheStinker** [comment]
There is only a .json file. Don't think it should be the reason.

**Comment by JordanSantiagoYT** [comment]
hmm, check mods/scripts

**Comment by StinkTheStinker** [comment]
This was from earlier.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/98816e94-418c-47d7-b073-694191a9bf25)

**Comment by StinkTheStinker** [comment]
Once again, for one of the events.

**Comment by JordanSantiagoYT** [comment]
a

yeah idk, but i think it might be the noteskin bc in psych it’s different than the js noteskin

**Comment by StinkTheStinker** [comment]
I removed the lua file for the character. And the noteskins that I dragged into the mods folder. I did those two things when I did the mod drag transfer.

**Comment by StinkTheStinker** [comment]
Im gonna try adding the swirl thing, I just gotta add the shader since I accidently deleted it. If that's the reason.

**Comment by StinkTheStinker** [comment]
Ok I thought.

I did get an error from the swirl earlier though. I got rid of it to fix it.

**Comment by StinkTheStinker** [comment]
Used a different stage by the way.

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/da9ae864-892a-419d-a37d-14ae7f076727

**Comment by StinkTheStinker** [comment]
Removed all the shaders that were in the mod folder, there was a fart.frag that had the same swirl.

**Comment by JordanSantiagoYT** [comment]
yeah, that basically means a json you put in has either incorrect formatting or is corrupted

**Comment by StinkTheStinker** [comment]
Hold on, let me delete the json

**Comment by StinkTheStinker** [comment]
I deleted the json, and it is not working still. 
![image_2023-11-04_173416697](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/59f8f3ab-e5f8-4ef3-8d57-ca1559f2291a)

**Comment by StinkTheStinker** [comment]
I guess we found 2 bugs.

**Comment by StinkTheStinker** [comment]
Im gonna close this.

**Comment by StinkTheStinker** [comment]
JS, let me know if you find why this is happening.

**Comment by StinkTheStinker** [comment]
Im gonna open this.

**Comment by JordanSantiagoYT** [comment]
the invalid char error means something's wrong with your stage JSON, not stage LUA

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a2923f2f-46c5-4602-9b4c-707db4040b98)
Theres the screen shot of the one with the swirl and without swirl.

**Comment by StinkTheStinker** [comment]
youcheated is without swirl, youareunfair is the one with swirl

**Comment by JordanSantiagoYT** [comment]
the format for the "youareunfair" json is messed up
you have a , after "hide_girlfriend": true, when there shouldnt be one

**Comment by StinkTheStinker** [comment]
is it the ","?

**Comment by JordanSantiagoYT** [comment]
yeah

**Comment by StinkTheStinker** [comment]
k give me a sec.

**Comment by StinkTheStinker** [comment]
what is the swirl promnt again?

**Comment by JordanSantiagoYT** [comment]
well i think it was a haxeflixel logo

**Comment by StinkTheStinker** [comment]
oh yea the haxeflixel logo is still there.

**Comment by StinkTheStinker** [comment]
even with a different stage.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/417d004f-8b47-423e-9ba3-e37f9dfb01df)

**Comment by JordanSantiagoYT** [comment]
with your script, remove the code that adds the background. let me know if the haxe logo still is visible, you can add it back after you're done testing

**Comment by JordanSantiagoYT** [comment]
wait i just realized, the mod's public so i can download and test the mod

**Comment by StinkTheStinker** [comment]
the mod pack that you made?

**Comment by JordanSantiagoYT** [comment]
no, the "Bambi's Comeback" mod that you're playing

**Comment by StinkTheStinker** [comment]
thats on psych engine, not js engine

**Comment by StinkTheStinker** [comment]
i am thinking of switching to js engine, since it has the swirl thing

**Comment by StinkTheStinker** [comment]
ill send the mod rq, i just need to turn it into a zip.

**Comment by StinkTheStinker** [comment]
i need to put it on the drive

**Comment by StinkTheStinker** [comment]
its adding it to the drive.

**Comment by StinkTheStinker** [comment]
https://drive.google.com/file/d/16WagFiPeiJNXtQmQ4k9AfGF1fUQ7XKb7/view?usp=sharing

**Comment by StinkTheStinker** [comment]
open the cheating chart

**Comment by StinkTheStinker** [comment]
ill be back.

**Comment by StinkTheStinker** [comment]
aight

**Comment by StinkTheStinker** [comment]
gtg

**Comment by JordanSantiagoYT** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/e890acf7-8b6b-414d-b4e6-3afd7e4b583b

**Comment by JordanSantiagoYT** [comment]
there's no haxeflixel logo?

**Comment by StinkTheStinker** [comment]
im back, but how tf is there no haxeflixel logo for you?

**Comment by JordanSantiagoYT** [comment]
https://drive.google.com/file/d/1SoTc90TN6Dzr3AkIkw0YAZqtRjtrfNmT/view?usp=sharing idk, but here's the one i used, i just put it in the mods folder as its own mod

**Comment by StinkTheStinker** [comment]
it is still there
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/ddd592bc-62c2-4d62-84bd-13dc2de25e40)

im just about to get yoshi engine. if it even has swirl support.

**Comment by JordanSantiagoYT** [comment]
yeah, it's something to do with your build of JS Engine. id suggest just reinstalling the engine then try again

also i don't really care whether or not people use yoshi engine (i think it has swirl support idk, there's bamber and davey v2 and the cheating song uses a swirl bg)

**Comment by StinkTheStinker** [comment]
i played that mod. it is good. but back to the point, it is the latest version thats not the android version, since i do not know how to fucking compile or some shit.

**Comment by StinkTheStinker** [comment]
this is on a different JS engine folder too.

**Comment by JordanSantiagoYT** [comment]
well it cant be based off your settings cause im pretty sure there arent any options that cause haxeflixel logos to appear

but reset your jse settings just in case and see if that works

**Comment by StinkTheStinker** [comment]
ill reset it. let me save a chart rq.

**Comment by JordanSantiagoYT** [comment]
and use the default noteskin cause the nonsense v2 one is really weird

**Comment by StinkTheStinker** [comment]
it will reset it anyway. how do i reset it anyway.

**Comment by JordanSantiagoYT** [comment]
just press "R" in every options menu. it basically resets all the settings to their default values

**Comment by JordanSantiagoYT** [comment]
if you want a faster way, just go to C:\Users\(your username)\AppData\Roaming\ShadowMario\JSEngine and delete both files in there

**Comment by StinkTheStinker** [comment]
changed the notes to 3d, stil aint workin. ill reset it now. you should add a feature to reset every single one of the setings quick. ill do the js engine setting file thingy rq.

**Comment by StinkTheStinker** [comment]
controls_v2.sol and funkin.sol?

**Comment by JordanSantiagoYT** [comment]
yeah

**Comment by JordanSantiagoYT** [comment]
but quick warning: that resets your scores as well

**Comment by StinkTheStinker** [comment]
i dont play that much things on JS Engine. exept songs that i like playing.

**Comment by StinkTheStinker** [comment]
does it remove my auto save as well?

**Comment by JordanSantiagoYT** [comment]
well idk, probably (i havent tested that myself)

**Comment by StinkTheStinker** [comment]
ill be the first to do it on js engine then, if i am.

**Comment by StinkTheStinker** [comment]
deleted it and it did not reset the setting somehow.

**Comment by JordanSantiagoYT** [comment]
did you have the engine open while doing it?

**Comment by StinkTheStinker** [comment]
nope

**Comment by StinkTheStinker** [comment]
i reseted every setting manuly now. let me check if it worked.

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/ced8dccc-58e4-483e-b57d-24d2ad732d63)
am i really this dumb

apparently, the save is located at C:\Users\(username)\AppData\Roaming\JordanSantiago\JSEngine.

**Comment by StinkTheStinker** [comment]
also it did delete the auto save

**Comment by JordanSantiagoYT** [comment]
oh

**Comment by StinkTheStinker** [comment]
bruh.

**Comment by StinkTheStinker** [comment]
🤓 
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/047a3fbb-13dd-4bd4-be07-20e5f1e224a7)

**Comment by StinkTheStinker** [comment]
i just fuckin opened the song 
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/0e7e5591-472c-4854-ae65-9710957b386e)

**Comment by JordanSantiagoYT** [comment]
"Hey, watch out! This Mod(ENGINE) contains some flashing lights! Press ENTER to disable them now or go to Options Menu. Press ESCAPE to ignore this message. You've been warned!" - 🤓

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/071dd123-fe10-456b-b656-46a96dd77213)
bro

**Comment by StinkTheStinker** [comment]
top left

**Comment by StinkTheStinker** [comment]
use the 1.12.0 version rq. see if its just the actuall version

**Comment by JordanSantiagoYT** [comment]
oh

**Comment by JordanSantiagoYT** [comment]
wait youre using 1.12.0

**Comment by JordanSantiagoYT** [comment]
ohh

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/f8428d10-5dd0-426a-a65c-22e71579fa55)
so this was fixed in 1.13.0

**Comment by StinkTheStinker** [comment]
what the fuck

**Comment by StinkTheStinker** [comment]
i cant even compile. thats the fucking thing.

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/bb9770c8-825e-415c-b99a-58ec2c478148)
a

**Comment by StinkTheStinker** [comment]
did you find that botplay bug i talked about in a bug report

**Comment by JordanSantiagoYT** [comment]
yeah

**Comment by JordanSantiagoYT** [comment]
it was related to the version :sob:

**Comment by JordanSantiagoYT** [comment]
wait gimme the swirl thing

**Comment by StinkTheStinker** [comment]
the promnt for it?

**Comment by JordanSantiagoYT** [comment]
the addGlitchEffect thing or whatever it is for the stage's lua script

**Comment by StinkTheStinker** [comment]
ill just send it for the people wondering how to do it 
`
	addGlitchEffect('some shit here', 0.3)`

**Comment by StinkTheStinker** [comment]
this is probably one of the most long thing in this js engine form thing yet. this is so fuckin long

**Comment by JordanSantiagoYT** [comment]
ok i think just try on a completely brand new 1.13.0 build

**Comment by StinkTheStinker** [comment]
bro

**Comment by JordanSantiagoYT** [comment]
the haxeflixel logo was not related to the engine's version.

**Comment by StinkTheStinker** [comment]
> ok i think just try on a completely brand new 1.13.0 build

1.12.0 you mean?

**Comment by JordanSantiagoYT** [comment]
well if you dont want to use https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/releases/tag/1.13.0 then yeah, a brand new 1.12.0 build

**Comment by StinkTheStinker** [comment]
credit me for the bug report

**Comment by StinkTheStinker** [comment]
jk

**Comment by JordanSantiagoYT** [comment]
ok

**Comment by JordanSantiagoYT** [comment]
GUH

**Comment by StinkTheStinker** [comment]
wait do you actully want to do that?

**Comment by JordanSantiagoYT** [comment]
well uhhh idk what bug its fixing :sob:

**Comment by StinkTheStinker** [comment]
botplay

**Comment by JordanSantiagoYT** [comment]
i mean a similar issue was already reported earlier, and a pr fixed that issue

**Comment by StinkTheStinker** [comment]
im stupid, wtf is a pr

**Comment by JordanSantiagoYT** [comment]
pull request, it's a thing where someone makes changes to the source code, usually to fix an issue they found

**Comment by StinkTheStinker** [comment]
ohhhhh

**Comment by StinkTheStinker** [comment]
here let me download the 1.20 thingy

**Comment by StinkTheStinker** [comment]
WHEN TF WAS THERE A COMPILED VERSION

**Comment by StinkTheStinker** [comment]
LAST TIME I LOOKED AT IT THERE WAS HNO COMPILED VERSION

**Comment by JordanSantiagoYT** [comment]
where were you looking

**Comment by JordanSantiagoYT** [comment]
were you looking at the 1.13.1 release

**Comment by StinkTheStinker** [comment]
holy fuck im dumb.

**Comment by StinkTheStinker** [comment]
they almost look fucking idenicall

**Comment by JordanSantiagoYT** [comment]
LMAO im sorry ill try to separate releases better with 1.14.0 and onward

**Comment by StinkTheStinker** [comment]
at least people wont get confused, like me

**Comment by JordanSantiagoYT** [comment]
true

**Comment by StinkTheStinker** [comment]
its still fucking there

**Comment by JordanSantiagoYT** [comment]
a

im out of ideas here

**Comment by StinkTheStinker** [comment]
139 comments on this, holy shit

**Comment by StinkTheStinker** [comment]
also quick question, how to i do the song by thing?

**Comment by StinkTheStinker** [comment]
never mind

**Comment by JordanSantiagoYT** [comment]
its an editable field in the chart editor

**Comment by StinkTheStinker** [comment]
there should be an option for credit icon and credit bar (both custom)

**Comment by JordanSantiagoYT** [comment]
funny thing, in 1.14.0 i basically added that

**Comment by JordanSantiagoYT** [comment]
except it only colors according to the opponent's health bar color

**Comment by StinkTheStinker** [comment]
i ment images, but im guessing its not in the update.

**Comment by JordanSantiagoYT** [comment]
oh

yeah thats not really in there

**Comment by StinkTheStinker** [comment]
ofc dave and bambi only has the credit/bar images. so prob add em

**Comment by JordanSantiagoYT** [comment]
well they have icons

the bar images, i may consider adding

**Comment by StinkTheStinker** [comment]
yea. make it like a dropdown thing. the only thing that i know will be complicated is the mod/images part, if you are gonna do that.

**Comment by StinkTheStinker** [comment]
sorry thats headings

**Comment by StinkTheStinker** [comment]
wait, what if its the randomized botplay txt?

**Comment by JordanSantiagoYT** [comment]
idk

**Comment by StinkTheStinker** [comment]
let me see rq

**Comment by StinkTheStinker** [comment]
nope

**Comment by StinkTheStinker** [comment]
its actully just staying still, it moves with the bg (not the swirl). thats a fucking bg issue

**Comment by StinkTheStinker** [comment]
now i need to go to bed. its 10 PM.

**Comment by StinkTheStinker** [comment]
thanks for trying to help

**Comment by JordanSantiagoYT** [comment]
no problem

**Comment by StinkTheStinker** [comment]
Well, still there.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/bb2239fb-bc70-44e5-98a9-2eee50162f76)

**Comment by StinkTheStinker** [comment]
It is in the latest version by the way!

**Comment by JordanSantiagoYT** [comment]
yeah, i dont think i know a way to fix this

**Comment by StinkTheStinker** [comment]
what about the other person?

**Comment by StinkTheStinker** [comment]
if he codes

**Comment by JordanSantiagoYT** [comment]
the other person? whos that

**Comment by StinkTheStinker** [comment]
as well

**Comment by JordanSantiagoYT** [comment]
you mean @Stefan2008Git ? i don't think he knows either

**Comment by StinkTheStinker** [comment]
yea that guy

**Comment by Stefan2008Git** [comment]
How i can help?

> you mean @Stefan2008Git ? i don't think he knows either

**Comment by StinkTheStinker** [comment]
this
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/e802045a-8a46-4da9-9f5b-d985c987d380)
this little dumb icon wont go away on my end, JS's end does not show that icon, but mine does

**Comment by Stefan2008Git** [comment]
> this ![image](https://user-images.githubusercontent.com/145304742/283280395-e802045a-8a46-4da9-9f5b-d985c987d380.png) this little dumb icon wont go away on my end, JS's end does not show that icon, but mine does

Are you sure you have correct image file and name

**Comment by StinkTheStinker** [comment]
image2 images are unused

**Comment by Stefan2008Git** [comment]
Nope, i can't help. Sorry @StinkTheStinker

**Comment by StinkTheStinker** [comment]
fuck

**Comment by StinkTheStinker** [comment]
esume

estart song

**Comment by StinkTheStinker** [comment]
me
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/7d53361e-3aa4-45a3-8fdd-f9cdd29aea42)

**Comment by StinkTheStinker** [comment]
also, quick question, what are these two for.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/0c1984a8-4e7b-4fce-9d70-9da4281f1026)
i know its for the results music

**Comment by JordanSantiagoYT** [comment]
theyre only used for the results screen, but the game alters between the two depending on what time of the day you finished the song

**Comment by StinkTheStinker** [comment]
mk
