### ISSUE TITLE
Error popup when I play a song I ported over

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#65]
### Describe your problem here.

I don't code so I'm having trouble understanding what the issue is. I ported my mod folder over from psych engine (manny edition specifially) and it was perfectly fine there. I removed a floating & credit script, the events, and a camera swing script

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/dcdcec6c-2719-47c7-8998-625414841581

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

It was mostly deleting things I wasn't going to use that came over with the port, such as backgrounds, songs, stages, images, and I replaced the default BF sprite but that hasn't caused any issues afaik

**Comment by JordanSantiagoYT** [comment]
did you check if your opponent actually has sing anims

**Comment by SMWpalkia** [comment]
i have the opponent set to only be a static idle #
![Screenshot 2023-11-04 233647](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/15bdba04-a506-4cab-8cc1-24cc22ccd0e0)
![Screenshot 2023-11-04 233702](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/cc5a81b6-f519-41df-b0d5-b1dfcde36774)

**Comment by JordanSantiagoYT** [comment]
yeah that's a problem with Double Note Ghosts

the game is coded to run doGhostAnim with the animation it's supposed to play
when the opponent doesn't have singAnimations and instead only has an idle, when running doGhostAnim the game tries to grab offsets from a null animation, which returns a null object reference and crashes the game.

there are 2 workarounds to this:

1. create sing animations and have them all set to the idle animation
2. turn off Double Note Ghosts

**Comment by SMWpalkia** [comment]
oh alright thank you. also side question, why do some opponent icons appear under bf instead of on the icon bar?

**Comment by JordanSantiagoYT** [comment]
from what i have seen, this occurs when an icon is bigger than 150x150, 300x150, or 450x150. i removed Big Icon support for winning icon support apparently

**Comment by SMWpalkia** [comment]
Is there a way to enable bug icon support on my end?

**Comment by JordanSantiagoYT** [comment]
you’d have to edit source code

**Comment by SMWpalkia** [comment]
> yeah that's a problem with Double Note Ghosts
> 
> the game is coded to run doGhostAnim with the animation it's supposed to play when the opponent doesn't have singAnimations and instead only has an idle, when running doGhostAnim the game tries to grab offsets from a null animation, which returns a null object reference and crashes the game.
> 
> there are 2 workarounds to this:
> 
> 1. create sing animations and have them all set to the idle animation
> 2. turn off Double Note Ghosts

i gave my character very small changes in their poses but the crash still occurs 
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/29880f71-f929-41bd-ba50-f2272e592849

**Comment by JordanSantiagoYT** [comment]
you added the sing animations, but they have the wrong name. they must be named accordingly:
right -> singRIGHT
left -> singLEFT
down -> singDOWN
up -> singUP

**Comment by SMWpalkia** [comment]
omg thank you so much!

**Comment by StinkTheStinker** [comment]
you should close this tbh.

**Comment by StinkTheStinker** [comment]
problem solved so it doesnt rlly matter.

**Comment by StinkTheStinker** [comment]
problem solved so it doesnt rlly matter.
