### ISSUE TITLE
Again

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#66]
### Describe your bug here.

Problem again:

### Command Prompt/Terminal logs (if existing)

```bash
source/openfl/display/FPS.hx:89: characters 27-67 : Not enough arguments, expected Precision:Int
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

NOOOPE

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

**Comment by StinkTheStinker** [comment]
Go to the file that is causing the problem (source/o[enfl/display/FPS.hx and go to line "89" and go to the letters "27-67", if you can't find out why, look up a tutorial.

**Comment by StinkTheStinker** [comment]
Not kidding, thats all I know. Tried helpin.

**Comment by JordanSantiagoYT** [comment]
alright, so first you’re going to go to openfl/display/FPS

then go to the Memory line where it calculates RAM
replace this line:

if (ClientPrefs.showRamUsage) text += "\nMemory: " + CoolUtil.formatBytes(Memory.getCurrentUsage()) + (ClientPrefs.showMaxRamUsage ? " / " + CoolUtil.formatBytes(Memory.getPeakUsage()) : "");

with this:
if (ClientPrefs.showRamUsage) text += "\nMemory: " + CoolUtil.formatBytes(Memory.getCurrentUsage(), false, 2) + (ClientPrefs.showMaxRamUsage ? " / " + CoolUtil.formatBytes(Memory.getPeakUsage(), false, 2) : "");

**Comment by JordanSantiagoYT** [comment]
fixed in latest commit
