### ISSUE TITLE
The Double-Ghost Note problem

### ISSUE THREAD

**Issue by MrSropical** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#68]
### Describe your bug here.

So Whenever there's a custom-note that it should get unpressed the DGN counts it and also the game crash when the DGN finds the alt-animation notes

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
is it off?
Options>Visuals And UI>Double Note Ghosts
check if thats there.

**Comment by StinkTheStinker** [comment]
i dont think you are looking at this

**Comment by MrSropical** [comment]
i know i should disable it but its a report bug

**Comment by JordanSantiagoYT** [comment]
Alt Animation crashing the game when DNG is now a known issue. I unfortunately don't know how to fix this, so the best workaround is to turn it off for now

**Comment by JordanSantiagoYT** [comment]
fix ed
