### ISSUE TITLE
Botplay won;t work

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#69]
### Describe your bug here.

![bruh](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/8254e597-5cc3-4813-b2df-6dd12114dc5c)

Error when you toggle BotPlay in the pause menu.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I don't even do source code.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/28ecdb64-e702-4861-b8a7-fd71bc87048f)
just the engine being dumb i guess

**Comment by JordanSantiagoYT** [comment]
nvm its because the version of the engine used here is 1.12.0

**Comment by SyncGit12** [comment]
this is the 69th issue
