### ISSUE TITLE
adding "light player strum" option on the optimization

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#7]
### What feature do you want to get added on the **base** engine?

so if light botplay strum exists, why not try adding Player Light strums?, i mean if you really wanna play without any glow press arrow or fade thingy without turning on botplay its a good idea to add this feature so you dont really only watch the botplay plays and you play it, and also if light botplay strum is for botplay well light player strum is for us players.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by JordanSantiagoYT** [comment]
added in commit https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/a575b6f71eb0877eeeb058fb10746b3f65452b83!
