### ISSUE TITLE
✨1.14.0✨ (i use compiled js)

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#71]
### Describe your problem here.

With version 1.14.0 of the js engine it became simply impossible to do anything, the c key in the chart editor simply stopped working, and when you press enter, it simply doesn’t go back, and when you put the key in the menu and do nothing, the game just crashes with the error null object reference AND DONT WORK MOBILE MIDDLESCROLL

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by JordanSantiagoYT** [comment]
okay.
first of all, the c key in the chart editor not working is intentional. i removed it because EZ Spam is much better in EVERY SINGLE WAY.
mobile middlescroll is deprecated and will be removed in 1.15.0.
with the Enter not going back and game null object reference things, im gonna need you to send me a video.

**Comment by StinkTheStinker** [comment]
blud doesnt read the changelogs 💀

**Comment by JordanSantiagoYT** [comment]
> blud doesnt read the changelogs 💀

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/d61d26bd-07c7-42f2-83e3-7a9f3f51177d)
literally just updated without bothering to read the changelog

**Comment by StinkTheStinker** [comment]
fr

**Comment by bimbifan** [comment]
> хорошо. Прежде всего, клавиши c в редакторе диаграммы намеренно не работают. я удалил его, потому что EZ Spam намного лучше во всех отношениях. mobile middlescroll устарел и будет удален в версии 1.15.0. поскольку Enter не возвращается назад, а в игре есть ссылки на нулевые объекты, мне нужно, чтобы вы прислали мне видео.

If anything, I meant about null object reference in the controls options, and in the chart editor, in principle, everything is fine, only sometimes there can be errors in events, for example, when I created the change scroll speed event, I got an error: invalid value 165 (I have this value)
