### ISSUE TITLE
Thre things

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#72]
### What feature do you want to get added on the **base** engine?

Cam beat when part of a introtext pops up when the game is starting up. Another thing is that there should be built in on the chart editor (data tab) is a built in app name changer, for a song of course. Which means you don't have to add a script to do it.

Note: new idea in comment thing.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by StinkTheStinker** [comment]
Also could not know what type of credit to add.

**Comment by StinkTheStinker** [comment]
I just came up with another one, Dave and Bambi Character select. Character select that has all characters (playable in the json name, and bf) in the game, including the mod characters. It's fine if you don't want to add this.

**Comment by StinkTheStinker** [comment]
how the fuck did i misspell three

**Comment by JordanSantiagoYT** [comment]
1. Do you mean the camera bouncing on a beat hit in the title state? That was originally in the engine but was removed in 1.3.0 because I worried that it used Denpa Engine code
2. I will consider it!
3. A character select sounds kiiiinda complex, so i won't be adding that

**Comment by StinkTheStinker** [comment]
> 1. Do you mean the camera bouncing on a beat hit in the title state? That was originally in the engine but was removed in 1.3.0 because I worried that it used Denpa Engine code. I may re-add it, using the code from PlayState maybe?

Yes

**Comment by StinkTheStinker** [comment]
oh yea, you should add the death settings to in the data tab

**Comment by MrSropical** [comment]
Try adding a setting that gives any character his own noteskin\noteplsahes

**Comment by StinkTheStinker** [comment]
blud thinks this is his issue thing

**Comment by MrSropical** [comment]
> 3. A character select sounds kiiiinda complex, so i won't be adding that

i can code it anyway

**Comment by StinkTheStinker** [comment]
> Try adding a setting that gives any character his own noteskin\noteplsahes

also, when you have a issue/question/feature request, make a new issue

**Comment by StinkTheStinker** [comment]
like, your own one
