### ISSUE TITLE
cant open chart editor unless i go through 7 in main menu

### ISSUE THREAD

**Issue by Marioispro1** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#73]
### Describe your bug here.

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/133698570/cdb4c3d8-a185-4b3d-a318-bb2b52d8faf6

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
what's your 7 event set to? it only goes to the chart editor if you have it set to "None", null or "---"

**Comment by Marioispro1** [comment]
> what's your 7 event set to? it only goes to the chart editor if you have it set to "None", null or "---"

how do i do that exactly

**Comment by JordanSantiagoYT** [comment]
you're supposed to set it in the chart editor, if there's no event then it sets to ---

**Comment by Marioispro1** [comment]
as i sent that my js engine just crashed holup

**Comment by Marioispro1** [comment]
alr ty
