### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by Miuthoi123** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#74]
### Describe your bug here.

i open js engine and open any songs and ... it crash.

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/117433468/a7b77411-bf60-4c49-804f-02c3eb6a635f

### Command Prompt/Terminal logs (if existing)

Yes
```bash
PlayState.hx (Line 2188)
flixel/FlxGame.hx (Line 642)
flixel/FlxGame.hx (Line 729)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 550)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by MemeHovy** [comment]
turn off hideHud for now

**Comment by Miuthoi123** [comment]
> turn off hideHud for now
I turned it off

**Comment by StinkTheStinker** [comment]
it might be the os, random guess. open a virtual box with windows 10 in it and download JS Engine on the virtual box

**Comment by JordanSantiagoYT** [comment]
It's a hideHud issue. it's fixed in a recent commit!
