### ISSUE TITLE
FNF Start Menu Logo Y Axis issue (it is annoying as fuck)

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#76]
### Describe your bug here.

So, I changed the start menu logo on the engine ofc, and when I change the Y-Axis, It starts there, than it goes to the default offset.

--------Video for more context----------

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/2b922a27-40a0-4b27-a243-b377be11747d

### Command Prompt/Terminal logs (if existing)

None

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Start Menu Logo

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
Fixed in https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/4a95aac1a2d3b93d32e61846ee67b3deb7c48f9c!
