### ISSUE TITLE
Trying to put a different bf death scene

### ISSUE THREAD

**Issue by PlayerAdante1** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#77]
### Describe your bug here.

function onCreate()
	-- CHARACTER
	setPropertyFromClass('substates.GameOverSubstate', 'characterName', 'shapey_bf-dead');
	
	-- SOUNDS/MUSICS
	setPropertyFromClass('substates.GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --file goes inside sounds/ folder
	setPropertyFromClass('substates.GameOverSubstate', 'loopSoundName', 'gameOver'); --file goes inside music/ folder
	setPropertyFromClass('substates.GameOverSubstate', 'endSoundName', 'gameOverEnd'); --file goes inside music/ folder
end

but it didn't work on data or script TOT

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
are you using android? if not, does the character exist?

**Comment by PlayerAdante1** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/109116149/4da6631b-599d-450c-b225-0396082103d8

**Comment by JordanSantiagoYT** [comment]
what do you mean by the script not working? it seems to be working for me

**Comment by PlayerAdante1** [comment]
I used a the death script https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by PlayerAdante1** [comment]
never mind i had to change it to GameOverSubstate
