### ISSUE TITLE
Null Object Reference when you enable Hide HUD option 

### ISSUE THREAD

**Issue by Stefan2008Git** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#78]
### Describe your bug here.

It's seems like this person had an issue if you enable Hide HUD option to appear Null Object Reference @JordanSantiagoYT 
![Screenshot_2023-11-17-08-46-51-137_com discord-edit](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/126715034/875b58c0-c5b9-43eb-bcac-93a2a4f6f703)

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (Line 2188)
 flixel/FlxGame.hx (Line 642)
 flixel/FlxGame.hx (Line 729)
 flixel/FlxGame.hx (Line 682)
 flixel/FlxGame.hx (Line 556)
 openfl/events/EventDispatcher.hx (Line 444)
 openfl/display/DisplayObject.hx (Line 1400)

 Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, i am simply here to report some people issue

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

**Comment by JordanSantiagoYT** [comment]
already fixed, found out that if botplayTxt isn’t created when botplayTxt.destroy is run then a null object reference happens, but if you look in the source that issue should be fixed!
