### ISSUE TITLE
LATEST ACTION BUILD BUGS

### ISSUE THREAD

**Issue by Ollieq1977336** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#80]
### Describe your bug here.

_Bit of a problem with the latest action build. When you have show notes off, they dont even play anymore with botplay._

oh yea theres also 2 health counters but idfk why

Video provided

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/112081585/cfb41cc0-7545-4b17-9043-acaa4a150f74

i was trying to use the funni denpa engine bug, but il try and code it in lua for now.

### Command Prompt/Terminal logs (if existing)

```bash
Nope, no logs!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

NOTHING. ***only mods***

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
me when i commit an oopsie:

**Comment by Ollieq1977336** [comment]
me when the when the me when me the when

**Comment by JordanSantiagoYT** [comment]
fixed: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/actions/runs/6907815391
