### ISSUE TITLE
Bug Report!

### ISSUE THREAD

**Issue by ItsYaProgramPlayzXD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#81]
### Describe your bug here.

I Download "THE LOST FILES" Mod
But When I Played It
It Crashed!
Heres The Error Code:

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (Line 7450)
PlayState.hx (Line 5932)
flixel/group/FlxGroup.hx (Line 787)
PlayState.hx (Line 5840)
flixel/FlxState.hx (Line 222)
flixel/FlxGame.hx (Line 752)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I Put 1 Mod

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by MemeHovy** [comment]
what version are you using?

**Comment by StinkTheStinker** [comment]
also, is it extracted? extract it and transfer the mod files to the mod folder  it self

**Comment by JordanSantiagoYT** [comment]
turn off double note ghosts

**Comment by JordanSantiagoYT** [comment]
Double Note Ghosts issue should be fixed in a recent commit.
