### ISSUE TITLE
Crash on latest version.

### ISSUE THREAD

**Issue by BostinTeaParty** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#82]
### Describe your bug here.

Game crashes on picking any song

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (Line 7450)
PlayState.hx (Line 5932)
flixel/group/FlxGroup.hx (Line 787)
PlayState.hx (Line 5840)
flixel/FlxState.hx (Line 222)
flixel/FlxGame.hx (Line 752)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I literally emptied the mods folder, gives the following error: PlayState.hx (Line 1318) flixel/FlxGame.hx (Line 642) flixel/FlxGame.hx (Line 729) flixel/FlxGame.hx (Line 682) flixel/FlxGame.hx (Line 550) openfl/events/EventDispatcher.hx (Line 444) openfl/display/DisplayObject.hx (Line 1400)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
just keep the mods folder in, i dont think it impacts the performance

**Comment by JordanSantiagoYT** [comment]
turn off double note ghosts
