### ISSUE TITLE
Charting menu problem

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#84]
### Describe your bug here.

When I press "7" it wont pull up the charting menu. When i press 8 it opens up the character editor. which i have to go to the main menu and head to the charting menu

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, im just tryna chart.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
this is off too
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/1e8fa32c-0fb2-41cc-b3b4-14cb06429fcd)

**Comment by StinkTheStinker** [comment]
let me send the mod folder rq

https://drive.google.com/file/d/1Jhql9WtO3ughMNjljOH9PHz5h-B_MCFA/view?usp=sharing

There is an early version included

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/9771d45c-83c9-460f-bcde-990e21aba37d)
for once i finally have the issue that you're talking about

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/00ff442e-8ec7-4376-b317-4d52a35c7501)
LM

**Comment by JordanSantiagoYT** [comment]
are you using 1.14.0?

**Comment by JordanSantiagoYT** [comment]
eh

1. Issue could not be reproduced on my version.
2. The haxe logo thing might not be fixable.

**Comment by StinkTheStinker** [comment]
> are you using 1.14.0?

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/f6e34d7e-ee4b-497f-8abd-583ba448afce)
yes

**Comment by JordanSantiagoYT** [comment]
what 7 event did you put in your song? it only takes you to the chart editor if you set it to "None", "---" or null

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/87889447-9b6a-4734-a399-a558ddb41149)

**Comment by StinkTheStinker** [comment]
holy fuckin shit i get it now

**Comment by StinkTheStinker** [comment]
you gotta make the default 7 event "None" which brings up the charting state

**Comment by StinkTheStinker** [comment]
since the "---" one doesnt do anything at all

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/9642e97a-cb8a-4582-8397-29192bbc337d)
guh??

**Comment by StinkTheStinker** [comment]
hold on let me record a video of whats goin on

**Comment by StinkTheStinker** [comment]
is there a site to show what key you are pressing?

**Comment by StinkTheStinker** [comment]
while playing a game?

**Comment by JordanSantiagoYT** [comment]
> is there a site to show what key you are pressing?

there are osu! kps's that you can use

**Comment by StinkTheStinker** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a334e2a7-b583-423f-a633-941a4eb14bc3

**Comment by StinkTheStinker** [comment]
when the key turns blue, it means that i clicked on the key, it is a bit laggy, dont know why
