### ISSUE TITLE
Songs crash when botplay presses the FIRST note

### ISSUE THREAD

**Issue by REALCraylenGD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#86]
### Describe your bug here.

I just played one song, it **DID** load but when Botplay pressed the first note of the song, the game crashed.
I updated to the latest version of JS Engine (1.15.0 at this time), and ***SOMETHING*** must've gone ***WRONG.***
![Screenshot 2023-11-23 235608](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/77181802/fec58dd4-b5a0-406f-91d4-25d451ee3edf)

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/2c9e92f1-e4e7-4816-8708-8e58c53137f0)
turn on "Enable Note Colors", apparently i forgot to check if disabling that crashes with note splashes

**Comment by REALCraylenGD** [comment]
Thanks, it worked!

**Comment by JordanSantiagoYT** [comment]
oh yeah, i pushed out a hotfix build that fixes this
