### ISSUE TITLE
Android Build will not load .JSEngine after the first time you download and open itit

### ISSUE THREAD

**Issue by Eeeeeeasrss** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#87]
### Describe your bug here.

I downloaded the Android Build, and I was able to open it, but after i deleted the .JSEngine, and redownloaded the app again, the .JSEngine did not appear. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I did delete the .JSEngine, but I am usually able to get it back after redownloading the application.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by Eeeeeeasrss** [comment]
Another thing to mention, I do have the assets in the .PsychEngine folder. It just will not load after the first time you download it and open it

**Comment by JordanSantiagoYT** [comment]
you have to move the files and stuff to .JSEngine now

**Comment by Guzqn** [comment]
> you have to move the files and stuff to .JSEngine now

What files?

**Comment by JordanSantiagoYT** [comment]
> > you have to move the files and stuff to .JSEngine now
> 
> What files?

the stuff inside .PsychEngine, that folder isn't used anymore since 1.14.0
