### ISSUE TITLE
Bug after window name change from song

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#88]
### Describe your bug here.

I guess im the bug spotter in this engine. Jokes aside, you should know by the title, screen shot is below.
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/70ef38c4-686e-4516-b6f1-4c6b521342ee)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
whoopsies, forgot to fix that, that's if you never changed the window name SORRY i may fix that with 1.16.0

**Comment by StinkTheStinker** [comment]
theres another one, idk how to explain it, so ill record it give me a sec

**Comment by StinkTheStinker** [comment]
i gotta fix somethin on the weeks :skull:

**Comment by JordanSantiagoYT** [comment]
IM PUSHING OUT ANOTHER HOTFIX BUILD, THIS SHOULD FIX THIS ISSUE

**Comment by StinkTheStinker** [comment]
hold on

**Comment by StinkTheStinker** [comment]
dont make one yet

**Comment by StinkTheStinker** [comment]
why tf did the 15 build make so much issues, like holy shit bruh

**Comment by JordanSantiagoYT** [comment]
E?

**Comment by JordanSantiagoYT** [comment]
> why tf did the 15 build make so much issues, like holy shit bruh

you're prob using the haxelib versions for psych 0.7

**Comment by StinkTheStinker** [comment]
no, im talkin about the non source code

**Comment by StinkTheStinker** [comment]
ima (try to) explain this with voice

**Comment by StinkTheStinker** [comment]
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/8029f153-4e38-4315-8b00-25b78483c5f8

**Comment by StinkTheStinker** [comment]
my keyboard is loud as fuck

**Comment by JordanSantiagoYT** [comment]
DOWNLOAD THE BUILD AGAIN!! it fixes that issue

**Comment by StinkTheStinker** [comment]
i am moving the stuff i changed to the mod thing

**Comment by StinkTheStinker** [comment]
i dont see it

**Comment by JordanSantiagoYT** [comment]
wdym? the release page in github should have it

**Comment by StinkTheStinker** [comment]
its the og 1.15

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/7afc11f4-9a35-455e-8d4d-76199c83d149)

**Comment by StinkTheStinker** [comment]
so much fuckin issues today tf?

**Comment by JordanSantiagoYT** [comment]
check the release and download that build again, i edited it

**Comment by StinkTheStinker** [comment]
ohh

**Comment by StinkTheStinker** [comment]
you should prob edit the changelogs if its not edited

**Comment by StinkTheStinker** [comment]
is this the most biggest issue list in one day or some shit?

**Comment by StinkTheStinker** [comment]
is this the heading for the credit heading?

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/bb92d149-4026-42ae-b3a9-cb58e19cea68)

**Comment by StinkTheStinker** [comment]
forgot the screenshot :skull:

**Comment by JordanSantiagoYT** [comment]
yeah it is

**Comment by StinkTheStinker** [comment]
ima edit it

**Comment by StinkTheStinker** [comment]
is the modchart on cheating built in?

**Comment by JordanSantiagoYT** [comment]
no

**Comment by StinkTheStinker** [comment]
i didnt add it as well :skull:

**Comment by StinkTheStinker** [comment]
holy fuckin shit it worked
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a7efc88f-8ec8-4f37-9cdd-4696bef7c35f)

**Comment by StinkTheStinker** [comment]
the hue makes it perfect

**Comment by StinkTheStinker** [comment]
you should prob add a feature where you can turn off/on the credits hue in settings

**Comment by JordanSantiagoYT** [comment]
nah, it would be an unnecessary option

**Comment by StinkTheStinker** [comment]
yea good point

**Comment by StinkTheStinker** [comment]
also, found somethin thats annoying

**Comment by StinkTheStinker** [comment]
when you load an incorrect chart, it crashes, no anti crash

**Comment by JordanSantiagoYT** [comment]
huh. to me it doesn't

**Comment by StinkTheStinker** [comment]
on the chart editor
