### ISSUE TITLE
WHAT I HAVE TO DO NOW

### ISSUE THREAD

**Issue by Guzqn** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#89]
### What is your question?

I installed the apk and accepted all permissions but when I press ok it crashes.... What do I do now?

**Comment by Guzqn** [comment]
Still waiting an answer.....

**Comment by Guzqn** [comment]
why nobody is answering :(

**Comment by BambiGaming2022** [comment]
idk
