### ISSUE TITLE
songs didnt got saved as a week??

### ISSUE THREAD

**Issue by Mushymushroom12** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#9]
### Describe your bug here.

idk if you know this bug where you could not save a song json into a week or something like that but this seems new to me bcuz it never happened before ever did i do something wrong here?? (note: i got the json and the inst and vocals, and the story mode is where i was trying to find the week but couldnt find it anywhere)
![uoh3](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/76ef71f4-8f57-4d4a-8c12-e70bbfa48447)
![uoh2](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/6f011553-2332-4937-9c4f-416592ba87ef)
![uoh](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/140804898/8bc02c2d-e618-4d5b-988c-38ba34f47ae2)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JordanSantiagoYT** [comment]
did you put the week json into mods/weeks? if so, open the week's json and check for "hideStoryMode". if it's set to true, set it to false and it should show up in story mode!

**Comment by Mushymushroom12** [comment]
its fixed ig idk how it did that cause i never been activating the "hidestorymode"
