### ISSUE TITLE
Very few events casusing a lot of lag

### ISSUE THREAD

**Issue by SMWpalkia** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#90]
### Describe your problem here.

My computer is known to have performance issues but when I load up a specific song, the fps stays consistently around 7. I currently have 32 events in the song and they're either a white flash for 1 second or a character change. [The drive link is to me recording it on my phone because obs tanks the performance as well and the file size is too big
](https://drive.google.com/file/d/1AlUqL-6Uo6q5PF0zt-YE7lFDwlHIuQye/view?usp=sharing)
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only the events of the song. I have other things edited such as the main menu but that hasn't effected performance at all

**Comment by JordanSantiagoYT** [comment]
> My computer is known to have performance issues

why not check other songs?

if so, then your problem is being caused by your pc being bad, not the engine (no offense)

**Comment by JordanSantiagoYT** [comment]
alternatively your problem could be caused by the sprites of the characters loaded being very big

**Comment by JordanSantiagoYT** [comment]
because when you add a "Change Character" event, the character is precached when the song is loaded so that a lagspike doesnt occur when the character changes

**Comment by SMWpalkia** [comment]
No offense taken, it's only that song though

And yeah the size is probably the issue

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/c975d57e-3c84-46da-b64e-9926222c0869)
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/705949eb-d2aa-4318-a4ae-aa7a7d117370)
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/136278510/f0379d99-89d5-4d8d-a001-bf6a634ef359)

**Comment by SMWpalkia** [comment]
i assume the solution is to just make them smaller?

**Comment by JordanSantiagoYT** [comment]
maybe that's the solution

**Comment by SMWpalkia** [comment]
Alright thanks. I'll try that later so I'm keeping this issue open in case it goes wrong if that's alr
