### ISSUE TITLE
Anti-Crash on character editor

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#91]
### What feature do you want to get added on the **base** engine?

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/befe23e6-c838-4b87-b451-0fad5ca93f98)
I was organizing stuff on the mods folder (mods/images/characters) and aparently i messed it up, but i noticed you should add that

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by JordanSantiagoYT** [comment]
YOU'RE SO RIGHT, i should add an anti crash for the character editor since i did it for the chart editor

**Comment by JordanSantiagoYT** [comment]
added (https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/commit/39969a13bf3e2f421cc1cd286120e66795295250)
