### ISSUE TITLE
Alt+Click (on one of the notes) don't work.

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#92]
### Describe your bug here.

More details on the video below:

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/8c6c0549-ca77-44b7-873f-06b0d4a4e345

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, just chartin bruh :skull:

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
The one I clicked on after the last one was a missing note. The context here is that when I do the alt+click thing, it does not do anything on the missing note, it just turns it into a normal note when the selected note type was "Phone".

Ex just in case: Replace missing note with death note switches to normal note. (this applies on every type of notes)

Note: This should be in ChartingState.hx

**Comment by StinkTheStinker** [comment]
+ it's small, just so it's easier for obs to make it smoother. Prob was to small.
Just full screen it if its to small

**Comment by StinkTheStinker** [comment]
also, i think the results are wrong
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/ad8fd6cc-7c2f-40f2-82e6-3ac972b23eeb)

**Comment by StinkTheStinker** [comment]
oh shit i just got an idea

**Comment by StinkTheStinker** [comment]
if you dont want the js engine update popping up, there should be a lua or txt file to set it to true/false

**Comment by StinkTheStinker** [comment]
and an option to turn this little shithead off
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/3e066627-2c00-4e1e-9f94-dca4a9a375d8)

**Comment by JordanSantiagoYT** [comment]
> ### Describe your bug here.
> More details on the video below:
> 
>  2023-11-28.20-06-38.mp4 
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Nah, just chartin bruh 💀
> 
> ### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?
> None

that’s because a note type is missing


> if you dont want the js engine update popping up, there should be a lua or txt file to set it to true/false

there’s also an option for that in the bottom of the visuals and ui menu

**Comment by StinkTheStinker** [comment]
> that’s because a note type is missing
i want it to be changed when its missing, its quicker

**Comment by StinkTheStinker** [comment]
fuckin thing bugged out

**Comment by JordanSantiagoYT** [comment]
tried fixing but i don't know how
