### ISSUE TITLE
Note volume glitch or some shit

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#93]
### Describe your bug here.

When you change the volume while notes are playing, it plays when you don't change the volume when a note hit happens sometimes. I currently don't have video. But, I will add it soon.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
Ima do a fuckin playthrough of cheating and ill send it

**Comment by StinkTheStinker** [comment]
but not right now, ill do it later

**Comment by StinkTheStinker** [comment]
nvm

**Comment by StinkTheStinker** [comment]
now the bug isnt doing anything

**Comment by StinkTheStinker** [comment]
also, the accuracy does not work
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/b554432f-7eb2-44f8-a362-82aec3637954)

**Comment by StinkTheStinker** [comment]
unless if you fixed it on the hotfix or somethin

**Comment by StinkTheStinker** [comment]
i dont want to keep updating :very big cry emoji meme:

**Comment by StinkTheStinker** [comment]
this will be the last update ill download

**Comment by JordanSantiagoYT** [comment]
neither issue you mentioned could be reproduced

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/eae54ed5-4e75-44c3-9aba-236d98b5c666
