### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by Stefan2008Git** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#94]
### Describe your bug here.

Ye
![Capture_decran_2023-11-30_132801](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/126715034/c20c1e31-3c12-41d9-a247-2f4c9a66b69f)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No?

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

**Comment by JordanSantiagoYT** [comment]
null strum

**Comment by JordanSantiagoYT** [comment]
wait a minute, YOURE PLAYING MIDDLESCROLL AND HAVE THE OPPONENT MODE TURNED ON that’s why it’s crashing

**Comment by Stefan2008Git** [comment]
> wait a minute, YOURE PLAYING MIDDLESCROLL AND HAVE THE OPPONENT MODE TURNED ON that’s why it’s crashing

Well, this is not an my issue, but okay
