### ISSUE TITLE
Uhhhh, so I was just messing with my FNF Mod, trying to fix something COMPLETELY different, and I made it worse and can not figure out what I did wrong.

### ISSUE THREAD

**Issue by Xenith-MROHIO6337** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#95]
### Describe your bug here.

The is bug/crash whenever I go to "Optimizations," and turn OFF "Chars and Bg," and go play a song. it crashes and I do NOT know how to fix it. Unless it is a bug you guys are trying to fix?

I am using the latest available PUBLIC version for the JS-Engine

Help please?

### Command Prompt/Terminal logs (if existing)

```bash
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

This is the, "Whenever I go to "Optimizations," and turn OFF "Chars and Bg," and go play a song. it crashes" bug.

PlayState.hx (Line 1341)
flixel/FlxGame.hx (Line 642)
flixel/FlxGame.hx (Line 729)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 550)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I do not know what I edited, :sob:

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
just a gfGhost issue for the millionth time, i’ll try to fix it some day but i just don’t know how
