### ISSUE TITLE
Can't figure out a title

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#96]
### What feature do you want to get added on the **base** engine?

Should there be a cam shake when a very spammy part happens?

Screenshots:
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/4870dcad-f147-49ed-96ba-6cdb40cfd156)
Current zoom: 2
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/217a638d-d4cb-4365-9fcf-193b52f6a3c7)
Current zoom: 4

The more notes it is, the more intensity it is (+0.1)

Normal intensity is 0.1

Max intensity is 1 (optional to add max intenisty

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by StinkTheStinker** [comment]
i mean, you added the cam zoom when 2+ notes are hit at the same time, why not just copy it and change it up a bit

**Comment by StinkTheStinker** [comment]
im not a coder, but i can still come up with quick things to do

**Comment by StinkTheStinker** [comment]
you want this kept open?

**Comment by JordanSantiagoYT** [comment]
A, it's up to you

**Comment by JordanSantiagoYT** [comment]
OH, maybe i can make it trigger a camera shake if the NPS is over 100

**Comment by StinkTheStinker** [comment]
that works. even though idk coding

**Comment by StinkTheStinker** [comment]
put that in 1.16

**Comment by JordanSantiagoYT** [comment]
wait, nvm cause it would still shake for another second

**Comment by StinkTheStinker** [comment]
let me think before this closes
