### ISSUE TITLE
WeekSong1 does not go to WeekSong2+

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#98]
### Describe your bug here.

putted subway surfers for the funny, jokes aside, here is the video:

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a1efcc31-a060-4c4d-aaf4-56ddb653958e

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only the main weeks "1 (not finished), 2, 3", not in source code

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by StinkTheStinker** [comment]
note: week1 is bambi, week2 is dave, week3 is ? (thats the actual name)

**Comment by JordanSantiagoYT** [comment]
did you turn on troll mode

**Comment by StinkTheStinker** [comment]
nope, never turn it on

**Comment by StinkTheStinker** [comment]
tf is an action build

**Comment by JordanSantiagoYT** [comment]
ah shit identified the issue

js engine rechart option loops the first song in a week if turned off

**Comment by StinkTheStinker** [comment]
dificult to read, but its off too 
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/527a29cf-42ac-43db-bf6a-8b5fe4fbe9bf)

**Comment by Stefan2008Git** [comment]
> tf is an action build

It's an tab on GitHub repository that you can get build without waiting for fully release

**Comment by StinkTheStinker** [comment]
couldve said "commited" build

**Comment by JordanSantiagoYT** [comment]
fix ed

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/984a2391-ef69-4863-bc49-ee81bc4bf507

**Comment by StinkTheStinker** [comment]
> fix ed
> 
>  2023-12-03.18-15-30.mp4

what

**Comment by StinkTheStinker** [comment]
does it fuck up the game if i putt the  "old game/assets", and the "old game/mods" to the new build?

**Comment by StinkTheStinker** [comment]
the same bug happens when the rechart is on

**Comment by JordanSantiagoYT** [comment]
ah ok

**Comment by StinkTheStinker** [comment]
luckly it does not

**Comment by StinkTheStinker** [comment]
it does not work still

**Comment by StinkTheStinker** [comment]
did you forget to do that?

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/f223db4f-25ab-4e33-8893-3ff2fe95ea8e)

**Comment by StinkTheStinker** [comment]
https://drive.google.com/drive/folders/1rIOhUFQoC7-V_lhTCtZATDOk88gq2Z3e?usp=sharing
there

**Comment by StinkTheStinker** [comment]
it aint for me

**Comment by JordanSantiagoYT** [comment]
> how tf

i reproduced the bug.. by turning troll mode on.

**Comment by StinkTheStinker** [comment]
what is troll mode supposed to do anyway

**Comment by StinkTheStinker** [comment]
now i played the song again, theres a part in the chart i need to fix

**Comment by JordanSantiagoYT** [comment]
> i think you broke chart editor ![image](https://private-user-images.githubusercontent.com/145304742/287570235-0ecf712e-fbdd-48c9-8618-7914bf3aa900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTUyODEsIm5iZiI6MTcwMTY1NDk4MSwicGF0aCI6Ii8xNDUzMDQ3NDIvMjg3NTcwMjM1LTBlY2Y3MTJlLWZiZGQtNDhjOS04NjE4LTc5MTRiZjNhYTkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQwMTU2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGFhNjc5NTllNTdlYmU0ZTExOGM2ZjIyMzM4NGQ4Mjk5M2RmMjJlMDc2ZWMwOWM5YTJhOTYzZjMyYzRhZWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wE0hxGQApHMGcmVjyVWWmT1QXHd7Yx6MwsE5UDiN8xc)

nah thats intentional

**Comment by StinkTheStinker** [comment]
show grid and lil buddies is off on default.

note: the funny guys are there when it was turned off at first

**Comment by StinkTheStinker** [comment]
even after the rechart its like that still
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/5c2ef93f-7b78-4c28-bc13-8a447189bca7)

**Comment by StinkTheStinker** [comment]
the fnf weekness tbh

**Comment by JordanSantiagoYT** [comment]
can you check if it still happens in freeplay

**Comment by StinkTheStinker** [comment]
also, can you make it do the original "song.json" instead of "song-normal.json"?
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/841c8235-6b71-477a-baaa-6121e4be4217)
the one thats crossed out is the -normal file i just now added

**Comment by StinkTheStinker** [comment]
ima test the thing now

**Comment by StinkTheStinker** [comment]
im stupid
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/54df5a5e-b958-4004-9d0a-92df1269cc87)

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/251b780d-6ef6-4ff9-8215-64b97a8c4dff)

**Comment by JordanSantiagoYT** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/129d4161-09bd-4c86-b9d0-b37d8dbf076e)
bruh

**Comment by JordanSantiagoYT** [comment]
oh yeah btw

**Comment by StinkTheStinker** [comment]
?

**Comment by JordanSantiagoYT** [comment]
the "normal" in the difficulties field has to be spelled out like this: "Normal"

**Comment by StinkTheStinker** [comment]
you should fix that

**Comment by JordanSantiagoYT** [comment]
that's why the game treated the normal you have as a custom difficulty

**Comment by StinkTheStinker** [comment]
well, im still usin it. since its not out yet

**Comment by StinkTheStinker** [comment]
wait

**Comment by StinkTheStinker** [comment]
is the loop caused by the results screen

**Comment by StinkTheStinker** [comment]
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/a2af3a89-ab79-40c8-818e-e4dd634b76ff)

**Comment by JordanSantiagoYT** [comment]
> the results screen shows on freeplay, but not story mode

that's intentional, i removed the code that makes it popup there

**Comment by StinkTheStinker** [comment]
the loop?

**Comment by StinkTheStinker** [comment]
Do you think I should be on the team, just for being a bug spotter. Like, I keep finding alot. And letting you know about it.

**Comment by Stefan2008Git** [comment]
> 2023-12-03.20-41-01.mp4 
> worked for me

Bro broked the RGB color for health on engine 💀

**Comment by JordanSantiagoYT** [comment]
> > 2023-12-03.20-41-01.mp4
> > worked for me
> 
> Bro broked the RGB color for health on engine 💀

nah, pretty sure it's because @StinkTheStinker put the old health bar over the new one, where the white part is transparent

**Comment by Stefan2008Git** [comment]
> also, in 1.16.0, characters will be able to have char-specific noteskins
> 
> so you won't need a script for that anymore

Wait the second. Don't even tell me that's an OS Engine moment. That sh#t fork had that too already and I think that's an stollen too maybe from Grafex Engine i guess.

**Comment by StinkTheStinker** [comment]
is the thing fixed?

**Comment by JordanSantiagoYT** [comment]
> > also, in 1.16.0, characters will be able to have char-specific noteskins
> > so you won't need a script for that anymore
> 
> Wait the second. Don't even tell me that's an OS Engine moment. That sh#t fork had that too already and I think that's an stollen too maybe from Grafex Engine i guess.

don't be silly!! 

i got it from vs ron 3.0

**Comment by JordanSantiagoYT** [comment]
> is the thing fixed?

yeah, theres a new commit

**Comment by StinkTheStinker** [comment]
k

**Comment by StinkTheStinker** [comment]
i dont see it

**Comment by StinkTheStinker** [comment]
ima close this, also credited you in my mod
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/acadfa11-0c34-4441-bc63-5d8cd55101ae)
