### ISSUE TITLE
The misterious "Attention" warning message box happen when someone opened JS Engine exe file

### ISSUE THREAD

**Issue by Stefan2008Git** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#99]
### What is your question?

Some person had an weird attention warning box and it's saying this (Quickly let me translate this error):
"This file is self-extracting. Running this program may damage your computer. Do you want to proceed?"
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/126715034/ae8db205-33d5-493d-acae-37ced4081111)

I never saw this error before, but i think the .dll file is corrupted or it's an Haxe issue. Sometimes it can happen with Android too, because it's saying the game is trojan, but remember, it's an Haxe issue with some stuff or something

**Comment by JordanSantiagoYT** [comment]
i'm not sure what to say about this issue. just run the exe, idk how it can even damage your pc. it can only extract files (the ingame updater) and delete itself (running the self destruct function while super danger mode is on)

**Comment by Stefan2008Git** [comment]
> i'm not sure what to say about this issue. just run the exe, idk how it can even damage your pc. it can only extract files (the ingame updater) and delete itself (running the self destruct function while super danger mode is on)

This is not my language. My main language is Serbian and English. Someone called Alexandre reported that bug, not me
